/* eslint-disable @typescript-eslint/camelcase */
import { SmsData } from '../../../store/ducks/sms_events';

export const smsDataFixtures: SmsData[] = [
    {
        EventDate: '2019-09-25',
        sms_type: 'ANC Visit',
        // tslint:disable-next-line: object-literal-sort-keys
        anc_id: '100NG6',
        age: '33',
        health_worker_location_name: 'Saigon',
        health_worker_name: 'Husna Hariz',
        height: 0,
        weight: 68,
        previous_risks: ' NULL',
        lmp_edd: 0,
        parity: 0,
        gravidity: 0,
        message:
            'Blood Pressure = 130-78\nWeight = 68\nCurrent Symptoms = Coughing, Fever, Chronic Disease, Congenital malformation\nSupplements = Takes Supplements\nRisk = high\nContact = 4',
        event_date: '2019-09-25T19:00:56.009000',
        intervention: ' NULL',
        breastfeeding: ' NULL',
        client_type: 'ec_woman',
        gender: 'F',
        child_no: ' NULL',
        first_name: 'habiba',
        second_name: ' NULL',
        third_name: ' NULL',
        last_name: ' NULL',
        date_of_birth: 0,
        year_of_birth: 1986,
        patient_contact: ' NULL',
        location_id: '1234567890987654321',
        contact: '4',
        anc_visit_date: '2020-02-22',
        next_anc_date: '2020-03-12',
        event_id: '1569423656162',
        symptoms: 'HO SOT KN DG',
        status: ' NULL',
        location: 'NHA',
        supplements: 'Takes Supplements',
        micronutrients: ' NULL',
        health_insurance_id: ' NULL',
        appointment_status: 'On Time',
        muac_status: ' NULL',
        response_status: ' NULL',
        risk_level: 'high',
        bmi: 0,
        muac: 0,
        lmp: 0,
        bp: '130-78',
        mother_symptoms: 'Coughing, Fever, Chronic Disease, Congenital malformation',
        ethnicity: ' NULL',
        household: ' NULL',
        toilet: ' NULL',
        handwashing: ' NULL',
        planned_delivery_location: ' NULL',
        death_date: 0,
        location_of_death: ' NULL',
        death_code: ' NULL',
        logface_risk: 'high',
        death_reason: ' NULL',
        child_symptoms: ' NULL',
        delivery_location: ' NULL',
        delivery_method: ' NULL',
        child_risk_level: ' NULL',
        health_worker_contact: 'telegram:782996367',
        team: ' NULL',
    } as unknown,
    {
        EventDate: '2019-10-03',
        sms_type: 'ANC Visit',
        // tslint:disable-next-line: object-literal-sort-keys
        anc_id: '100P9K',
        age: '38y 9m',
        health_worker_location_name: 'Saigon',
        health_worker_name: 'Husna Hariz',
        height: 0,
        weight: 80,
        previous_risks: ' NULL',
        lmp_edd: 0,
        parity: 0,
        gravidity: 0,
        message:
            'Blood Pressure = 129-78\nWeight = 80\nCurrent Symptoms = No symptoms\nSupplements = Takes Supplements\nRisk = No Risk\nContact = 1',
        event_date: '2019-10-03T07:25:24.776000',
        intervention: ' NULL',
        breastfeeding: ' NULL',
        client_type: 'ec_woman',
        gender: 'F',
        child_no: ' NULL',
        first_name: 'Rory',
        second_name: ' NULL',
        third_name: ' NULL',
        last_name: ' NULL',
        date_of_birth: 0,
        year_of_birth: 1981,
        patient_contact: ' NULL',
        location_id: '1234567890987654321',
        contact: '1',
        anc_visit_date: '2019-03-02',
        next_anc_date: '2019-05-02',
        event_id: '1570087524929',
        symptoms: 'BT',
        status: ' NULL',
        location: ' NULL',
        supplements: 'Takes Supplements',
        micronutrients: ' NULL',
        health_insurance_id: ' NULL',
        appointment_status: 'On Time',
        muac_status: ' NULL',
        response_status: ' NULL',
        risk_level: 'No Risk',
        bmi: 0,
        muac: 0,
        lmp: 0,
        bp: '129-78',
        mother_symptoms: 'No symptoms',
        ethnicity: ' NULL',
        household: ' NULL',
        toilet: ' NULL',
        handwashing: ' NULL',
        planned_delivery_location: ' NULL',
        death_date: 0,
        location_of_death: ' NULL',
        death_code: ' NULL',
        logface_risk: ' NULL',
        death_reason: ' NULL',
        child_symptoms: ' NULL',
        delivery_location: ' NULL',
        delivery_method: ' NULL',
        child_risk_level: ' NULL',
        health_worker_contact: 'telegram:782996367',
        team: ' NULL',
    } as unknown,
    {
        EventDate: '2019-10-03',
        sms_type: 'Home ANC Visit',
        // tslint:disable-next-line: object-literal-sort-keys
        anc_id: '100P9K',
        age: '38y 9m',
        health_worker_location_name: 'Saigon',
        health_worker_name: 'Husna Hariz',
        height: 0,
        weight: 80,
        previous_risks: ' NULL',
        lmp_edd: 0,
        parity: 0,
        gravidity: 0,
        message:
            'Blood Pressure = 118-78 \nWeight = 80 \nCurrent Symptoms = No symptoms \nSupplements = Takes Supplements \nRisk = No Risk \nContact = 2',
        event_date: '2019-10-03T07:26:33.645000',
        intervention: ' NULL',
        breastfeeding: ' NULL',
        client_type: 'ec_woman',
        gender: 'F',
        child_no: ' NULL',
        first_name: 'Rory',
        second_name: ' NULL',
        third_name: ' NULL',
        last_name: ' NULL',
        date_of_birth: 0,
        year_of_birth: 1981,
        patient_contact: ' NULL',
        location_id: '1234567890987654321',
        contact: '2',
        anc_visit_date: '0009-04-10',
        next_anc_date: '2019-05-02',
        event_id: '1570087593675',
        symptoms: 'BT',
        status: ' NULL',
        location: ' NULL',
        supplements: 'Takes Supplements',
        micronutrients: ' NULL',
        health_insurance_id: ' NULL',
        appointment_status: 'On Time',
        muac_status: ' NULL',
        response_status: ' NULL',
        risk_level: 'No Risk',
        bmi: 0,
        muac: 0,
        lmp: 0,
        bp: '118-78',
        mother_symptoms: 'No symptoms',
        ethnicity: ' NULL',
        household: ' NULL',
        toilet: ' NULL',
        handwashing: ' NULL',
        planned_delivery_location: ' NULL',
        death_date: 0,
        location_of_death: ' NULL',
        death_code: ' NULL',
        logface_risk: ' NULL',
        death_reason: ' NULL',
        child_symptoms: ' NULL',
        delivery_location: ' NULL',
        delivery_method: ' NULL',
        child_risk_level: ' NULL',
        health_worker_contact: 'telegram:782996367',
        team: ' NULL',
    } as unknown,
    {
        EventDate: '2019-10-03',
        sms_type: 'Delivery Planning',
        // tslint:disable-next-line: object-literal-sort-keys
        anc_id: '100P9K',
        age: '38y 9m',
        health_worker_location_name: 'Saigon',
        health_worker_name: 'Husna Hariz',
        height: 0,
        weight: 0,
        previous_risks: ' NULL',
        lmp_edd: 0,
        parity: 0,
        gravidity: 0,
        message: 'Planned Delivery Location = At home \nCurrent Symptoms = No symptoms',
        event_date: '2019-10-03T07:27:18.103000',
        intervention: ' NULL',
        breastfeeding: ' NULL',
        client_type: 'ec_woman',
        gender: 'F',
        child_no: ' NULL',
        first_name: 'Rory',
        second_name: ' NULL',
        third_name: ' NULL',
        last_name: ' NULL',
        date_of_birth: 0,
        year_of_birth: 1981,
        patient_contact: ' NULL',
        location_id: '1234567890987654321',
        contact: '1',
        anc_visit_date: 0,
        next_anc_date: '2019-05-02',
        event_id: '1570087638129',
        symptoms: 'BT',
        status: ' NULL',
        location: 'NHA',
        supplements: ' NULL',
        micronutrients: ' NULL',
        health_insurance_id: ' NULL',
        appointment_status: 'On Time',
        muac_status: ' NULL',
        response_status: ' NULL',
        risk_level: 'no_risk',
        bmi: 0,
        muac: 0,
        lmp: 0,
        bp: ' NULL',
        mother_symptoms: 'No symptoms',
        ethnicity: ' NULL',
        household: ' NULL',
        toilet: ' NULL',
        handwashing: ' NULL',
        planned_delivery_location: 'At home',
        death_date: 0,
        location_of_death: ' NULL',
        death_code: ' NULL',
        logface_risk: 'no risk',
        death_reason: ' NULL',
        child_symptoms: ' NULL',
        delivery_location: ' NULL',
        delivery_method: ' NULL',
        child_risk_level: ' NULL',
        health_worker_contact: 'telegram:782996367',
        team: ' NULL',
    } as unknown,
    {
        EventDate: '2019-10-03',
        sms_type: 'Social Determinants',
        // tslint:disable-next-line: object-literal-sort-keys
        anc_id: '100P9K',
        age: '38y 9m',
        health_worker_location_name: 'Saigon',
        health_worker_name: 'Husna Hariz',
        height: 0,
        weight: 0,
        previous_risks: ' NULL',
        lmp_edd: 0,
        parity: 0,
        gravidity: 0,
        message:
            'Planned Delivery Location = At home\nHousehold = HNG\nEthnicity = TAY\nToilet = Has no toilet\nHandwashing = Has no handwashing',
        event_date: '2019-10-03T07:29:30.209000',
        intervention: ' NULL',
        breastfeeding: ' NULL',
        client_type: 'ec_woman',
        gender: 'F',
        child_no: ' NULL',
        first_name: 'Rory',
        second_name: ' NULL',
        third_name: ' NULL',
        last_name: ' NULL',
        date_of_birth: 0,
        year_of_birth: 1981,
        patient_contact: ' NULL',
        location_id: '1234567890987654321',
        contact: '1',
        anc_visit_date: 0,
        next_anc_date: 0,
        event_id: '1570087770485',
        symptoms: ' NULL',
        status: ' NULL',
        location: 'NHA',
        supplements: ' NULL',
        micronutrients: ' NULL',
        health_insurance_id: ' NULL',
        appointment_status: 'On Time',
        muac_status: ' NULL',
        response_status: ' NULL',
        risk_level: 'no_risk',
        bmi: 0,
        muac: 0,
        lmp: 0,
        bp: ' NULL',
        mother_symptoms: ' NULL',
        ethnicity: 'TAY',
        household: 'HNG',
        toilet: 'Has no toilet',
        handwashing: 'Has no handwashing',
        planned_delivery_location: 'At home',
        death_date: 0,
        location_of_death: ' NULL',
        death_code: ' NULL',
        logface_risk: 'no risk',
        death_reason: ' NULL',
        child_symptoms: ' NULL',
        delivery_location: ' NULL',
        delivery_method: ' NULL',
        child_risk_level: ' NULL',
        health_worker_contact: 'telegram:782996367',
        team: ' NULL',
    } as unknown,
    {
        EventDate: '2019-10-03',
        sms_type: 'ANC Visit',
        // tslint:disable-next-line: object-literal-sort-keys
        anc_id: '100P9K',
        age: '38y 9m',
        health_worker_location_name: 'Saigon',
        health_worker_name: 'Husna Hariz',
        height: 0,
        weight: 80,
        previous_risks: ' NULL',
        lmp_edd: 0,
        parity: 0,
        gravidity: 0,
        message:
            'Blood Pressure = 119-68\nWeight = 80\nCurrent Symptoms = No symptoms\nSupplements = Takes Supplements\nRisk = low\nContact = 2',
        event_date: '2019-10-03T07:30:08.636000',
        intervention: ' NULL',
        breastfeeding: ' NULL',
        client_type: 'ec_woman',
        gender: 'F',
        child_no: ' NULL',
        first_name: 'Rory',
        second_name: ' NULL',
        third_name: ' NULL',
        last_name: ' NULL',
        date_of_birth: 0,
        year_of_birth: 1981,
        patient_contact: ' NULL',
        location_id: '1234567890987654321',
        contact: '2',
        anc_visit_date: '2019-05-02',
        next_anc_date: '2019-07-02',
        event_id: '1570087808665',
        symptoms: 'BT',
        status: ' NULL',
        location: 'NHA',
        supplements: 'Takes Supplements',
        micronutrients: ' NULL',
        health_insurance_id: ' NULL',
        appointment_status: 'On Time',
        muac_status: ' NULL',
        response_status: ' NULL',
        risk_level: 'low',
        bmi: 0,
        muac: 0,
        lmp: 0,
        bp: '119-68',
        mother_symptoms: 'No symptoms',
        ethnicity: ' NULL',
        household: ' NULL',
        toilet: ' NULL',
        handwashing: ' NULL',
        planned_delivery_location: ' NULL',
        death_date: 0,
        location_of_death: ' NULL',
        death_code: ' NULL',
        logface_risk: 'low',
        death_reason: ' NULL',
        child_symptoms: ' NULL',
        delivery_location: ' NULL',
        delivery_method: ' NULL',
        child_risk_level: ' NULL',
        health_worker_contact: 'telegram:782996367',
        team: ' NULL',
    } as unknown,
    {
        EventDate: '2019-10-03',
        sms_type: 'ANC Visit',
        // tslint:disable-next-line: object-literal-sort-keys
        anc_id: '100P9K',
        age: '38y 9m',
        health_worker_location_name: 'Saigon',
        health_worker_name: 'Husna Hariz',
        height: 0,
        weight: 80,
        previous_risks: ' NULL',
        lmp_edd: 0,
        parity: 0,
        gravidity: 0,
        message:
            'Blood Pressure = 119-68\nWeight = 80\nCurrent Symptoms = No symptoms\nSupplements = Takes Supplements\nRisk = low\nContact = 3',
        event_date: '2019-10-03T07:30:38.168000',
        intervention: ' NULL',
        breastfeeding: ' NULL',
        client_type: 'ec_woman',
        gender: 'F',
        child_no: ' NULL',
        first_name: 'Rory',
        second_name: ' NULL',
        third_name: ' NULL',
        last_name: ' NULL',
        date_of_birth: 0,
        year_of_birth: 1981,
        patient_contact: ' NULL',
        location_id: '1234567890987654321',
        contact: '3',
        anc_visit_date: '2019-07-02',
        next_anc_date: '2019-09-02',
        event_id: '1570087838196',
        symptoms: 'BT',
        status: ' NULL',
        location: 'NHA',
        supplements: 'Takes Supplements',
        micronutrients: ' NULL',
        health_insurance_id: ' NULL',
        appointment_status: 'On Time',
        muac_status: ' NULL',
        response_status: ' NULL',
        risk_level: 'low',
        bmi: 0,
        muac: 0,
        lmp: 0,
        bp: '119-68',
        mother_symptoms: 'No symptoms',
        ethnicity: ' NULL',
        household: ' NULL',
        toilet: ' NULL',
        handwashing: ' NULL',
        planned_delivery_location: ' NULL',
        death_date: 0,
        location_of_death: ' NULL',
        death_code: ' NULL',
        logface_risk: 'low',
        death_reason: ' NULL',
        child_symptoms: ' NULL',
        delivery_location: ' NULL',
        delivery_method: ' NULL',
        child_risk_level: ' NULL',
        health_worker_contact: 'telegram:782996367',
        team: ' NULL',
    } as unknown,
    {
        EventDate: '2019-10-03',
        sms_type: 'Birth Report',
        // tslint:disable-next-line: object-literal-sort-keys
        anc_id: '100P9K',
        age: '38y 9m',
        health_worker_location_name: 'Saigon',
        health_worker_name: 'Husna Hariz',
        height: 48,
        weight: 2.2,
        previous_risks: ' NULL',
        lmp_edd: 0,
        parity: 0,
        gravidity: 0,
        message:
            'Child DOB = 01-10-2019 \nChild Gender = NU \nDelivery Location = At home \nNewborn Symptoms = No symptoms, Hemorrhage/persistent bleeding \nChild Weight = 2.2 \nChild Length = 48 \nChild Risk = red_alert \nBreastfeeding = Breastfeeding during 1st hour\nMother Symptoms = No symptoms, Hemorrhage/persistent bleeding',
        event_date: '2019-10-03T07:31:29.462000',
        intervention: ' NULL',
        breastfeeding: 'Breastfeeding during 1st hour',
        client_type: 'ec_woman',
        gender: 'NU',
        child_no: '100P9K-20191001-01',
        first_name: 'Rory',
        second_name: ' NULL',
        third_name: ' NULL',
        last_name: ' NULL',
        date_of_birth: 0,
        year_of_birth: 1981,
        patient_contact: ' NULL',
        location_id: '1234567890987654321',
        contact: '3',
        anc_visit_date: 0,
        next_anc_date: 0,
        event_id: '1570087889485',
        symptoms: 'BT XH',
        status: ' NULL',
        location: 'NHA',
        supplements: ' NULL',
        micronutrients: ' NULL',
        health_insurance_id: ' NULL',
        appointment_status: 'On Time',
        muac_status: ' NULL',
        response_status: ' NULL',
        risk_level: 'red_alert',
        bmi: 0,
        muac: 0,
        lmp: 0,
        bp: ' NULL',
        mother_symptoms: 'No symptoms, Hemorrhage/persistent bleeding',
        ethnicity: ' NULL',
        household: ' NULL',
        toilet: ' NULL',
        handwashing: ' NULL',
        planned_delivery_location: ' NULL',
        death_date: 0,
        location_of_death: ' NULL',
        death_code: ' NULL',
        logface_risk: 'red',
        death_reason: ' NULL',
        child_symptoms: 'No symptoms, Hemorrhage/persistent bleeding',
        delivery_location: 'At home',
        delivery_method: 'C-Section',
        child_risk_level: 'red_alert',
        health_worker_contact: 'telegram:782996367',
        team: ' NULL',
    } as unknown,
    {
        EventDate: '2019-10-03',
        sms_type: 'Red Alert Report',
        // tslint:disable-next-line: object-literal-sort-keys
        anc_id: '100P9K-20191001-01',
        age: '0m',
        health_worker_location_name: 'Saigon',
        health_worker_name: 'Husna Hariz',
        height: 0,
        weight: 0,
        previous_risks: ' NULL',
        lmp_edd: 0,
        parity: 0,
        gravidity: 0,
        message: 'Symptoms = Coughing, Fever \nLocation = At home \nInterventions = ',
        event_date: '2019-10-03T08:02:40.982000',
        intervention: ' NULL',
        breastfeeding: ' NULL',
        client_type: 'ec_child',
        gender: ' NULL',
        child_no: '01',
        first_name: ' NULL',
        second_name: ' NULL',
        third_name: ' NULL',
        last_name: ' NULL',
        date_of_birth: 0,
        year_of_birth: 2019,
        patient_contact: ' NULL',
        location_id: '1234567890987654321',
        contact: ' NULL',
        anc_visit_date: 0,
        next_anc_date: 0,
        event_id: '1570089812157',
        symptoms: 'HO SOT',
        status: ' NULL',
        location: 'At home',
        supplements: ' NULL',
        micronutrients: ' NULL',
        health_insurance_id: ' NULL',
        appointment_status: 'On Time',
        muac_status: ' NULL',
        response_status: ' NULL',
        risk_level: 'red_alert',
        bmi: 0,
        muac: 0,
        lmp: 0,
        bp: ' NULL',
        mother_symptoms: ' NULL',
        ethnicity: ' NULL',
        household: ' NULL',
        toilet: ' NULL',
        handwashing: ' NULL',
        planned_delivery_location: ' NULL',
        death_date: 0,
        location_of_death: ' NULL',
        death_code: ' NULL',
        logface_risk: 'red',
        death_reason: ' NULL',
        child_symptoms: 'Coughing, Fever',
        delivery_location: ' NULL',
        delivery_method: ' NULL',
        child_risk_level: ' NULL',
        health_worker_contact: 'telegram:782996367',
        team: ' NULL',
    } as unknown,
    {
        EventDate: '2019-10-04',
        sms_type: 'Pregnancy Detection',
        // tslint:disable-next-line: object-literal-sort-keys
        anc_id: '100PAH',
        age: '30y 9m',
        health_worker_location_name: 'Saigon',
        health_worker_name: 'HMN',
        height: 0,
        weight: 0,
        previous_risks: ' NULL',
        lmp_edd: 0,
        parity: 0,
        gravidity: 0,
        message: 'Name = Joy Loiuse  \nPhone Number = +84983105510 \nHealth Insurance = NA',
        event_date: '2019-10-04T06:36:35.102000',
        intervention: ' NULL',
        breastfeeding: ' NULL',
        client_type: 'ec_woman',
        gender: 'F',
        child_no: ' NULL',
        first_name: 'Joy',
        second_name: 'Loiuse',
        third_name: ' NULL',
        last_name: ' NULL',
        date_of_birth: 0,
        year_of_birth: 1989,
        patient_contact: '+84983105510',
        location_id: '1234567890987654321',
        contact: ' NULL',
        anc_visit_date: 0,
        next_anc_date: 0,
        event_id: '1570170995321',
        symptoms: ' NULL',
        status: ' NULL',
        location: ' NULL',
        supplements: ' NULL',
        micronutrients: ' NULL',
        health_insurance_id: ' NULL',
        appointment_status: 'On Time',
        muac_status: ' NULL',
        response_status: ' NULL',
        risk_level: ' NULL',
        bmi: 0,
        muac: 0,
        lmp: 0,
        bp: ' NULL',
        mother_symptoms: ' NULL',
        ethnicity: ' NULL',
        household: ' NULL',
        toilet: ' NULL',
        handwashing: ' NULL',
        planned_delivery_location: ' NULL',
        death_date: 0,
        location_of_death: ' NULL',
        death_code: ' NULL',
        logface_risk: 'Not Set',
        death_reason: ' NULL',
        child_symptoms: ' NULL',
        delivery_location: ' NULL',
        delivery_method: ' NULL',
        child_risk_level: ' NULL',
        health_worker_contact: 'telegram:611765738',
        team: ' NULL',
    } as unknown,
    {
        EventDate: '2019-10-04',
        sms_type: 'Pregnancy Registration',
        // tslint:disable-next-line: object-literal-sort-keys
        anc_id: '100PAH',
        age: '30y 9m',
        health_worker_location_name: 'Saigon',
        health_worker_name: 'HMN',
        height: 145,
        weight: 55,
        previous_risks: 'Previous pregnancy too close or too far, Home Delivery',
        lmp_edd: '2019-10-09',
        parity: 1,
        gravidity: 3,
        message:
            'EDD = 09-10-2019\nGravidity = 3\nParity = 1\nWeight = 55 \nHeight = 145\nBMI = 26\nPrevious Gynaecology History = Previous pregnancy too close or too far, Home Delivery\nCurrent Symptoms = Heavy sweating, Coughing',
        event_date: '2019-10-04T06:38:49.432000',
        intervention: ' NULL',
        breastfeeding: ' NULL',
        client_type: 'ec_woman',
        gender: 'F',
        child_no: ' NULL',
        first_name: 'Joy',
        second_name: ' NULL',
        third_name: ' NULL',
        last_name: ' NULL',
        date_of_birth: 0,
        year_of_birth: 1989,
        patient_contact: ' NULL',
        location_id: '1234567890987654321',
        contact: '0',
        anc_visit_date: '2019-10-04',
        next_anc_date: '2019-07-02',
        event_id: '1570171129630',
        symptoms: 'RMH HO',
        status: ' NULL',
        location: ' NULL',
        supplements: ' NULL',
        micronutrients: ' NULL',
        health_insurance_id: ' NULL',
        appointment_status: 'On Time',
        muac_status: ' NULL',
        response_status: ' NULL',
        risk_level: 'red_alert',
        bmi: 26,
        muac: 0,
        lmp: '2019-01-02',
        bp: '120/80',
        mother_symptoms: 'Heavy sweating, Coughing',
        ethnicity: ' NULL',
        household: ' NULL',
        toilet: ' NULL',
        handwashing: ' NULL',
        planned_delivery_location: ' NULL',
        death_date: 0,
        location_of_death: ' NULL',
        death_code: ' NULL',
        logface_risk: 'red',
        death_reason: ' NULL',
        child_symptoms: ' NULL',
        delivery_location: ' NULL',
        delivery_method: ' NULL',
        child_risk_level: ' NULL',
        health_worker_contact: 'telegram:611765738',
        team: ' NULL',
    } as unknown,
    {
        EventDate: '2019-10-04',
        sms_type: 'Red Alert Report',
        // tslint:disable-next-line: object-literal-sort-keys
        anc_id: '100P9K-20191001-01',
        age: '3d',
        health_worker_location_name: 'Saigon',
        health_worker_name: 'Husna Hariz',
        height: 0,
        weight: 0,
        previous_risks: ' NULL',
        lmp_edd: 0,
        parity: 0,
        gravidity: 0,
        message: 'Symptoms = Coughing, Fever \nLocation = At home \nInterventions = ',
        event_date: '2019-10-04T07:16:38.749000',
        intervention: ' NULL',
        breastfeeding: ' NULL',
        client_type: 'ec_child',
        gender: ' NULL',
        child_no: '01',
        first_name: ' NULL',
        second_name: ' NULL',
        third_name: ' NULL',
        last_name: ' NULL',
        date_of_birth: 0,
        year_of_birth: 2019,
        patient_contact: ' NULL',
        location_id: '1234567890987654321',
        contact: ' NULL',
        anc_visit_date: 0,
        next_anc_date: 0,
        event_id: '1570173399115',
        symptoms: 'HO SOT',
        status: ' NULL',
        location: 'At home',
        supplements: ' NULL',
        micronutrients: ' NULL',
        health_insurance_id: ' NULL',
        appointment_status: 'On Time',
        muac_status: ' NULL',
        response_status: ' NULL',
        risk_level: 'red_alert',
        bmi: 0,
        muac: 0,
        lmp: 0,
        bp: ' NULL',
        mother_symptoms: ' NULL',
        ethnicity: ' NULL',
        household: ' NULL',
        toilet: ' NULL',
        handwashing: ' NULL',
        planned_delivery_location: ' NULL',
        death_date: 0,
        location_of_death: ' NULL',
        death_code: ' NULL',
        logface_risk: 'red',
        death_reason: ' NULL',
        child_symptoms: 'Coughing, Fever',
        delivery_location: ' NULL',
        delivery_method: ' NULL',
        child_risk_level: ' NULL',
        health_worker_contact: 'telegram:782996367',
        team: ' NULL',
    } as unknown,
    {
        EventDate: '2019-10-04',
        sms_type: 'Response Report',
        // tslint:disable-next-line: object-literal-sort-keys
        anc_id: '100P9K-20191001-01',
        age: '3d',
        health_worker_location_name: 'Saigon',
        health_worker_name: 'Husna Hariz',
        height: 0,
        weight: 0,
        previous_risks: ' NULL',
        lmp_edd: 0,
        parity: 0,
        gravidity: 0,
        message: 'Symptoms = No symptoms  \nIntervention = Ambulance On Time \nHealth Status = ',
        event_date: '2019-10-04T07:20:02.008000',
        intervention: 'Ambulance On Time',
        breastfeeding: ' NULL',
        client_type: 'ec_child',
        gender: ' NULL',
        child_no: '01',
        first_name: ' NULL',
        second_name: ' NULL',
        third_name: ' NULL',
        last_name: ' NULL',
        date_of_birth: 0,
        year_of_birth: 2019,
        patient_contact: ' NULL',
        location_id: '1234567890987654321',
        contact: ' NULL',
        anc_visit_date: 0,
        next_anc_date: 0,
        event_id: '1570173602178',
        symptoms: 'BT',
        status: ' NULL',
        location: 'At home',
        supplements: ' NULL',
        micronutrients: ' NULL',
        health_insurance_id: ' NULL',
        appointment_status: 'On Time',
        muac_status: ' NULL',
        response_status: ' NULL',
        risk_level: 'no_risk',
        bmi: 0,
        muac: 0,
        lmp: 0,
        bp: ' NULL',
        mother_symptoms: ' NULL',
        ethnicity: ' NULL',
        household: ' NULL',
        toilet: ' NULL',
        handwashing: ' NULL',
        planned_delivery_location: ' NULL',
        death_date: 0,
        location_of_death: ' NULL',
        death_code: ' NULL',
        logface_risk: 'no risk',
        death_reason: ' NULL',
        child_symptoms: 'No symptoms',
        delivery_location: ' NULL',
        delivery_method: ' NULL',
        child_risk_level: ' NULL',
        health_worker_contact: 'telegram:782996367',
        team: ' NULL',
    } as unknown,
    {
        EventDate: '2019-10-04',
        sms_type: 'Pregnancy Detection',
        // tslint:disable-next-line: object-literal-sort-keys
        anc_id: '100PCF',
        age: '36y ',
        health_worker_location_name: 'Saigon',
        health_worker_name: 'Husna Hariz',
        height: 0,
        weight: 0,
        previous_risks: ' NULL',
        lmp_edd: 0,
        parity: 0,
        gravidity: 0,
        message: 'Name = Matildah Anna Simon \nPhone Number = +84995623456 \nHealth Insurance = 42015120116',
        event_date: '2019-10-04T07:24:07.496000',
        intervention: ' NULL',
        breastfeeding: ' NULL',
        client_type: 'ec_woman',
        gender: 'F',
        child_no: ' NULL',
        first_name: 'Matildah',
        second_name: 'Anna',
        third_name: 'Simon',
        last_name: ' NULL',
        date_of_birth: 0,
        year_of_birth: 1983,
        patient_contact: '+84995623456',
        location_id: '1234567890987654321',
        contact: ' NULL',
        anc_visit_date: 0,
        next_anc_date: 0,
        event_id: '1570173847657',
        symptoms: ' NULL',
        status: ' NULL',
        location: ' NULL',
        supplements: ' NULL',
        micronutrients: ' NULL',
        health_insurance_id: ' NULL',
        appointment_status: 'On Time',
        muac_status: ' NULL',
        response_status: ' NULL',
        risk_level: ' NULL',
        bmi: 0,
        muac: 0,
        lmp: 0,
        bp: ' NULL',
        mother_symptoms: ' NULL',
        ethnicity: ' NULL',
        household: ' NULL',
        toilet: ' NULL',
        handwashing: ' NULL',
        planned_delivery_location: ' NULL',
        death_date: 0,
        location_of_death: ' NULL',
        death_code: ' NULL',
        logface_risk: 'Not Set',
        death_reason: ' NULL',
        child_symptoms: ' NULL',
        delivery_location: ' NULL',
        delivery_method: ' NULL',
        child_risk_level: ' NULL',
        health_worker_contact: 'telegram:782996367',
        team: ' NULL',
    } as unknown,
    {
        EventDate: '2019-10-04',
        sms_type: 'Pregnancy Registration',
        // tslint:disable-next-line: object-literal-sort-keys
        anc_id: '100PCF',
        age: '36y ',
        health_worker_location_name: 'Saigon',
        health_worker_name: 'Husna Hariz',
        height: 160,
        weight: 54,
        previous_risks: 'Diabetes, High blood pressure',
        lmp_edd: '2019-11-01',
        parity: 2,
        gravidity: 3,
        message:
            'EDD = 01-11-2019\nGravidity = 3\nParity = 2\nWeight = 54 \nHeight = 160\nBMI = 21\nPrevious Gynaecology History = Diabetes, High blood pressure\nCurrent Symptoms = Flaccid Paralysis',
        event_date: '2019-10-04T07:24:34.017000',
        intervention: ' NULL',
        breastfeeding: ' NULL',
        client_type: 'ec_woman',
        gender: 'F',
        child_no: ' NULL',
        first_name: 'Matildah',
        second_name: ' NULL',
        third_name: ' NULL',
        last_name: ' NULL',
        date_of_birth: 0,
        year_of_birth: 1983,
        patient_contact: ' NULL',
        location_id: '1234567890987654321',
        contact: '0',
        anc_visit_date: '2019-10-04',
        next_anc_date: '2019-03-22',
        event_id: '1570173874178',
        symptoms: 'LM',
        status: ' NULL',
        location: ' NULL',
        supplements: ' NULL',
        micronutrients: ' NULL',
        health_insurance_id: ' NULL',
        appointment_status: 'On Time',
        muac_status: ' NULL',
        response_status: ' NULL',
        risk_level: 'high',
        bmi: 21,
        muac: 0,
        lmp: '2019-01-25',
        bp: '123-78',
        mother_symptoms: 'Flaccid Paralysis',
        ethnicity: ' NULL',
        household: ' NULL',
        toilet: ' NULL',
        handwashing: ' NULL',
        planned_delivery_location: ' NULL',
        death_date: 0,
        location_of_death: ' NULL',
        death_code: ' NULL',
        logface_risk: 'high',
        death_reason: ' NULL',
        child_symptoms: ' NULL',
        delivery_location: ' NULL',
        delivery_method: ' NULL',
        child_risk_level: ' NULL',
        health_worker_contact: 'telegram:782996367',
        team: ' NULL',
    } as unknown,
    {
        EventDate: '2019-10-11',
        sms_type: 'Death Report',
        // tslint:disable-next-line: object-literal-sort-keys
        anc_id: '100PG5',
        age: '28y ',
        health_worker_location_name: 'Hanoi',
        health_worker_name: 'Huong',
        height: 0,
        weight: 0,
        previous_risks: ' NULL',
        lmp_edd: 0,
        parity: 0,
        gravidity: 0,
        message: 'Date of death = 08-08-2019 \nLocation of Death = At home \nContact = 1',
        event_date: '2019-10-11T03:43:05.318000',
        intervention: ' NULL',
        breastfeeding: ' NULL',
        client_type: 'ec_woman',
        gender: 'F',
        child_no: '01',
        first_name: 'nguyen',
        second_name: ' NULL',
        third_name: ' NULL',
        last_name: ' NULL',
        date_of_birth: 0,
        year_of_birth: 1991,
        patient_contact: ' NULL',
        location_id: '5434567890987654543',
        contact: '1',
        anc_visit_date: 0,
        next_anc_date: 0,
        event_id: '1570765385605',
        symptoms: ' NULL',
        status: ' NULL',
        location: 'NHA',
        supplements: ' NULL',
        micronutrients: ' NULL',
        health_insurance_id: ' NULL',
        appointment_status: 'On Time',
        muac_status: ' NULL',
        response_status: ' NULL',
        risk_level: 'no_risk',
        bmi: 0,
        muac: 0,
        lmp: 0,
        bp: ' NULL',
        mother_symptoms: ' NULL',
        ethnicity: ' NULL',
        household: ' NULL',
        toilet: ' NULL',
        handwashing: ' NULL',
        planned_delivery_location: ' NULL',
        death_date: '2019-08-08',
        location_of_death: 'At home',
        death_code: 'Newborn Death',
        logface_risk: 'no risk',
        death_reason: ' NULL',
        child_symptoms: ' NULL',
        delivery_location: ' NULL',
        delivery_method: ' NULL',
        child_risk_level: ' NULL',
        health_worker_contact: 'telegram:978543639',
        team: ' NULL',
    } as unknown,
    {
        EventDate: '2019-10-11',
        sms_type: 'Red Alert Report',
        // tslint:disable-next-line: object-literal-sort-keys
        anc_id: '100PG5',
        age: '28y ',
        health_worker_location_name: 'Hanoi',
        health_worker_name: 'Huong',
        height: 0,
        weight: 0,
        previous_risks: ' NULL',
        lmp_edd: 0,
        parity: 0,
        gravidity: 0,
        message: 'Symptoms = Hemorrhage/persistent bleeding \nLocation = At home ',
        event_date: '2019-10-11T03:48:58.776000',
        intervention: ' NULL',
        breastfeeding: ' NULL',
        client_type: 'ec_woman',
        gender: 'F',
        child_no: ' NULL',
        first_name: 'nguyen',
        second_name: ' NULL',
        third_name: ' NULL',
        last_name: ' NULL',
        date_of_birth: 0,
        year_of_birth: 1991,
        patient_contact: ' NULL',
        location_id: '5434567890987654543',
        contact: ' NULL',
        anc_visit_date: 0,
        next_anc_date: 0,
        event_id: '1570765739019',
        symptoms: 'XH',
        status: ' NULL',
        location: 'At home',
        supplements: ' NULL',
        micronutrients: ' NULL',
        health_insurance_id: ' NULL',
        appointment_status: 'On Time',
        muac_status: ' NULL',
        response_status: ' NULL',
        risk_level: 'red_alert',
        bmi: 0,
        muac: 0,
        lmp: 0,
        bp: ' NULL',
        mother_symptoms: 'Hemorrhage/persistent bleeding',
        ethnicity: ' NULL',
        household: ' NULL',
        toilet: ' NULL',
        handwashing: ' NULL',
        planned_delivery_location: ' NULL',
        death_date: 0,
        location_of_death: ' NULL',
        death_code: ' NULL',
        logface_risk: 'red',
        death_reason: ' NULL',
        child_symptoms: ' NULL',
        delivery_location: ' NULL',
        delivery_method: ' NULL',
        child_risk_level: ' NULL',
        health_worker_contact: 'telegram:978543639',
        team: ' NULL',
    } as unknown,
    {
        EventDate: '2019-10-11',
        sms_type: 'Response Report',
        // tslint:disable-next-line: object-literal-sort-keys
        anc_id: '100PG5',
        age: '28y ',
        health_worker_location_name: 'Hanoi',
        health_worker_name: 'Huong',
        height: 0,
        weight: 0,
        previous_risks: ' NULL',
        lmp_edd: 0,
        parity: 0,
        gravidity: 0,
        message: 'Symptoms = No symptoms  \nIntervention = MIECD Resource Person Advice \nHealth Status = ',
        event_date: '2019-10-11T03:52:20.281000',
        intervention: 'MIECD Resource Person Advice',
        breastfeeding: ' NULL',
        client_type: 'ec_woman',
        gender: 'F',
        child_no: ' NULL',
        first_name: 'nguyen',
        second_name: ' NULL',
        third_name: ' NULL',
        last_name: ' NULL',
        date_of_birth: 0,
        year_of_birth: 1991,
        patient_contact: ' NULL',
        location_id: '5434567890987654543',
        contact: ' NULL',
        anc_visit_date: 0,
        next_anc_date: 0,
        event_id: '1570765940561',
        symptoms: 'BT',
        status: ' NULL',
        location: 'At home',
        supplements: ' NULL',
        micronutrients: ' NULL',
        health_insurance_id: ' NULL',
        appointment_status: 'On Time',
        muac_status: ' NULL',
        response_status: ' NULL',
        risk_level: 'no_risk',
        bmi: 0,
        muac: 0,
        lmp: 0,
        bp: ' NULL',
        mother_symptoms: 'No symptoms',
        ethnicity: ' NULL',
        household: ' NULL',
        toilet: ' NULL',
        handwashing: ' NULL',
        planned_delivery_location: ' NULL',
        death_date: 0,
        location_of_death: ' NULL',
        death_code: ' NULL',
        logface_risk: 'no risk',
        death_reason: ' NULL',
        child_symptoms: ' NULL',
        delivery_location: ' NULL',
        delivery_method: ' NULL',
        child_risk_level: ' NULL',
        health_worker_contact: 'telegram:978543639',
        team: ' NULL',
    } as unknown,
    {
        EventDate: '2019-10-11',
        sms_type: 'Nutrition Registration',
        // tslint:disable-next-line: object-literal-sort-keys
        anc_id: '100PJ1',
        age: '2m 4d',
        health_worker_location_name: 'Hanoi',
        health_worker_name: 'Huong',
        height: 51,
        weight: 4.2,
        previous_risks: ' NULL',
        lmp_edd: 0,
        parity: 0,
        gravidity: 0,
        message:
            'Name = lo a thu  \nPhone Number = 983187135 \nHealth Insurance = 983187135 \nMUAC = 12 \nWeight = 4.2 \nHeight = 51',
        event_date: '2019-10-11T03:54:44.831000',
        intervention: ' NULL',
        breastfeeding: ' NULL',
        client_type: 'ec_child',
        gender: 'NU',
        child_no: ' NULL',
        first_name: 'lo',
        second_name: 'a',
        third_name: 'thu',
        last_name: ' NULL',
        date_of_birth: 0,
        year_of_birth: 2019,
        patient_contact: '983187135',
        location_id: '5434567890987654543',
        contact: ' NULL',
        anc_visit_date: 0,
        next_anc_date: 0,
        event_id: '1570766085120',
        symptoms: ' NULL',
        status: ' NULL',
        location: ' NULL',
        supplements: ' NULL',
        micronutrients: ' NULL',
        health_insurance_id: ' NULL',
        appointment_status: 'On Time',
        muac_status: ' NULL',
        response_status: ' NULL',
        risk_level: ' NULL',
        bmi: 0,
        muac: 12,
        lmp: 0,
        bp: ' NULL',
        mother_symptoms: ' NULL',
        ethnicity: ' NULL',
        household: ' NULL',
        toilet: ' NULL',
        handwashing: ' NULL',
        planned_delivery_location: ' NULL',
        death_date: 0,
        location_of_death: ' NULL',
        death_code: ' NULL',
        logface_risk: 'Not Set',
        death_reason: ' NULL',
        child_symptoms: ' NULL',
        delivery_location: ' NULL',
        delivery_method: ' NULL',
        child_risk_level: ' NULL',
        health_worker_contact: 'telegram:978543639',
        team: ' NULL',
    } as unknown,
    {
        EventDate: '2019-10-11',
        sms_type: 'Nutrition Report',
        // tslint:disable-next-line: object-literal-sort-keys
        anc_id: '100PJ1',
        age: '2m 4d',
        health_worker_location_name: 'Hanoi',
        health_worker_name: 'Huong',
        height: 60,
        weight: 5,
        previous_risks: ' NULL',
        lmp_edd: 0,
        parity: 0,
        gravidity: 0,
        message:
            'MUAC = 12 \nWeight = 5 \nHeight = 60 \nFeeding Status = BMHT \nSupplements = Child Supplements\nMUAC Classification = Moderate Acute Malnutrition',
        event_date: '2019-10-11T04:07:33.525000',
        intervention: ' NULL',
        breastfeeding: 'To be updated',
        client_type: 'ec_child',
        gender: 'NU',
        child_no: ' NULL',
        first_name: 'lo',
        second_name: ' NULL',
        third_name: ' NULL',
        last_name: ' NULL',
        date_of_birth: 0,
        year_of_birth: 2019,
        patient_contact: ' NULL',
        location_id: '5434567890987654543',
        contact: ' NULL',
        anc_visit_date: 0,
        next_anc_date: 0,
        event_id: '1570766853760',
        symptoms: ' NULL',
        status: 'BMHT',
        location: ' NULL',
        supplements: 'Child Supplements',
        micronutrients: ' NULL',
        health_insurance_id: ' NULL',
        appointment_status: 'On Time',
        muac_status: 'Moderate Acute Malnutrition',
        response_status: ' NULL',
        risk_level: 'high',
        bmi: 0,
        muac: 12,
        lmp: 0,
        bp: ' NULL',
        mother_symptoms: ' NULL',
        ethnicity: ' NULL',
        household: ' NULL',
        toilet: ' NULL',
        handwashing: ' NULL',
        planned_delivery_location: ' NULL',
        death_date: 0,
        location_of_death: ' NULL',
        death_code: ' NULL',
        logface_risk: 'high',
        death_reason: ' NULL',
        child_symptoms: ' NULL',
        delivery_location: ' NULL',
        delivery_method: ' NULL',
        child_risk_level: ' NULL',
        health_worker_contact: 'telegram:978543639',
        team: ' NULL',
    } as unknown,
    {
        EventDate: '2019-10-11',
        sms_type: 'Depature Report',
        // tslint:disable-next-line: object-literal-sort-keys
        anc_id: '100PJ1',
        age: '2m 4d',
        health_worker_location_name: 'Hanoi',
        health_worker_name: 'Huong',
        height: 0,
        weight: 0,
        previous_risks: ' NULL',
        lmp_edd: 0,
        parity: 0,
        gravidity: 0,
        message: 0,
        event_date: '2019-10-11T04:09:11.297000',
        intervention: ' NULL',
        breastfeeding: ' NULL',
        client_type: 'ec_child',
        gender: 'NU',
        child_no: ' NULL',
        first_name: 'lo',
        second_name: ' NULL',
        third_name: ' NULL',
        last_name: ' NULL',
        date_of_birth: 0,
        year_of_birth: 2019,
        patient_contact: ' NULL',
        location_id: '5434567890987654543',
        contact: ' NULL',
        anc_visit_date: 0,
        next_anc_date: 0,
        event_id: '1570766951538',
        symptoms: ' NULL',
        status: ' NULL',
        location: ' NULL',
        supplements: ' NULL',
        micronutrients: ' NULL',
        health_insurance_id: ' NULL',
        appointment_status: 'On Time',
        muac_status: ' NULL',
        response_status: ' NULL',
        risk_level: ' NULL',
        bmi: 0,
        muac: 0,
        lmp: 0,
        bp: ' NULL',
        mother_symptoms: ' NULL',
        ethnicity: ' NULL',
        household: ' NULL',
        toilet: ' NULL',
        handwashing: ' NULL',
        planned_delivery_location: ' NULL',
        death_date: 0,
        location_of_death: ' NULL',
        death_code: ' NULL',
        logface_risk: 'Not Set',
        death_reason: ' NULL',
        child_symptoms: ' NULL',
        delivery_location: ' NULL',
        delivery_method: ' NULL',
        child_risk_level: ' NULL',
        health_worker_contact: 'telegram:978543639',
        team: ' NULL',
    } as unknown,
    {
        EventDate: '2019-10-11',
        sms_type: 'Nutrition Report',
        // tslint:disable-next-line: object-literal-sort-keys
        anc_id: '100PJ1',
        age: '2m 4d',
        health_worker_location_name: 'Hanoi',
        health_worker_name: 'Huong',
        height: 60,
        weight: 5,
        previous_risks: ' NULL',
        lmp_edd: 0,
        parity: 0,
        gravidity: 0,
        message:
            'MUAC = 12 \nWeight = 5 \nHeight = 60 \nFeeding Status = BMHT \nSupplements = Child Supplements\nMUAC Classification = Moderate Acute Malnutrition',
        event_date: '2019-10-11T04:09:16.698000',
        intervention: ' NULL',
        breastfeeding: 'To be updated',
        client_type: 'ec_child',
        gender: 'NU',
        child_no: ' NULL',
        first_name: 'lo',
        second_name: ' NULL',
        third_name: ' NULL',
        last_name: ' NULL',
        date_of_birth: 0,
        year_of_birth: 2019,
        patient_contact: ' NULL',
        location_id: '5434567890987654543',
        contact: ' NULL',
        anc_visit_date: 0,
        next_anc_date: 0,
        event_id: '1570766956799',
        symptoms: ' NULL',
        status: 'BMHT',
        location: ' NULL',
        supplements: 'Child Supplements',
        micronutrients: ' NULL',
        health_insurance_id: ' NULL',
        appointment_status: 'On Time',
        muac_status: 'Moderate Acute Malnutrition',
        response_status: ' NULL',
        risk_level: 'high',
        bmi: 0,
        muac: 12,
        lmp: 0,
        bp: ' NULL',
        mother_symptoms: ' NULL',
        ethnicity: ' NULL',
        household: ' NULL',
        toilet: ' NULL',
        handwashing: ' NULL',
        planned_delivery_location: ' NULL',
        death_date: 0,
        location_of_death: ' NULL',
        death_code: ' NULL',
        logface_risk: 'high',
        death_reason: ' NULL',
        child_symptoms: ' NULL',
        delivery_location: ' NULL',
        delivery_method: ' NULL',
        child_risk_level: ' NULL',
        health_worker_contact: 'telegram:978543639',
        team: ' NULL',
    } as unknown,
] as SmsData[];
