// tslint:disable object-literal-sort-keys
const groupedSmsData = {
  '1569423656162': {
    EventDate: '2019-09-25',
    age: '33',
    anc_id: '100NG6',
    anc_visit_date: '2020-02-22',
    appointment_status: 'On Time',
    bmi: 0,
    bp: '130-78',
    breastfeeding: ' NULL',
    child_no: ' NULL',
    child_risk_level: ' NULL',
    child_symptoms: ' NULL',
    client_type: 'ec_woman',
    contact: '4',
    date_of_birth: 0,
    death_code: ' NULL',
    death_date: 0,
    death_reason: ' NULL',
    delivery_location: ' NULL',
    delivery_method: ' NULL',
    ethnicity: ' NULL',
    event_date: '2019-09-25T19:00:56.009000',
    event_id: '1569423656162',
    first_name: 'habiba',
    gender: 'F',
    gravidity: 0,
    handwashing: ' NULL',
    health_insurance_id: ' NULL',
    health_worker_contact: 'telegram:782996367',
    health_worker_location_name: 'Saigon',
    health_worker_name: 'Husna Hariz',
    height: 0,
    household: ' NULL',
    intervention: ' NULL',
    last_name: ' NULL',
    lmp: 0,
    lmp_edd: 0,
    location: 'NHA',
    location_id: '1234567890987654321',
    location_of_death: ' NULL',
    logface_risk: 'high',
    message: `Blood Pressure = 130-78
Weight = 68
Current Symptoms = Coughing, Fever, Chronic Disease, Congenital malformation
Supplements = Takes Supplements
Risk = high
Contact = 4`,
    micronutrients: ' NULL',
    mother_symptoms: 'Coughing, Fever, Chronic Disease, Congenital malformation',
    muac: 0,
    muac_status: ' NULL',
    next_anc_date: '2020-03-12',
    parity: 0,
    patient_contact: ' NULL',
    planned_delivery_location: ' NULL',
    previous_risks: ' NULL',
    response_status: ' NULL',
    risk_level: 'high',
    second_name: ' NULL',
    sms_type: 'ANC Visit',
    status: ' NULL',
    supplements: 'Takes Supplements',
    symptoms: 'HO SOT KN DG',
    team: ' NULL',
    third_name: ' NULL',
    toilet: ' NULL',
    weight: 68,
    year_of_birth: 1986,
  },
  '1570087524929': {
    EventDate: '2019-10-03',
    age: '38y 9m',
    anc_id: '100P9K',
    anc_visit_date: '2019-03-02',
    appointment_status: 'On Time',
    bmi: 0,
    bp: '129-78',
    breastfeeding: ' NULL',
    child_no: ' NULL',
    child_risk_level: ' NULL',
    child_symptoms: ' NULL',
    client_type: 'ec_woman',
    contact: '1',
    date_of_birth: 0,
    death_code: ' NULL',
    death_date: 0,
    death_reason: ' NULL',
    delivery_location: ' NULL',
    delivery_method: ' NULL',
    ethnicity: ' NULL',
    event_date: '2019-10-03T07:25:24.776000',
    event_id: '1570087524929',
    first_name: 'Rory',
    gender: 'F',
    gravidity: 0,
    handwashing: ' NULL',
    health_insurance_id: ' NULL',
    health_worker_contact: 'telegram:782996367',
    health_worker_location_name: 'Saigon',
    health_worker_name: 'Husna Hariz',
    height: 0,
    household: ' NULL',
    intervention: ' NULL',
    last_name: ' NULL',
    lmp: 0,
    lmp_edd: 0,
    location: ' NULL',
    location_id: '1234567890987654321',
    location_of_death: ' NULL',
    logface_risk: ' NULL',
    message: `Blood Pressure = 129-78
Weight = 80
Current Symptoms = No symptoms
Supplements = Takes Supplements
Risk = No Risk
Contact = 1`,
    micronutrients: ' NULL',
    mother_symptoms: 'No symptoms',
    muac: 0,
    muac_status: ' NULL',
    next_anc_date: '2019-05-02',
    parity: 0,
    patient_contact: ' NULL',
    planned_delivery_location: ' NULL',
    previous_risks: ' NULL',
    response_status: ' NULL',
    risk_level: 'No Risk',
    second_name: ' NULL',
    sms_type: 'ANC Visit',
    status: ' NULL',
    supplements: 'Takes Supplements',
    symptoms: 'BT',
    team: ' NULL',
    third_name: ' NULL',
    toilet: ' NULL',
    weight: 80,
    year_of_birth: 1981,
  },
  '1570087593675': {
    EventDate: '2019-10-03',
    age: '38y 9m',
    anc_id: '100P9K',
    anc_visit_date: '0009-04-10',
    appointment_status: 'On Time',
    bmi: 0,
    bp: '118-78',
    breastfeeding: ' NULL',
    child_no: ' NULL',
    child_risk_level: ' NULL',
    child_symptoms: ' NULL',
    client_type: 'ec_woman',
    contact: '2',
    date_of_birth: 0,
    death_code: ' NULL',
    death_date: 0,
    death_reason: ' NULL',
    delivery_location: ' NULL',
    delivery_method: ' NULL',
    ethnicity: ' NULL',
    event_date: '2019-10-03T07:26:33.645000',
    event_id: '1570087593675',
    first_name: 'Rory',
    gender: 'F',
    gravidity: 0,
    handwashing: ' NULL',
    health_insurance_id: ' NULL',
    health_worker_contact: 'telegram:782996367',
    health_worker_location_name: 'Saigon',
    health_worker_name: 'Husna Hariz',
    height: 0,
    household: ' NULL',
    intervention: ' NULL',
    last_name: ' NULL',
    lmp: 0,
    lmp_edd: 0,
    location: ' NULL',
    location_id: '1234567890987654321',
    location_of_death: ' NULL',
    logface_risk: ' NULL',
    message: `Blood Pressure = 118-78 
Weight = 80 
Current Symptoms = No symptoms 
Supplements = Takes Supplements 
Risk = No Risk 
Contact = 2`,
    micronutrients: ' NULL',
    mother_symptoms: 'No symptoms',
    muac: 0,
    muac_status: ' NULL',
    next_anc_date: '2019-05-02',
    parity: 0,
    patient_contact: ' NULL',
    planned_delivery_location: ' NULL',
    previous_risks: ' NULL',
    response_status: ' NULL',
    risk_level: 'No Risk',
    second_name: ' NULL',
    sms_type: 'Home ANC Visit',
    status: ' NULL',
    supplements: 'Takes Supplements',
    symptoms: 'BT',
    team: ' NULL',
    third_name: ' NULL',
    toilet: ' NULL',
    weight: 80,
    year_of_birth: 1981,
  },
};

export default groupedSmsData;
