/* eslint-disable @typescript-eslint/camelcase */
// tslint:disable object-literal-sort-keys
import { SmsData } from '../../../store/ducks/sms_events';

export const smsSlice: SmsData[] = ([
    {
        EventDate: '2019-10-02',
        sms_type: 'Pregnancy Registration',
        anc_id: '100P7P',
        age: '36y 9m',
        health_worker_location_name: 'Yen Phu Village',
        health_worker_name: 'Husna Hariz',
        height: 165,
        weight: 78,
        previous_risks: 'Previous C-section/forcep/?, Previous convulsion',
        lmp_edd: '2019-12-07',
        parity: 3,
        gravidity: 4,
        message:
            'EDD = 07-12-2019\nGravidity = 4\nParity = 3\nWeight = 78 \nHeight = 165\nBMI = 28\nPrevious Gynaecology History = Previous C-section/forcep/?, Previous convulsion\nCurrent Symptoms = Coughing',
        event_date: '2019-10-02T09:05:50.580000',
        intervention: ' NULL',
        breastfeeding: ' NULL',
        client_type: 'ec_woman',
        gender: 'F',
        child_no: ' NULL',
        first_name: 'priscilla',
        second_name: ' NULL',
        third_name: ' NULL',
        last_name: ' NULL',
        date_of_birth: 0,
        year_of_birth: 1983,
        patient_contact: ' NULL',
        location_id: 'bb37165f-2ee9-4cad-a3b5-020c0cc75ccf',
        contact: '0',
        anc_visit_date: '2019-10-02',
        next_anc_date: '2019-09-02',
        event_id: '1570007157607',
        symptoms: 'HO',
        status: ' NULL',
        location: ' NULL',
        supplements: ' NULL',
        micronutrients: ' NULL',
        health_insurance_id: ' NULL',
        appointment_status: 'On Time',
        muac_status: ' NULL',
        response_status: ' NULL',
        risk_level: 'high',
        bmi: 28,
        muac: 0,
        lmp: '2019-03-02',
        bp: '120/80',
        mother_symptoms: 'Coughing',
        ethnicity: ' NULL',
        household: ' NULL',
        toilet: ' NULL',
        handwashing: ' NULL',
        planned_delivery_location: ' NULL',
        death_date: 0,
        location_of_death: ' NULL',
        death_code: ' NULL',
        logface_risk: 'high',
        death_reason: ' NULL',
        child_symptoms: ' NULL',
        delivery_location: ' NULL',
        delivery_method: ' NULL',
        child_risk_level: ' NULL',
        health_worker_contact: 'telegram:782996367',
        team: ' NULL',
    },
    {
        EventDate: '2019-10-02',
        sms_type: 'Social Determinants',
        anc_id: '100P7P',
        age: '36y 9m',
        health_worker_location_name: 'Yen Phu Village',
        health_worker_name: 'Husna Hariz',
        height: 0,
        weight: 0,
        previous_risks: ' NULL',
        lmp_edd: 0,
        parity: 0,
        gravidity: 0,
        message:
            'Planned Delivery Location = At home\nHousehold = HNG\nEthnicity = TAY\nToilet = Has no toilet\nHandwashing = Has no handwashing',
        event_date: '2019-10-02T09:10:25.491000',
        intervention: ' NULL',
        breastfeeding: ' NULL',
        client_type: 'ec_woman',
        gender: 'F',
        child_no: ' NULL',
        first_name: 'priscilla',
        second_name: ' NULL',
        third_name: ' NULL',
        last_name: ' NULL',
        date_of_birth: 0,
        year_of_birth: 1983,
        patient_contact: ' NULL',
        location_id: 'bb37165f-2ee9-4cad-a3b5-020c0cc75ccf',
        contact: '0',
        anc_visit_date: 0,
        next_anc_date: 0,
        event_id: '1570007425669',
        symptoms: ' NULL',
        status: ' NULL',
        location: 'NHA',
        supplements: ' NULL',
        micronutrients: ' NULL',
        health_insurance_id: ' NULL',
        appointment_status: 'On Time',
        muac_status: ' NULL',
        response_status: ' NULL',
        risk_level: 'high',
        bmi: 0,
        muac: 0,
        lmp: 0,
        bp: ' NULL',
        mother_symptoms: ' NULL',
        ethnicity: 'TAY',
        household: 'HNG',
        toilet: 'Has no toilet',
        handwashing: 'Has no handwashing',
        planned_delivery_location: 'At home',
        death_date: 0,
        location_of_death: ' NULL',
        death_code: ' NULL',
        logface_risk: 'high',
        death_reason: ' NULL',
        child_symptoms: ' NULL',
        delivery_location: ' NULL',
        delivery_method: ' NULL',
        child_risk_level: ' NULL',
        health_worker_contact: 'telegram:782996367',
        team: ' NULL',
    },
    {
        EventDate: '2019-10-02',
        sms_type: 'ANC Visit',
        anc_id: '100P7P',
        age: '36y 9m',
        health_worker_location_name: 'Yen Phu Village',
        health_worker_name: 'Husna Hariz',
        height: 0,
        weight: 80,
        previous_risks: ' NULL',
        lmp_edd: 0,
        parity: 0,
        gravidity: 0,
        message:
            'Blood Pressure = 118-78\nWeight = 80\nCurrent Symptoms = No symptoms\nSupplements = Takes Supplements\nRisk = high\nContact = 1',
        event_date: '2019-10-02T09:11:43.364000',
        intervention: ' NULL',
        breastfeeding: ' NULL',
        client_type: 'ec_woman',
        gender: 'F',
        child_no: ' NULL',
        first_name: 'priscilla',
        second_name: ' NULL',
        third_name: ' NULL',
        last_name: ' NULL',
        date_of_birth: 0,
        year_of_birth: 1983,
        patient_contact: ' NULL',
        location_id: 'bb37165f-2ee9-4cad-a3b5-020c0cc75ccf',
        contact: '1',
        anc_visit_date: '2019-09-02',
        next_anc_date: '2019-10-02',
        event_id: '1570007503539',
        symptoms: 'BT',
        status: ' NULL',
        location: 'NHA',
        supplements: 'Takes Supplements',
        micronutrients: ' NULL',
        health_insurance_id: ' NULL',
        appointment_status: 'On Time',
        muac_status: ' NULL',
        response_status: ' NULL',
        risk_level: 'high',
        bmi: 0,
        muac: 0,
        lmp: 0,
        bp: '118-78',
        mother_symptoms: 'No symptoms',
        ethnicity: ' NULL',
        household: ' NULL',
        toilet: ' NULL',
        handwashing: ' NULL',
        planned_delivery_location: ' NULL',
        death_date: 0,
        location_of_death: ' NULL',
        death_code: ' NULL',
        logface_risk: 'high',
        death_reason: ' NULL',
        child_symptoms: ' NULL',
        delivery_location: ' NULL',
        delivery_method: ' NULL',
        child_risk_level: ' NULL',
        health_worker_contact: 'telegram:782996367',
        team: ' NULL',
    },
    {
        EventDate: '2019-10-02',
        sms_type: 'Home ANC Visit',
        anc_id: '100P7P',
        age: '36y 9m',
        health_worker_location_name: 'Yen Phu Village',
        health_worker_name: 'Husna Hariz',
        height: 0,
        weight: 80,
        previous_risks: ' NULL',
        lmp_edd: 0,
        parity: 0,
        gravidity: 0,
        message:
            'Blood Pressure = 118-78 \nWeight = 80 \nCurrent Symptoms = No symptoms \nSupplements = Takes Supplements \nRisk = No Risk \nContact = 2',
        event_date: '2019-10-02T09:12:21.550000',
        intervention: ' NULL',
        breastfeeding: ' NULL',
        client_type: 'ec_woman',
        gender: 'F',
        child_no: ' NULL',
        first_name: 'priscilla',
        second_name: ' NULL',
        third_name: ' NULL',
        last_name: ' NULL',
        date_of_birth: 0,
        year_of_birth: 1983,
        patient_contact: ' NULL',
        location_id: 'bb37165f-2ee9-4cad-a3b5-020c0cc75ccf',
        contact: '2',
        anc_visit_date: '0008-04-10',
        next_anc_date: '2019-10-02',
        event_id: '1570007541592',
        symptoms: 'BT',
        status: ' NULL',
        location: ' NULL',
        supplements: 'Takes Supplements',
        micronutrients: ' NULL',
        health_insurance_id: ' NULL',
        appointment_status: 'On Time',
        muac_status: ' NULL',
        response_status: ' NULL',
        risk_level: 'No Risk',
        bmi: 0,
        muac: 0,
        lmp: 0,
        bp: '118-78',
        mother_symptoms: 'No symptoms',
        ethnicity: ' NULL',
        household: ' NULL',
        toilet: ' NULL',
        handwashing: ' NULL',
        planned_delivery_location: ' NULL',
        death_date: 0,
        location_of_death: ' NULL',
        death_code: ' NULL',
        logface_risk: ' NULL',
        death_reason: ' NULL',
        child_symptoms: ' NULL',
        delivery_location: ' NULL',
        delivery_method: ' NULL',
        child_risk_level: ' NULL',
        health_worker_contact: 'telegram:782996367',
        team: ' NULL',
    },
    {
        EventDate: '2019-10-02',
        sms_type: 'Delivery Planning',
        anc_id: '100P7P',
        age: '36y 9m',
        health_worker_location_name: 'Yen Phu Village',
        health_worker_name: 'Husna Hariz',
        height: 0,
        weight: 0,
        previous_risks: ' NULL',
        lmp_edd: 0,
        parity: 0,
        gravidity: 0,
        message: 'Planned Delivery Location = At home \nCurrent Symptoms = No symptoms',
        event_date: '2019-10-02T09:13:02.982000',
        intervention: ' NULL',
        breastfeeding: ' NULL',
        client_type: 'ec_woman',
        gender: 'F',
        child_no: ' NULL',
        first_name: 'priscilla',
        second_name: ' NULL',
        third_name: ' NULL',
        last_name: ' NULL',
        date_of_birth: 0,
        year_of_birth: 1983,
        patient_contact: ' NULL',
        location_id: 'bb37165f-2ee9-4cad-a3b5-020c0cc75ccf',
        contact: '1',
        anc_visit_date: 0,
        next_anc_date: '2019-10-02',
        event_id: '1570007583007',
        symptoms: 'BT',
        status: ' NULL',
        location: 'NHA',
        supplements: ' NULL',
        micronutrients: ' NULL',
        health_insurance_id: ' NULL',
        appointment_status: 'On Time',
        muac_status: ' NULL',
        response_status: ' NULL',
        risk_level: 'no_risk',
        bmi: 0,
        muac: 0,
        lmp: 0,
        bp: ' NULL',
        mother_symptoms: 'No symptoms',
        ethnicity: ' NULL',
        household: ' NULL',
        toilet: ' NULL',
        handwashing: ' NULL',
        planned_delivery_location: 'At home',
        death_date: 0,
        location_of_death: ' NULL',
        death_code: ' NULL',
        logface_risk: 'no risk',
        death_reason: ' NULL',
        child_symptoms: ' NULL',
        delivery_location: ' NULL',
        delivery_method: ' NULL',
        child_risk_level: ' NULL',
        health_worker_contact: 'telegram:782996367',
        team: ' NULL',
    },
    {
        EventDate: '2019-10-02',
        sms_type: 'ANC Visit',
        anc_id: '100P7P',
        age: '36y 9m',
        health_worker_location_name: 'Yen Phu Village',
        health_worker_name: 'Husna Hariz',
        height: 0,
        weight: 80,
        previous_risks: ' NULL',
        lmp_edd: 0,
        parity: 0,
        gravidity: 0,
        message:
            'Blood Pressure = 118-78\nWeight = 80\nCurrent Symptoms = No symptoms\nSupplements = Takes Supplements\nRisk = high\nContact = 2',
        event_date: '2019-10-02T09:13:24.755000',
        intervention: ' NULL',
        breastfeeding: ' NULL',
        client_type: 'ec_woman',
        gender: 'F',
        child_no: ' NULL',
        first_name: 'priscilla',
        second_name: ' NULL',
        third_name: ' NULL',
        last_name: ' NULL',
        date_of_birth: 0,
        year_of_birth: 1983,
        patient_contact: ' NULL',
        location_id: 'bb37165f-2ee9-4cad-a3b5-020c0cc75ccf',
        contact: '2',
        anc_visit_date: '2019-10-02',
        next_anc_date: '2019-12-02',
        event_id: '1570007604781',
        symptoms: 'BT',
        status: ' NULL',
        location: 'NHA',
        supplements: 'Takes Supplements',
        micronutrients: ' NULL',
        health_insurance_id: ' NULL',
        appointment_status: 'On Time',
        muac_status: ' NULL',
        response_status: ' NULL',
        risk_level: 'high',
        bmi: 0,
        muac: 0,
        lmp: 0,
        bp: '118-78',
        mother_symptoms: 'No symptoms',
        ethnicity: ' NULL',
        household: ' NULL',
        toilet: ' NULL',
        handwashing: ' NULL',
        planned_delivery_location: ' NULL',
        death_date: 0,
        location_of_death: ' NULL',
        death_code: ' NULL',
        logface_risk: 'high',
        death_reason: ' NULL',
        child_symptoms: ' NULL',
        delivery_location: ' NULL',
        delivery_method: ' NULL',
        child_risk_level: ' NULL',
        health_worker_contact: 'telegram:782996367',
        team: ' NULL',
    },
    {
        EventDate: '2019-10-02',
        sms_type: 'ANC Visit',
        anc_id: '100P7P',
        age: '36y 9m',
        health_worker_location_name: 'Yen Phu Village',
        health_worker_name: 'Husna Hariz',
        height: 0,
        weight: 80,
        previous_risks: ' NULL',
        lmp_edd: 0,
        parity: 0,
        gravidity: 0,
        message:
            'Blood Pressure = 118-78\nWeight = 80\nCurrent Symptoms = No symptoms\nSupplements = Takes Supplements\nRisk = high\nContact = 3',
        event_date: '2019-10-02T09:14:00.942000',
        intervention: ' NULL',
        breastfeeding: ' NULL',
        client_type: 'ec_woman',
        gender: 'F',
        child_no: ' NULL',
        first_name: 'priscilla',
        second_name: ' NULL',
        third_name: ' NULL',
        last_name: ' NULL',
        date_of_birth: 0,
        year_of_birth: 1983,
        patient_contact: ' NULL',
        location_id: 'bb37165f-2ee9-4cad-a3b5-020c0cc75ccf',
        contact: '3',
        anc_visit_date: '2019-12-02',
        next_anc_date: '2020-01-02',
        event_id: '1570007640966',
        symptoms: 'BT',
        status: ' NULL',
        location: 'NHA',
        supplements: 'Takes Supplements',
        micronutrients: ' NULL',
        health_insurance_id: ' NULL',
        appointment_status: 'On Time',
        muac_status: ' NULL',
        response_status: ' NULL',
        risk_level: 'high',
        bmi: 0,
        muac: 0,
        lmp: 0,
        bp: '118-78',
        mother_symptoms: 'No symptoms',
        ethnicity: ' NULL',
        household: ' NULL',
        toilet: ' NULL',
        handwashing: ' NULL',
        planned_delivery_location: ' NULL',
        death_date: 0,
        location_of_death: ' NULL',
        death_code: ' NULL',
        logface_risk: 'high',
        death_reason: ' NULL',
        child_symptoms: ' NULL',
        delivery_location: ' NULL',
        delivery_method: ' NULL',
        child_risk_level: ' NULL',
        health_worker_contact: 'telegram:782996367',
        team: ' NULL',
    },
    {
        EventDate: '2019-10-02',
        sms_type: 'Birth Report',
        anc_id: '100P7P',
        age: '0y -4m',
        health_worker_location_name: 'Yen Phu Village',
        health_worker_name: 'Husna Hariz',
        height: 48,
        weight: 2,
        previous_risks: ' NULL',
        lmp_edd: 0,
        parity: 0,
        gravidity: 0,
        message:
            'Child DOB = 20-02-2020 \nChild Gender = NU \nDelivery Location = At home \nNewborn Symptoms = No symptoms, Hemorrhage/persistent bleeding \nChild Weight = 2.2 \nChild Length = 48 \nChild Risk = red_alert \nBreastfeeding = Breastfeeding during 1st hour\nMother Symptoms = No symptoms, Hemorrhage/persistent bleeding',
        event_date: '2019-10-02T09:15:54.572000',
        intervention: ' NULL',
        breastfeeding: 'Breastfeeding during 1st hour',
        client_type: 'ec_woman',
        gender: 'NU',
        child_no: '100P7P-20200220-01',
        first_name: 'priscilla',
        second_name: ' NULL',
        third_name: ' NULL',
        last_name: ' NULL',
        date_of_birth: 0,
        year_of_birth: 2020,
        patient_contact: ' NULL',
        location_id: 'bb37165f-2ee9-4cad-a3b5-020c0cc75ccf',
        contact: '3',
        anc_visit_date: 0,
        next_anc_date: 0,
        event_id: '1570007755140',
        symptoms: 'BT XH',
        status: ' NULL',
        location: 'NHA',
        supplements: ' NULL',
        micronutrients: ' NULL',
        health_insurance_id: ' NULL',
        appointment_status: 'On Time',
        muac_status: ' NULL',
        response_status: ' NULL',
        risk_level: 'red_alert',
        bmi: 0,
        muac: 0,
        lmp: 0,
        bp: ' NULL',
        mother_symptoms: 'No symptoms, Hemorrhage/persistent bleeding',
        ethnicity: ' NULL',
        household: ' NULL',
        toilet: ' NULL',
        handwashing: ' NULL',
        planned_delivery_location: ' NULL',
        death_date: 0,
        location_of_death: ' NULL',
        death_code: ' NULL',
        logface_risk: 'red',
        death_reason: ' NULL',
        child_symptoms: 'No symptoms, Hemorrhage/persistent bleeding',
        delivery_location: 'At home',
        delivery_method: 'C-Section',
        child_risk_level: 'red_alert',
        health_worker_contact: 'telegram:782996367',
        team: ' NULL',
    },
    {
        EventDate: '2019-10-02',
        sms_type: 'Birth Report',
        anc_id: '100P7P',
        age: '-2m',
        health_worker_location_name: 'Yen Phu Village',
        health_worker_name: 'Husna Hariz',
        height: 48,
        weight: 2,
        previous_risks: ' NULL',
        lmp_edd: 0,
        parity: 0,
        gravidity: 0,
        message:
            'Child DOB = 20-12-2019 \nChild Gender = NU \nDelivery Location = At home \nNewborn Symptoms = No symptoms, Hemorrhage/persistent bleeding \nChild Weight = 2.2 \nChild Length = 48 \nChild Risk = red_alert \nBreastfeeding = Breastfeeding during 1st hour\nMother Symptoms = No symptoms, Hemorrhage/persistent bleeding',
        event_date: '2019-10-02T09:22:02.800000',
        intervention: ' NULL',
        breastfeeding: 'Breastfeeding during 1st hour',
        client_type: 'ec_woman',
        gender: 'NU',
        child_no: '100P7P-20191220-02',
        first_name: 'priscilla',
        second_name: ' NULL',
        third_name: ' NULL',
        last_name: ' NULL',
        date_of_birth: 0,
        year_of_birth: 2019,
        patient_contact: ' NULL',
        location_id: 'bb37165f-2ee9-4cad-a3b5-020c0cc75ccf',
        contact: '3',
        anc_visit_date: 0,
        next_anc_date: 0,
        event_id: '1570008122958',
        symptoms: 'BT XH',
        status: ' NULL',
        location: 'NHA',
        supplements: ' NULL',
        micronutrients: ' NULL',
        health_insurance_id: ' NULL',
        appointment_status: 'On Time',
        muac_status: ' NULL',
        response_status: ' NULL',
        risk_level: 'red_alert',
        bmi: 0,
        muac: 0,
        lmp: 0,
        bp: ' NULL',
        mother_symptoms: 'No symptoms, Hemorrhage/persistent bleeding',
        ethnicity: ' NULL',
        household: ' NULL',
        toilet: ' NULL',
        handwashing: ' NULL',
        planned_delivery_location: ' NULL',
        death_date: 0,
        location_of_death: ' NULL',
        death_code: ' NULL',
        logface_risk: 'red',
        death_reason: ' NULL',
        child_symptoms: 'No symptoms, Hemorrhage/persistent bleeding',
        delivery_location: 'At home',
        delivery_method: 'C-Section',
        child_risk_level: 'red_alert',
        health_worker_contact: 'telegram:782996367',
        team: ' NULL',
    },
    {
        EventDate: '2019-10-02',
        sms_type: 'Birth Report',
        anc_id: '100P7P',
        age: '-2m',
        health_worker_location_name: 'Yen Phu Village',
        health_worker_name: 'Husna Hariz',
        height: 48,
        weight: 2,
        previous_risks: ' NULL',
        lmp_edd: 0,
        parity: 0,
        gravidity: 0,
        message:
            'Child DOB = 20-12-2020 \nChild Gender = NU \nDelivery Location = At home \nNewborn Symptoms = No symptoms, Hemorrhage/persistent bleeding \nChild Weight = 2.2 \nChild Length = 48 \nChild Risk = red_alert \nBreastfeeding = Breastfeeding during 1st hour\nMother Symptoms = No symptoms, Hemorrhage/persistent bleeding',
        event_date: '2019-10-02T09:23:47.788000',
        intervention: ' NULL',
        breastfeeding: 'Breastfeeding during 1st hour',
        client_type: 'ec_woman',
        gender: 'NU',
        child_no: '100P7P-20201220-02',
        first_name: 'priscilla',
        second_name: ' NULL',
        third_name: ' NULL',
        last_name: ' NULL',
        date_of_birth: 0,
        year_of_birth: 2020,
        patient_contact: ' NULL',
        location_id: 'bb37165f-2ee9-4cad-a3b5-020c0cc75ccf',
        contact: '3',
        anc_visit_date: 0,
        next_anc_date: 0,
        event_id: '1570008227951',
        symptoms: 'BT XH',
        status: ' NULL',
        location: 'NHA',
        supplements: ' NULL',
        micronutrients: ' NULL',
        health_insurance_id: ' NULL',
        appointment_status: 'On Time',
        muac_status: ' NULL',
        response_status: ' NULL',
        risk_level: 'red_alert',
        bmi: 0,
        muac: 0,
        lmp: 0,
        bp: ' NULL',
        mother_symptoms: 'No symptoms, Hemorrhage/persistent bleeding',
        ethnicity: ' NULL',
        household: ' NULL',
        toilet: ' NULL',
        handwashing: ' NULL',
        planned_delivery_location: ' NULL',
        death_date: 0,
        location_of_death: ' NULL',
        death_code: ' NULL',
        logface_risk: 'red',
        death_reason: ' NULL',
        child_symptoms: 'No symptoms, Hemorrhage/persistent bleeding',
        delivery_location: 'At home',
        delivery_method: 'C-Section',
        child_risk_level: 'red_alert',
        health_worker_contact: 'telegram:782996367',
        team: ' NULL',
    },
    {
        EventDate: '2019-10-02',
        sms_type: 'Nutrition Registration',
        anc_id: '100P7P-20201220-02',
        age: '-2m',
        health_worker_location_name: 'Yen Phu Village',
        health_worker_name: 'Husna Hariz',
        height: 48,
        weight: 2,
        previous_risks: ' NULL',
        lmp_edd: 0,
        parity: 0,
        gravidity: 0,
        message:
            'Name = Nancy Jane   \nPhone Number = +84995679786 \nHealth Insurance = 42015228988 \nMUAC = 8 \nWeight = 2.2 \nHeight = 48',
        event_date: '2019-10-02T09:25:52.113000',
        intervention: ' NULL',
        breastfeeding: ' NULL',
        client_type: 'ec_child',
        gender: 'NU',
        child_no: ' NULL',
        first_name: 'Nancy',
        second_name: 'Jane',
        third_name: ' NULL',
        last_name: ' NULL',
        date_of_birth: 0,
        year_of_birth: 2020,
        patient_contact: '+84995679786',
        location_id: 'bb37165f-2ee9-4cad-a3b5-020c0cc75ccf',
        contact: ' NULL',
        anc_visit_date: 0,
        next_anc_date: 0,
        event_id: '1570008352289',
        symptoms: ' NULL',
        status: ' NULL',
        location: ' NULL',
        supplements: ' NULL',
        micronutrients: ' NULL',
        health_insurance_id: ' NULL',
        appointment_status: 'On Time',
        muac_status: ' NULL',
        response_status: ' NULL',
        risk_level: ' NULL',
        bmi: 0,
        muac: 8,
        lmp: 0,
        bp: ' NULL',
        mother_symptoms: ' NULL',
        ethnicity: ' NULL',
        household: ' NULL',
        toilet: ' NULL',
        handwashing: ' NULL',
        planned_delivery_location: ' NULL',
        death_date: 0,
        location_of_death: ' NULL',
        death_code: ' NULL',
        logface_risk: 'Not Set',
        death_reason: ' NULL',
        child_symptoms: ' NULL',
        delivery_location: ' NULL',
        delivery_method: ' NULL',
        child_risk_level: ' NULL',
        health_worker_contact: 'telegram:782996367',
        team: ' NULL',
    },
    {
        EventDate: '2019-10-02',
        sms_type: 'Nutrition Registration',
        anc_id: '100P7P-20200220-01',
        age: '-4m',
        health_worker_location_name: 'Yen Phu Village',
        health_worker_name: 'Husna Hariz',
        height: 48,
        weight: 2,
        previous_risks: ' NULL',
        lmp_edd: 0,
        parity: 0,
        gravidity: 0,
        message:
            'Name = Lin Min   \nPhone Number = +84995679786 \nHealth Insurance = 42015228922 \nMUAC = 8 \nWeight = 2.2 \nHeight = 48',
        event_date: '2019-10-02T09:28:26.634000',
        intervention: ' NULL',
        breastfeeding: ' NULL',
        client_type: 'ec_child',
        gender: 'NU',
        child_no: ' NULL',
        first_name: 'Lin',
        second_name: 'Min',
        third_name: ' NULL',
        last_name: ' NULL',
        date_of_birth: 0,
        year_of_birth: 2020,
        patient_contact: '+84995679786',
        location_id: 'bb37165f-2ee9-4cad-a3b5-020c0cc75ccf',
        contact: ' NULL',
        anc_visit_date: 0,
        next_anc_date: 0,
        event_id: '1570008506847',
        symptoms: ' NULL',
        status: ' NULL',
        location: ' NULL',
        supplements: ' NULL',
        micronutrients: ' NULL',
        health_insurance_id: ' NULL',
        appointment_status: 'On Time',
        muac_status: ' NULL',
        response_status: ' NULL',
        risk_level: ' NULL',
        bmi: 0,
        muac: 8,
        lmp: 0,
        bp: ' NULL',
        mother_symptoms: ' NULL',
        ethnicity: ' NULL',
        household: ' NULL',
        toilet: ' NULL',
        handwashing: ' NULL',
        planned_delivery_location: ' NULL',
        death_date: 0,
        location_of_death: ' NULL',
        death_code: ' NULL',
        logface_risk: 'Not Set',
        death_reason: ' NULL',
        child_symptoms: ' NULL',
        delivery_location: ' NULL',
        delivery_method: ' NULL',
        child_risk_level: ' NULL',
        health_worker_contact: 'telegram:782996367',
        team: ' NULL',
    },
    {
        EventDate: '2019-10-02',
        sms_type: 'Red Alert Report',
        anc_id: '100P7P',
        age: '36y 9m',
        health_worker_location_name: 'Yen Phu Village',
        health_worker_name: 'Husna Hariz',
        height: 0,
        weight: 0,
        previous_risks: ' NULL',
        lmp_edd: 0,
        parity: 0,
        gravidity: 0,
        message: 'Symptoms = Dark vaginal blood \nLocation = At home \nInterventions = ',
        event_date: '2019-10-02T12:02:01.097000',
        intervention: ' NULL',
        breastfeeding: ' NULL',
        client_type: 'ec_woman',
        gender: 'F',
        child_no: ' NULL',
        first_name: 'priscilla',
        second_name: ' NULL',
        third_name: ' NULL',
        last_name: ' NULL',
        date_of_birth: 0,
        year_of_birth: 1983,
        patient_contact: ' NULL',
        location_id: 'bb37165f-2ee9-4cad-a3b5-020c0cc75ccf',
        contact: ' NULL',
        anc_visit_date: 0,
        next_anc_date: 0,
        event_id: '1570017721361',
        symptoms: 'MD',
        status: ' NULL',
        location: 'At home',
        supplements: ' NULL',
        micronutrients: ' NULL',
        health_insurance_id: ' NULL',
        appointment_status: 'On Time',
        muac_status: ' NULL',
        response_status: ' NULL',
        risk_level: 'no_risk',
        bmi: 0,
        muac: 0,
        lmp: 0,
        bp: ' NULL',
        mother_symptoms: 'Dark vaginal blood',
        ethnicity: ' NULL',
        household: ' NULL',
        toilet: ' NULL',
        handwashing: ' NULL',
        planned_delivery_location: ' NULL',
        death_date: 0,
        location_of_death: ' NULL',
        death_code: ' NULL',
        logface_risk: 'no risk',
        death_reason: ' NULL',
        child_symptoms: ' NULL',
        delivery_location: ' NULL',
        delivery_method: ' NULL',
        child_risk_level: ' NULL',
        health_worker_contact: 'telegram:782996367',
        team: ' NULL',
    },
    {
        EventDate: '2019-10-02',
        sms_type: 'Red Alert Report',
        anc_id: '100P7P-20201220-02',
        age: '-2m',
        health_worker_location_name: 'Yen Phu Village',
        health_worker_name: 'Husna Hariz',
        height: 0,
        weight: 0,
        previous_risks: ' NULL',
        lmp_edd: 0,
        parity: 0,
        gravidity: 0,
        message: 'Symptoms = Dark vaginal blood \nLocation = At home \nInterventions = ',
        event_date: '2019-10-02T12:22:19.201000',
        intervention: ' NULL',
        breastfeeding: ' NULL',
        client_type: 'ec_child',
        gender: 'NU',
        child_no: ' NULL',
        first_name: 'Nancy',
        second_name: ' NULL',
        third_name: ' NULL',
        last_name: ' NULL',
        date_of_birth: 0,
        year_of_birth: 2020,
        patient_contact: ' NULL',
        location_id: 'bb37165f-2ee9-4cad-a3b5-020c0cc75ccf',
        contact: ' NULL',
        anc_visit_date: 0,
        next_anc_date: 0,
        event_id: '1570018939484',
        symptoms: 'MD',
        status: ' NULL',
        location: 'At home',
        supplements: ' NULL',
        micronutrients: ' NULL',
        health_insurance_id: ' NULL',
        appointment_status: 'On Time',
        muac_status: ' NULL',
        response_status: ' NULL',
        risk_level: 'no_risk',
        bmi: 0,
        muac: 0,
        lmp: 0,
        bp: ' NULL',
        mother_symptoms: ' NULL',
        ethnicity: ' NULL',
        household: ' NULL',
        toilet: ' NULL',
        handwashing: ' NULL',
        planned_delivery_location: ' NULL',
        death_date: 0,
        location_of_death: ' NULL',
        death_code: ' NULL',
        logface_risk: 'no risk',
        death_reason: ' NULL',
        child_symptoms: 'Dark vaginal blood',
        delivery_location: ' NULL',
        delivery_method: ' NULL',
        child_risk_level: ' NULL',
        health_worker_contact: 'telegram:782996367',
        team: ' NULL',
    },
    {
        EventDate: '2019-10-02',
        sms_type: 'Red Alert Report',
        anc_id: '100P7P--06',
        age: '36y 9m',
        health_worker_location_name: 'Yen Phu Village',
        health_worker_name: 'Husna Hariz',
        height: 0,
        weight: 0,
        previous_risks: ' NULL',
        lmp_edd: 0,
        parity: 0,
        gravidity: 0,
        message: 'Symptoms = Dark vaginal blood, Fever \nLocation = At home \nInterventions = ',
        event_date: '2019-10-02T13:14:19.402000',
        intervention: ' NULL',
        breastfeeding: ' NULL',
        client_type: 'ec_woman',
        gender: 'F',
        child_no: '06',
        first_name: 'priscilla',
        second_name: ' NULL',
        third_name: ' NULL',
        last_name: ' NULL',
        date_of_birth: 0,
        year_of_birth: 1983,
        patient_contact: ' NULL',
        location_id: 'bb37165f-2ee9-4cad-a3b5-020c0cc75ccf',
        contact: ' NULL',
        anc_visit_date: 0,
        next_anc_date: 0,
        event_id: '1570022059787',
        symptoms: 'MD SOT',
        status: ' NULL',
        location: 'At home',
        supplements: ' NULL',
        micronutrients: ' NULL',
        health_insurance_id: ' NULL',
        appointment_status: 'On Time',
        muac_status: ' NULL',
        response_status: ' NULL',
        risk_level: 'high',
        bmi: 0,
        muac: 0,
        lmp: 0,
        bp: ' NULL',
        mother_symptoms: 'Dark vaginal blood, Fever',
        ethnicity: ' NULL',
        household: ' NULL',
        toilet: ' NULL',
        handwashing: ' NULL',
        planned_delivery_location: ' NULL',
        death_date: 0,
        location_of_death: ' NULL',
        death_code: ' NULL',
        logface_risk: 'high',
        death_reason: ' NULL',
        child_symptoms: ' NULL',
        delivery_location: ' NULL',
        delivery_method: ' NULL',
        child_risk_level: ' NULL',
        health_worker_contact: 'telegram:782996367',
        team: ' NULL',
    },
    {
        EventDate: '2019-10-02',
        sms_type: 'Birth Report',
        anc_id: '100P7P',
        age: '36y 9m',
        health_worker_location_name: 'Yen Phu Village',
        health_worker_name: 'Husna Hariz',
        height: 48,
        weight: 2,
        previous_risks: ' NULL',
        lmp_edd: 0,
        parity: 0,
        gravidity: 0,
        message:
            'Child DOB = 20-12-2020 \nChild Gender = NU \nDelivery Location = At home \nNewborn Symptoms = No symptoms, Hemorrhage/persistent bleeding \nChild Weight = 2.2 \nChild Length = 48 \nChild Risk = red_alert \nBreastfeeding = Breastfeeding during 1st hour\nMother Symptoms = No symptoms, Hemorrhage/persistent bleeding',
        event_date: '2019-10-02T14:04:44.001000',
        intervention: ' NULL',
        breastfeeding: 'Breastfeeding during 1st hour',
        client_type: 'ec_woman',
        gender: 'NU',
        child_no: '100P7P-20201220-09',
        first_name: 'priscilla',
        second_name: ' NULL',
        third_name: ' NULL',
        last_name: ' NULL',
        date_of_birth: 0,
        year_of_birth: 2020,
        patient_contact: ' NULL',
        location_id: 'bb37165f-2ee9-4cad-a3b5-020c0cc75ccf',
        contact: '3',
        anc_visit_date: 0,
        next_anc_date: 0,
        event_id: '1570025092736',
        symptoms: 'BT XH',
        status: ' NULL',
        location: 'NHA',
        supplements: ' NULL',
        micronutrients: ' NULL',
        health_insurance_id: ' NULL',
        appointment_status: 'On Time',
        muac_status: ' NULL',
        response_status: ' NULL',
        risk_level: 'red_alert',
        bmi: 0,
        muac: 0,
        lmp: 0,
        bp: ' NULL',
        mother_symptoms: 'No symptoms, Hemorrhage/persistent bleeding',
        ethnicity: ' NULL',
        household: ' NULL',
        toilet: ' NULL',
        handwashing: ' NULL',
        planned_delivery_location: ' NULL',
        death_date: 0,
        location_of_death: ' NULL',
        death_code: ' NULL',
        logface_risk: 'red',
        death_reason: ' NULL',
        child_symptoms: 'No symptoms, Hemorrhage/persistent bleeding',
        delivery_location: 'At home',
        delivery_method: 'C-Section',
        child_risk_level: 'red_alert',
        health_worker_contact: 'telegram:782996367',
        team: ' NULL',
    },
    {
        EventDate: '2019-10-03',
        sms_type: 'Birth Report',
        anc_id: '100P7P',
        age: '36y 9m',
        health_worker_location_name: 'Yen Phu Village',
        health_worker_name: 'Husna Hariz',
        height: 48,
        weight: 2,
        previous_risks: ' NULL',
        lmp_edd: 0,
        parity: 0,
        gravidity: 0,
        message:
            'Child DOB = 20-12-2020 \nChild Gender = NU \nDelivery Location = At home \nNewborn Symptoms = No symptoms, Hemorrhage/persistent bleeding \nChild Weight = 2.2 \nChild Length = 48 \nChild Risk = red_alert \nBreastfeeding = Breastfeeding during 1st hour\nMother Symptoms = No symptoms, Hemorrhage/persistent bleeding',
        event_date: '2019-10-03T06:49:33.065000',
        intervention: ' NULL',
        breastfeeding: 'Breastfeeding during 1st hour',
        client_type: 'ec_woman',
        gender: 'NU',
        child_no: '100P7P-20201220-13',
        first_name: 'priscilla',
        second_name: ' NULL',
        third_name: ' NULL',
        last_name: ' NULL',
        date_of_birth: 0,
        year_of_birth: 2020,
        patient_contact: ' NULL',
        location_id: 'bb37165f-2ee9-4cad-a3b5-020c0cc75ccf',
        contact: '3',
        anc_visit_date: 0,
        next_anc_date: 0,
        event_id: '1570085373297',
        symptoms: 'BT XH',
        status: ' NULL',
        location: 'NHA',
        supplements: ' NULL',
        micronutrients: ' NULL',
        health_insurance_id: ' NULL',
        appointment_status: 'On Time',
        muac_status: ' NULL',
        response_status: ' NULL',
        risk_level: 'red_alert',
        bmi: 0,
        muac: 0,
        lmp: 0,
        bp: ' NULL',
        mother_symptoms: 'No symptoms, Hemorrhage/persistent bleeding',
        ethnicity: ' NULL',
        household: ' NULL',
        toilet: ' NULL',
        handwashing: ' NULL',
        planned_delivery_location: ' NULL',
        death_date: 0,
        location_of_death: ' NULL',
        death_code: ' NULL',
        logface_risk: 'red',
        death_reason: ' NULL',
        child_symptoms: 'No symptoms, Hemorrhage/persistent bleeding',
        delivery_location: 'At home',
        delivery_method: 'C-Section',
        child_risk_level: 'red_alert',
        health_worker_contact: 'telegram:782996367',
        team: ' NULL',
    },
    {
        EventDate: '2019-10-03',
        sms_type: 'Birth Report',
        anc_id: '100P7P',
        age: '36y 9m',
        health_worker_location_name: 'Yen Phu Village',
        health_worker_name: 'Husna Hariz',
        height: 48,
        weight: 2.2,
        previous_risks: ' NULL',
        lmp_edd: 0,
        parity: 0,
        gravidity: 0,
        message:
            'Child DOB = 20-12-2020 \nChild Gender = NU \nDelivery Location = At home \nNewborn Symptoms = No symptoms, Hemorrhage/persistent bleeding \nChild Weight = 2.2 \nChild Length = 48 \nChild Risk = red_alert \nBreastfeeding = Breastfeeding during 1st hour\nMother Symptoms = No symptoms, Hemorrhage/persistent bleeding',
        event_date: '2019-10-03T07:07:38.111000',
        intervention: ' NULL',
        breastfeeding: 'Breastfeeding during 1st hour',
        client_type: 'ec_woman',
        gender: 'NU',
        child_no: '100P7P-20201220-13',
        first_name: 'priscilla',
        second_name: ' NULL',
        third_name: ' NULL',
        last_name: ' NULL',
        date_of_birth: 0,
        year_of_birth: 2020,
        patient_contact: ' NULL',
        location_id: 'bb37165f-2ee9-4cad-a3b5-020c0cc75ccf',
        contact: '3',
        anc_visit_date: 0,
        next_anc_date: 0,
        event_id: '1570086458413',
        symptoms: 'BT XH',
        status: ' NULL',
        location: 'NHA',
        supplements: ' NULL',
        micronutrients: ' NULL',
        health_insurance_id: ' NULL',
        appointment_status: 'On Time',
        muac_status: ' NULL',
        response_status: ' NULL',
        risk_level: 'red_alert',
        bmi: 0,
        muac: 0,
        lmp: 0,
        bp: ' NULL',
        mother_symptoms: 'No symptoms, Hemorrhage/persistent bleeding',
        ethnicity: ' NULL',
        household: ' NULL',
        toilet: ' NULL',
        handwashing: ' NULL',
        planned_delivery_location: ' NULL',
        death_date: 0,
        location_of_death: ' NULL',
        death_code: ' NULL',
        logface_risk: 'red',
        death_reason: ' NULL',
        child_symptoms: 'No symptoms, Hemorrhage/persistent bleeding',
        delivery_location: 'At home',
        delivery_method: 'C-Section',
        child_risk_level: 'red_alert',
        health_worker_contact: 'telegram:782996367',
        team: ' NULL',
    },
    {
        EventDate: '2019-10-03',
        sms_type: 'Pregnancy Detection',
        anc_id: '100P9K',
        age: '38y 9m',
        health_worker_location_name: 'Yen Phu Village',
        health_worker_name: 'Husna Hariz',
        height: 0,
        weight: 0,
        previous_risks: ' NULL',
        lmp_edd: 0,
        parity: 0,
        gravidity: 0,
        message: 'Name = Rory Mory Dory \nPhone Number = +84995623786 \nHealth Insurance = 42015990116',
        event_date: '2019-10-03T07:18:05.243000',
        intervention: ' NULL',
        breastfeeding: ' NULL',
        client_type: 'ec_woman',
        gender: 'F',
        child_no: ' NULL',
        first_name: 'Rory',
        second_name: 'Mory',
        third_name: 'Dory',
        last_name: ' NULL',
        date_of_birth: 0,
        year_of_birth: 1981,
        patient_contact: '+84995623786',
        location_id: 'bb37165f-2ee9-4cad-a3b5-020c0cc75ccf',
        contact: ' NULL',
        anc_visit_date: 0,
        next_anc_date: 0,
        event_id: '1570087085524',
        symptoms: ' NULL',
        status: ' NULL',
        location: ' NULL',
        supplements: ' NULL',
        micronutrients: ' NULL',
        health_insurance_id: ' NULL',
        appointment_status: 'On Time',
        muac_status: ' NULL',
        response_status: ' NULL',
        risk_level: ' NULL',
        bmi: 0,
        muac: 0,
        lmp: 0,
        bp: ' NULL',
        mother_symptoms: ' NULL',
        ethnicity: ' NULL',
        household: ' NULL',
        toilet: ' NULL',
        handwashing: ' NULL',
        planned_delivery_location: ' NULL',
        death_date: 0,
        location_of_death: ' NULL',
        death_code: ' NULL',
        logface_risk: 'Not Set',
        death_reason: ' NULL',
        child_symptoms: ' NULL',
        delivery_location: ' NULL',
        delivery_method: ' NULL',
        child_risk_level: ' NULL',
        health_worker_contact: 'telegram:782996367',
        team: ' NULL',
    },
    {
        EventDate: '2019-10-03',
        sms_type: 'Pregnancy Registration',
        anc_id: '100P9K',
        age: '38y 9m',
        health_worker_location_name: 'Yen Phu Village',
        health_worker_name: 'Husna Hariz',
        height: 160,
        weight: 54,
        previous_risks: 'Diabetes, High blood pressure',
        lmp_edd: '2019-11-01',
        parity: 2,
        gravidity: 3,
        message:
            'EDD = 01-11-2019\nGravidity = 3\nParity = 2\nWeight = 54 \nHeight = 160\nBMI = 21\nPrevious Gynaecology History = Diabetes, High blood pressure\nCurrent Symptoms = Flaccid Paralysis',
        event_date: '2019-10-03T07:22:34.774000',
        intervention: ' NULL',
        breastfeeding: ' NULL',
        client_type: 'ec_woman',
        gender: 'F',
        child_no: ' NULL',
        first_name: 'Rory',
        second_name: ' NULL',
        third_name: ' NULL',
        last_name: ' NULL',
        date_of_birth: 0,
        year_of_birth: 1981,
        patient_contact: ' NULL',
        location_id: 'bb37165f-2ee9-4cad-a3b5-020c0cc75ccf',
        contact: '0',
        anc_visit_date: '2019-10-03',
        next_anc_date: '2019-03-22',
        event_id: '1570087354945',
        symptoms: 'LM',
        status: ' NULL',
        location: ' NULL',
        supplements: ' NULL',
        micronutrients: ' NULL',
        health_insurance_id: ' NULL',
        appointment_status: 'On Time',
        muac_status: ' NULL',
        response_status: ' NULL',
        risk_level: 'high',
        bmi: 21,
        muac: 0,
        lmp: '2019-01-25',
        bp: '123-78',
        mother_symptoms: 'Flaccid Paralysis',
        ethnicity: ' NULL',
        household: ' NULL',
        toilet: ' NULL',
        handwashing: ' NULL',
        planned_delivery_location: ' NULL',
        death_date: 0,
        location_of_death: ' NULL',
        death_code: ' NULL',
        logface_risk: 'high',
        death_reason: ' NULL',
        child_symptoms: ' NULL',
        delivery_location: ' NULL',
        delivery_method: ' NULL',
        child_risk_level: ' NULL',
        health_worker_contact: 'telegram:782996367',
        team: ' NULL',
    },
    {
        EventDate: '2019-10-03',
        sms_type: 'ANC Visit',
        anc_id: '100P9K',
        age: '38y 9m',
        health_worker_location_name: 'Yen Phu Village',
        health_worker_name: 'Husna Hariz',
        height: 0,
        weight: 80,
        previous_risks: ' NULL',
        lmp_edd: 0,
        parity: 0,
        gravidity: 0,
        message:
            'Blood Pressure = 129-78\nWeight = 80\nCurrent Symptoms = No symptoms\nSupplements = Takes Supplements\nRisk = No Risk\nContact = 1',
        event_date: '2019-10-03T07:25:24.776000',
        intervention: ' NULL',
        breastfeeding: ' NULL',
        client_type: 'ec_woman',
        gender: 'F',
        child_no: ' NULL',
        first_name: 'Rory',
        second_name: ' NULL',
        third_name: ' NULL',
        last_name: ' NULL',
        date_of_birth: 0,
        year_of_birth: 1981,
        patient_contact: ' NULL',
        location_id: 'bb37165f-2ee9-4cad-a3b5-020c0cc75ccf',
        contact: '1',
        anc_visit_date: '2019-03-02',
        next_anc_date: '2019-05-02',
        event_id: '1570087524929',
        symptoms: 'BT',
        status: ' NULL',
        location: ' NULL',
        supplements: 'Takes Supplements',
        micronutrients: ' NULL',
        health_insurance_id: ' NULL',
        appointment_status: 'On Time',
        muac_status: ' NULL',
        response_status: ' NULL',
        risk_level: 'No Risk',
        bmi: 0,
        muac: 0,
        lmp: 0,
        bp: '129-78',
        mother_symptoms: 'No symptoms',
        ethnicity: ' NULL',
        household: ' NULL',
        toilet: ' NULL',
        handwashing: ' NULL',
        planned_delivery_location: ' NULL',
        death_date: 0,
        location_of_death: ' NULL',
        death_code: ' NULL',
        logface_risk: ' NULL',
        death_reason: ' NULL',
        child_symptoms: ' NULL',
        delivery_location: ' NULL',
        delivery_method: ' NULL',
        child_risk_level: ' NULL',
        health_worker_contact: 'telegram:782996367',
        team: ' NULL',
    },
    {
        EventDate: '2019-10-03',
        sms_type: 'Home ANC Visit',
        anc_id: '100P9K',
        age: '38y 9m',
        health_worker_location_name: 'Yen Phu Village',
        health_worker_name: 'Husna Hariz',
        height: 0,
        weight: 80,
        previous_risks: ' NULL',
        lmp_edd: 0,
        parity: 0,
        gravidity: 0,
        message:
            'Blood Pressure = 118-78 \nWeight = 80 \nCurrent Symptoms = No symptoms \nSupplements = Takes Supplements \nRisk = No Risk \nContact = 2',
        event_date: '2019-10-03T07:26:33.645000',
        intervention: ' NULL',
        breastfeeding: ' NULL',
        client_type: 'ec_woman',
        gender: 'F',
        child_no: ' NULL',
        first_name: 'Rory',
        second_name: ' NULL',
        third_name: ' NULL',
        last_name: ' NULL',
        date_of_birth: 0,
        year_of_birth: 1981,
        patient_contact: ' NULL',
        location_id: 'bb37165f-2ee9-4cad-a3b5-020c0cc75ccf',
        contact: '2',
        anc_visit_date: '0009-04-10',
        next_anc_date: '2019-05-02',
        event_id: '1570087593675',
        symptoms: 'BT',
        status: ' NULL',
        location: ' NULL',
        supplements: 'Takes Supplements',
        micronutrients: ' NULL',
        health_insurance_id: ' NULL',
        appointment_status: 'On Time',
        muac_status: ' NULL',
        response_status: ' NULL',
        risk_level: 'No Risk',
        bmi: 0,
        muac: 0,
        lmp: 0,
        bp: '118-78',
        mother_symptoms: 'No symptoms',
        ethnicity: ' NULL',
        household: ' NULL',
        toilet: ' NULL',
        handwashing: ' NULL',
        planned_delivery_location: ' NULL',
        death_date: 0,
        location_of_death: ' NULL',
        death_code: ' NULL',
        logface_risk: ' NULL',
        death_reason: ' NULL',
        child_symptoms: ' NULL',
        delivery_location: ' NULL',
        delivery_method: ' NULL',
        child_risk_level: ' NULL',
        health_worker_contact: 'telegram:782996367',
        team: ' NULL',
    },
    {
        EventDate: '2019-10-03',
        sms_type: 'Delivery Planning',
        anc_id: '100P9K',
        age: '38y 9m',
        health_worker_location_name: 'Yen Phu Village',
        health_worker_name: 'Husna Hariz',
        height: 0,
        weight: 0,
        previous_risks: ' NULL',
        lmp_edd: 0,
        parity: 0,
        gravidity: 0,
        message: 'Planned Delivery Location = At home \nCurrent Symptoms = No symptoms',
        event_date: '2019-10-03T07:27:18.103000',
        intervention: ' NULL',
        breastfeeding: ' NULL',
        client_type: 'ec_woman',
        gender: 'F',
        child_no: ' NULL',
        first_name: 'Rory',
        second_name: ' NULL',
        third_name: ' NULL',
        last_name: ' NULL',
        date_of_birth: 0,
        year_of_birth: 1981,
        patient_contact: ' NULL',
        location_id: 'bb37165f-2ee9-4cad-a3b5-020c0cc75ccf',
        contact: '1',
        anc_visit_date: 0,
        next_anc_date: '2019-05-02',
        event_id: '1570087638129',
        symptoms: 'BT',
        status: ' NULL',
        location: 'NHA',
        supplements: ' NULL',
        micronutrients: ' NULL',
        health_insurance_id: ' NULL',
        appointment_status: 'On Time',
        muac_status: ' NULL',
        response_status: ' NULL',
        risk_level: 'no_risk',
        bmi: 0,
        muac: 0,
        lmp: 0,
        bp: ' NULL',
        mother_symptoms: 'No symptoms',
        ethnicity: ' NULL',
        household: ' NULL',
        toilet: ' NULL',
        handwashing: ' NULL',
        planned_delivery_location: 'At home',
        death_date: 0,
        location_of_death: ' NULL',
        death_code: ' NULL',
        logface_risk: 'no risk',
        death_reason: ' NULL',
        child_symptoms: ' NULL',
        delivery_location: ' NULL',
        delivery_method: ' NULL',
        child_risk_level: ' NULL',
        health_worker_contact: 'telegram:782996367',
        team: ' NULL',
    },
    {
        EventDate: '2019-10-03',
        sms_type: 'Social Determinants',
        anc_id: '100P9K',
        age: '38y 9m',
        health_worker_location_name: 'Yen Phu Village',
        health_worker_name: 'Husna Hariz',
        height: 0,
        weight: 0,
        previous_risks: ' NULL',
        lmp_edd: 0,
        parity: 0,
        gravidity: 0,
        message:
            'Planned Delivery Location = At home\nHousehold = HNG\nEthnicity = TAY\nToilet = Has no toilet\nHandwashing = Has no handwashing',
        event_date: '2019-10-03T07:29:30.209000',
        intervention: ' NULL',
        breastfeeding: ' NULL',
        client_type: 'ec_woman',
        gender: 'F',
        child_no: ' NULL',
        first_name: 'Rory',
        second_name: ' NULL',
        third_name: ' NULL',
        last_name: ' NULL',
        date_of_birth: 0,
        year_of_birth: 1981,
        patient_contact: ' NULL',
        location_id: 'bb37165f-2ee9-4cad-a3b5-020c0cc75ccf',
        contact: '1',
        anc_visit_date: 0,
        next_anc_date: 0,
        event_id: '1570087770485',
        symptoms: ' NULL',
        status: ' NULL',
        location: 'NHA',
        supplements: ' NULL',
        micronutrients: ' NULL',
        health_insurance_id: ' NULL',
        appointment_status: 'On Time',
        muac_status: ' NULL',
        response_status: ' NULL',
        risk_level: 'no_risk',
        bmi: 0,
        muac: 0,
        lmp: 0,
        bp: ' NULL',
        mother_symptoms: ' NULL',
        ethnicity: 'TAY',
        household: 'HNG',
        toilet: 'Has no toilet',
        handwashing: 'Has no handwashing',
        planned_delivery_location: 'At home',
        death_date: 0,
        location_of_death: ' NULL',
        death_code: ' NULL',
        logface_risk: 'no risk',
        death_reason: ' NULL',
        child_symptoms: ' NULL',
        delivery_location: ' NULL',
        delivery_method: ' NULL',
        child_risk_level: ' NULL',
        health_worker_contact: 'telegram:782996367',
        team: ' NULL',
    },
    {
        EventDate: '2019-10-03',
        sms_type: 'ANC Visit',
        anc_id: '100P9K',
        age: '38y 9m',
        health_worker_location_name: 'Yen Phu Village',
        health_worker_name: 'Husna Hariz',
        height: 0,
        weight: 80,
        previous_risks: ' NULL',
        lmp_edd: 0,
        parity: 0,
        gravidity: 0,
        message:
            'Blood Pressure = 119-68\nWeight = 80\nCurrent Symptoms = No symptoms\nSupplements = Takes Supplements\nRisk = low\nContact = 2',
        event_date: '2019-10-03T07:30:08.636000',
        intervention: ' NULL',
        breastfeeding: ' NULL',
        client_type: 'ec_woman',
        gender: 'F',
        child_no: ' NULL',
        first_name: 'Rory',
        second_name: ' NULL',
        third_name: ' NULL',
        last_name: ' NULL',
        date_of_birth: 0,
        year_of_birth: 1981,
        patient_contact: ' NULL',
        location_id: 'bb37165f-2ee9-4cad-a3b5-020c0cc75ccf',
        contact: '2',
        anc_visit_date: '2019-05-02',
        next_anc_date: '2019-07-02',
        event_id: '1570087808665',
        symptoms: 'BT',
        status: ' NULL',
        location: 'NHA',
        supplements: 'Takes Supplements',
        micronutrients: ' NULL',
        health_insurance_id: ' NULL',
        appointment_status: 'On Time',
        muac_status: ' NULL',
        response_status: ' NULL',
        risk_level: 'low',
        bmi: 0,
        muac: 0,
        lmp: 0,
        bp: '119-68',
        mother_symptoms: 'No symptoms',
        ethnicity: ' NULL',
        household: ' NULL',
        toilet: ' NULL',
        handwashing: ' NULL',
        planned_delivery_location: ' NULL',
        death_date: 0,
        location_of_death: ' NULL',
        death_code: ' NULL',
        logface_risk: 'low',
        death_reason: ' NULL',
        child_symptoms: ' NULL',
        delivery_location: ' NULL',
        delivery_method: ' NULL',
        child_risk_level: ' NULL',
        health_worker_contact: 'telegram:782996367',
        team: ' NULL',
    },
    {
        EventDate: '2019-10-03',
        sms_type: 'ANC Visit',
        anc_id: '100P9K',
        age: '38y 9m',
        health_worker_location_name: 'Yen Phu Village',
        health_worker_name: 'Husna Hariz',
        height: 0,
        weight: 80,
        previous_risks: ' NULL',
        lmp_edd: 0,
        parity: 0,
        gravidity: 0,
        message:
            'Blood Pressure = 119-68\nWeight = 80\nCurrent Symptoms = No symptoms\nSupplements = Takes Supplements\nRisk = low\nContact = 3',
        event_date: '2019-10-03T07:30:38.168000',
        intervention: ' NULL',
        breastfeeding: ' NULL',
        client_type: 'ec_woman',
        gender: 'F',
        child_no: ' NULL',
        first_name: 'Rory',
        second_name: ' NULL',
        third_name: ' NULL',
        last_name: ' NULL',
        date_of_birth: 0,
        year_of_birth: 1981,
        patient_contact: ' NULL',
        location_id: 'bb37165f-2ee9-4cad-a3b5-020c0cc75ccf',
        contact: '3',
        anc_visit_date: '2019-07-02',
        next_anc_date: '2019-09-02',
        event_id: '1570087838196',
        symptoms: 'BT',
        status: ' NULL',
        location: 'NHA',
        supplements: 'Takes Supplements',
        micronutrients: ' NULL',
        health_insurance_id: ' NULL',
        appointment_status: 'On Time',
        muac_status: ' NULL',
        response_status: ' NULL',
        risk_level: 'low',
        bmi: 0,
        muac: 0,
        lmp: 0,
        bp: '119-68',
        mother_symptoms: 'No symptoms',
        ethnicity: ' NULL',
        household: ' NULL',
        toilet: ' NULL',
        handwashing: ' NULL',
        planned_delivery_location: ' NULL',
        death_date: 0,
        location_of_death: ' NULL',
        death_code: ' NULL',
        logface_risk: 'low',
        death_reason: ' NULL',
        child_symptoms: ' NULL',
        delivery_location: ' NULL',
        delivery_method: ' NULL',
        child_risk_level: ' NULL',
        health_worker_contact: 'telegram:782996367',
        team: ' NULL',
    },
    {
        EventDate: '2019-10-03',
        sms_type: 'Birth Report',
        anc_id: '100P9K',
        age: '38y 9m',
        health_worker_location_name: 'Yen Phu Village',
        health_worker_name: 'Husna Hariz',
        height: 48,
        weight: 2.2,
        previous_risks: ' NULL',
        lmp_edd: 0,
        parity: 0,
        gravidity: 0,
        message:
            'Child DOB = 01-10-2019 \nChild Gender = NU \nDelivery Location = At home \nNewborn Symptoms = No symptoms, Hemorrhage/persistent bleeding \nChild Weight = 2.2 \nChild Length = 48 \nChild Risk = red_alert \nBreastfeeding = Breastfeeding during 1st hour\nMother Symptoms = No symptoms, Hemorrhage/persistent bleeding',
        event_date: '2019-10-03T07:31:29.462000',
        intervention: ' NULL',
        breastfeeding: 'Breastfeeding during 1st hour',
        client_type: 'ec_woman',
        gender: 'NU',
        child_no: '100P9K-20191001-01',
        first_name: 'Rory',
        second_name: ' NULL',
        third_name: ' NULL',
        last_name: ' NULL',
        date_of_birth: 0,
        year_of_birth: 1981,
        patient_contact: ' NULL',
        location_id: 'bb37165f-2ee9-4cad-a3b5-020c0cc75ccf',
        contact: '3',
        anc_visit_date: 0,
        next_anc_date: 0,
        event_id: '1570087889485',
        symptoms: 'BT XH',
        status: ' NULL',
        location: 'NHA',
        supplements: ' NULL',
        micronutrients: ' NULL',
        health_insurance_id: ' NULL',
        appointment_status: 'On Time',
        muac_status: ' NULL',
        response_status: ' NULL',
        risk_level: 'red_alert',
        bmi: 0,
        muac: 0,
        lmp: 0,
        bp: ' NULL',
        mother_symptoms: 'No symptoms, Hemorrhage/persistent bleeding',
        ethnicity: ' NULL',
        household: ' NULL',
        toilet: ' NULL',
        handwashing: ' NULL',
        planned_delivery_location: ' NULL',
        death_date: 0,
        location_of_death: ' NULL',
        death_code: ' NULL',
        logface_risk: 'red',
        death_reason: ' NULL',
        child_symptoms: 'No symptoms, Hemorrhage/persistent bleeding',
        delivery_location: 'At home',
        delivery_method: 'C-Section',
        child_risk_level: 'red_alert',
        health_worker_contact: 'telegram:782996367',
        team: ' NULL',
    },
    {
        EventDate: '2019-10-03',
        sms_type: 'Red Alert Report',
        anc_id: '100P9K-20191001-01',
        age: '0m',
        health_worker_location_name: 'Yen Phu Village',
        health_worker_name: 'Husna Hariz',
        height: 0,
        weight: 0,
        previous_risks: ' NULL',
        lmp_edd: 0,
        parity: 0,
        gravidity: 0,
        message: 'Symptoms = Coughing, Fever \nLocation = At home \nInterventions = ',
        event_date: '2019-10-03T08:02:40.982000',
        intervention: ' NULL',
        breastfeeding: ' NULL',
        client_type: 'ec_child',
        gender: ' NULL',
        child_no: '01',
        first_name: ' NULL',
        second_name: ' NULL',
        third_name: ' NULL',
        last_name: ' NULL',
        date_of_birth: 0,
        year_of_birth: 2019,
        patient_contact: ' NULL',
        location_id: 'bb37165f-2ee9-4cad-a3b5-020c0cc75ccf',
        contact: ' NULL',
        anc_visit_date: 0,
        next_anc_date: 0,
        event_id: '1570089812157',
        symptoms: 'HO SOT',
        status: ' NULL',
        location: 'At home',
        supplements: ' NULL',
        micronutrients: ' NULL',
        health_insurance_id: ' NULL',
        appointment_status: 'On Time',
        muac_status: ' NULL',
        response_status: ' NULL',
        risk_level: 'red_alert',
        bmi: 0,
        muac: 0,
        lmp: 0,
        bp: ' NULL',
        mother_symptoms: ' NULL',
        ethnicity: ' NULL',
        household: ' NULL',
        toilet: ' NULL',
        handwashing: ' NULL',
        planned_delivery_location: ' NULL',
        death_date: 0,
        location_of_death: ' NULL',
        death_code: ' NULL',
        logface_risk: 'red',
        death_reason: ' NULL',
        child_symptoms: 'Coughing, Fever',
        delivery_location: ' NULL',
        delivery_method: ' NULL',
        child_risk_level: ' NULL',
        health_worker_contact: 'telegram:782996367',
        team: ' NULL',
    },
    {
        EventDate: '2019-10-04',
        sms_type: 'Pregnancy Detection',
        anc_id: '100PAH',
        age: '30y 9m',
        health_worker_location_name: 'Yen Phu Village',
        health_worker_name: 'HMN',
        height: 0,
        weight: 0,
        previous_risks: ' NULL',
        lmp_edd: 0,
        parity: 0,
        gravidity: 0,
        message: 'Name = Joy Loiuse  \nPhone Number = +84983105510 \nHealth Insurance = NA',
        event_date: '2019-10-04T06:36:35.102000',
        intervention: ' NULL',
        breastfeeding: ' NULL',
        client_type: 'ec_woman',
        gender: 'F',
        child_no: ' NULL',
        first_name: 'Joy',
        second_name: 'Loiuse',
        third_name: ' NULL',
        last_name: ' NULL',
        date_of_birth: 0,
        year_of_birth: 1989,
        patient_contact: '+84983105510',
        location_id: 'bb37165f-2ee9-4cad-a3b5-020c0cc75ccf',
        contact: ' NULL',
        anc_visit_date: 0,
        next_anc_date: 0,
        event_id: '1570170995321',
        symptoms: ' NULL',
        status: ' NULL',
        location: ' NULL',
        supplements: ' NULL',
        micronutrients: ' NULL',
        health_insurance_id: ' NULL',
        appointment_status: 'On Time',
        muac_status: ' NULL',
        response_status: ' NULL',
        risk_level: ' NULL',
        bmi: 0,
        muac: 0,
        lmp: 0,
        bp: ' NULL',
        mother_symptoms: ' NULL',
        ethnicity: ' NULL',
        household: ' NULL',
        toilet: ' NULL',
        handwashing: ' NULL',
        planned_delivery_location: ' NULL',
        death_date: 0,
        location_of_death: ' NULL',
        death_code: ' NULL',
        logface_risk: 'Not Set',
        death_reason: ' NULL',
        child_symptoms: ' NULL',
        delivery_location: ' NULL',
        delivery_method: ' NULL',
        child_risk_level: ' NULL',
        health_worker_contact: 'telegram:611765738',
        team: ' NULL',
    },
    {
        EventDate: '2019-10-04',
        sms_type: 'Pregnancy Registration',
        anc_id: '100PAH',
        age: '30y 9m',
        health_worker_location_name: 'Yen Phu Village',
        health_worker_name: 'HMN',
        height: 145,
        weight: 55,
        previous_risks: 'Previous pregnancy too close or too far, Home Delivery',
        lmp_edd: '2019-10-09',
        parity: 1,
        gravidity: 3,
        message:
            'EDD = 09-10-2019\nGravidity = 3\nParity = 1\nWeight = 55 \nHeight = 145\nBMI = 26\nPrevious Gynaecology History = Previous pregnancy too close or too far, Home Delivery\nCurrent Symptoms = Heavy sweating, Coughing',
        event_date: '2019-10-04T06:38:49.432000',
        intervention: ' NULL',
        breastfeeding: ' NULL',
        client_type: 'ec_woman',
        gender: 'F',
        child_no: ' NULL',
        first_name: 'Joy',
        second_name: ' NULL',
        third_name: ' NULL',
        last_name: ' NULL',
        date_of_birth: 0,
        year_of_birth: 1989,
        patient_contact: ' NULL',
        location_id: 'bb37165f-2ee9-4cad-a3b5-020c0cc75ccf',
        contact: '0',
        anc_visit_date: '2019-10-04',
        next_anc_date: '2019-07-02',
        event_id: '1570171129630',
        symptoms: 'RMH HO',
        status: ' NULL',
        location: ' NULL',
        supplements: ' NULL',
        micronutrients: ' NULL',
        health_insurance_id: ' NULL',
        appointment_status: 'On Time',
        muac_status: ' NULL',
        response_status: ' NULL',
        risk_level: 'red_alert',
        bmi: 26,
        muac: 0,
        lmp: '2019-01-02',
        bp: '120/80',
        mother_symptoms: 'Heavy sweating, Coughing',
        ethnicity: ' NULL',
        household: ' NULL',
        toilet: ' NULL',
        handwashing: ' NULL',
        planned_delivery_location: ' NULL',
        death_date: 0,
        location_of_death: ' NULL',
        death_code: ' NULL',
        logface_risk: 'red',
        death_reason: ' NULL',
        child_symptoms: ' NULL',
        delivery_location: ' NULL',
        delivery_method: ' NULL',
        child_risk_level: ' NULL',
        health_worker_contact: 'telegram:611765738',
        team: ' NULL',
    },
    {
        EventDate: '2019-10-04',
        sms_type: 'Red Alert Report',
        anc_id: '100P9K-20191001-01',
        age: '3d',
        health_worker_location_name: 'Yen Phu Village',
        health_worker_name: 'Husna Hariz',
        height: 0,
        weight: 0,
        previous_risks: ' NULL',
        lmp_edd: 0,
        parity: 0,
        gravidity: 0,
        message: 'Symptoms = Coughing, Fever \nLocation = At home \nInterventions = ',
        event_date: '2019-10-04T07:16:38.749000',
        intervention: ' NULL',
        breastfeeding: ' NULL',
        client_type: 'ec_child',
        gender: ' NULL',
        child_no: '01',
        first_name: ' NULL',
        second_name: ' NULL',
        third_name: ' NULL',
        last_name: ' NULL',
        date_of_birth: 0,
        year_of_birth: 2019,
        patient_contact: ' NULL',
        location_id: 'bb37165f-2ee9-4cad-a3b5-020c0cc75ccf',
        contact: ' NULL',
        anc_visit_date: 0,
        next_anc_date: 0,
        event_id: '1570173399115',
        symptoms: 'HO SOT',
        status: ' NULL',
        location: 'At home',
        supplements: ' NULL',
        micronutrients: ' NULL',
        health_insurance_id: ' NULL',
        appointment_status: 'On Time',
        muac_status: ' NULL',
        response_status: ' NULL',
        risk_level: 'red_alert',
        bmi: 0,
        muac: 0,
        lmp: 0,
        bp: ' NULL',
        mother_symptoms: ' NULL',
        ethnicity: ' NULL',
        household: ' NULL',
        toilet: ' NULL',
        handwashing: ' NULL',
        planned_delivery_location: ' NULL',
        death_date: 0,
        location_of_death: ' NULL',
        death_code: ' NULL',
        logface_risk: 'red',
        death_reason: ' NULL',
        child_symptoms: 'Coughing, Fever',
        delivery_location: ' NULL',
        delivery_method: ' NULL',
        child_risk_level: ' NULL',
        health_worker_contact: 'telegram:782996367',
        team: ' NULL',
    },
    {
        EventDate: '2019-10-04',
        sms_type: 'Response Report',
        anc_id: '100P9K-20191001-01',
        age: '3d',
        health_worker_location_name: 'Yen Phu Village',
        health_worker_name: 'Husna Hariz',
        height: 0,
        weight: 0,
        previous_risks: ' NULL',
        lmp_edd: 0,
        parity: 0,
        gravidity: 0,
        message: 'Symptoms = No symptoms  \nIntervention = Ambulance On Time \nHealth Status = ',
        event_date: '2019-10-04T07:20:02.008000',
        intervention: 'Ambulance On Time',
        breastfeeding: ' NULL',
        client_type: 'ec_child',
        gender: ' NULL',
        child_no: '01',
        first_name: ' NULL',
        second_name: ' NULL',
        third_name: ' NULL',
        last_name: ' NULL',
        date_of_birth: 0,
        year_of_birth: 2019,
        patient_contact: ' NULL',
        location_id: 'bb37165f-2ee9-4cad-a3b5-020c0cc75ccf',
        contact: ' NULL',
        anc_visit_date: 0,
        next_anc_date: 0,
        event_id: '1570173602178',
        symptoms: 'BT',
        status: ' NULL',
        location: 'At home',
        supplements: ' NULL',
        micronutrients: ' NULL',
        health_insurance_id: ' NULL',
        appointment_status: 'On Time',
        muac_status: ' NULL',
        response_status: ' NULL',
        risk_level: 'no_risk',
        bmi: 0,
        muac: 0,
        lmp: 0,
        bp: ' NULL',
        mother_symptoms: ' NULL',
        ethnicity: ' NULL',
        household: ' NULL',
        toilet: ' NULL',
        handwashing: ' NULL',
        planned_delivery_location: ' NULL',
        death_date: 0,
        location_of_death: ' NULL',
        death_code: ' NULL',
        logface_risk: 'no risk',
        death_reason: ' NULL',
        child_symptoms: 'No symptoms',
        delivery_location: ' NULL',
        delivery_method: ' NULL',
        child_risk_level: ' NULL',
        health_worker_contact: 'telegram:782996367',
        team: ' NULL',
    },
] as unknown) as SmsData[];
