// tslint:disable object-literal-sort-keys
export const convertToStringArrayInput = {
  age: '-1',
  anc_id: '100NG6',
  anc_visit_date: 0,
  appointment_status: 'On Time',
  bmi: 0,
  bp: ' NULL',
  breastfeeding: 'Breastfeeding during 1st hour',
  child_no: '100NG6-20200401-1',
  child_risk_level: 'red_alert',
  child_symptoms: 'Hypothermia, Fever',
  client_type: 'ec_woman',
  contact: '4',
  date_of_birth: 0,
  death_code: ' NULL',
  death_date: 0,
  death_reason: ' NULL',
  delivery_location: 'District hospitals/CDC',
  delivery_method: 'Some delivery method',
  ethnicity: ' NULL',
  event_date: '2019-09-27T11:45:02.606000',
  event_id: '1569570302932',
  EventDate: '2019-09-27',
  first_name: 'habiba',
  gender: 'M',
  gravidity: 0,
  handwashing: ' NULL',
  health_insurance_id: ' NULL',
  health_worker_contact: 'telegram:782996367',
  health_worker_location_name: 'Saigon',
  health_worker_name: 'Husna Hariz',
  height: 31,
  household: ' NULL',
  intervention: ' NULL',
  last_name: ' NULL',
  lmp: 0,
  lmp_edd: 0,
  location: 'BVH',
  location_id: '1234567890987654321',
  location_of_death: ' NULL',
  logface_risk: 'red',
  message:
    'Child DOB = 2020-04-01 \nChild Gender = M \nDelivery Location = District hospitals/CDC \nNewborn Symptoms = Hypothermia, Fever \nChild Weight = 25 \nChild Length = 31 \nChild Risk = red_alert \nBreastfeeding = Breastfeeding during 1st hour',
  micronutrients: ' NULL',
  mother_symptoms: 'Hypothermia, Fever',
  muac: 0,
  muac_status: ' NULL',
  next_anc_date: 0,
  parity: 0,
  patient_contact: ' NULL',
  planned_delivery_location: ' NULL',
  previous_risks: ' NULL',
  response_status: ' NULL',
  risk_level: 'red_alert',
  second_name: ' NULL',
  sms_type: 'Birth Report',
  status: ' NULL',
  supplements: ' NULL',
  symptoms: 'HNH SOT',
  team: ' NULL',
  third_name: ' NULL',
  toilet: ' NULL',
  weight: 25,
  year_of_birth: 2020,
};

export const convertToStringArrayOutput: string[] = [
  'Birth Report',
  '2019-09-27',
  'Husna Hariz',
  'Child DOB = 2020-04-01 \nChild Gender = M \nDelivery Location = District hospitals/CDC \nNewborn Symptoms = Hypothermia, Fever \nChild Weight = 25 \nChild Length = 31 \nChild Risk = red_alert \nBreastfeeding = Breastfeeding during 1st hour',
];

export const convertToStringArrayInput2 = {
  EventDate: '2019-10-02',
  sms_type: 'Pregnancy Registration',
  // tslint:disable-next-line: object-literal-sort-keys
  anc_id: '100P7P',
  age: '36y 9m',
  health_worker_location_name: 'Saigon',
  health_worker_name: 'Husna Hariz',
  height: 165,
  weight: 78,
  previous_risks: 'Previous C-section/forcep/?, Previous convulsion',
  lmp_edd: '2019-12-07',
  parity: 3,
  gravidity: 4,
  message:
    'EDD = 07-12-2019\nGravidity = 4\nParity = 3\nWeight = 78 \nHeight = 165\nBMI = 28\nPrevious Gynaecology History = Previous C-section/forcep/?, Previous convulsion\nCurrent Symptoms = Coughing',
  event_date: '2019-10-02T09:04:37.551000',
  intervention: ' NULL',
  breastfeeding: ' NULL',
  client_type: 'ec_woman',
  gender: 'F',
  child_no: ' NULL',
  first_name: 'priscilla',
  second_name: ' NULL',
  third_name: ' NULL',
  last_name: ' NULL',
  date_of_birth: 0,
  year_of_birth: 1983,
  patient_contact: ' NULL',
  location_id: '1234567890987654321',
  contact: '0',
  anc_visit_date: '2019-10-02',
  next_anc_date: '2019-09-02',
  event_id: '1570007091641',
  symptoms: 'HO',
  status: ' NULL',
  location: ' NULL',
  supplements: ' NULL',
  micronutrients: ' NULL',
  health_insurance_id: ' NULL',
  appointment_status: 'On Time',
  muac_status: ' NULL',
  response_status: ' NULL',
  risk_level: 'high',
  bmi: 28,
  muac: 0,
  lmp: '2019-03-02',
  bp: '120/80',
  mother_symptoms: 'Coughing',
  ethnicity: ' NULL',
  household: ' NULL',
  toilet: ' NULL',
  handwashing: ' NULL',
  planned_delivery_location: ' NULL',
  death_date: 0,
  location_of_death: ' NULL',
  death_code: ' NULL',
  logface_risk: 'high',
  death_reason: ' NULL',
  child_symptoms: ' NULL',
  delivery_location: ' NULL',
  delivery_method: ' NULL',
  child_risk_level: ' NULL',
  health_worker_contact: 'telegram:782996367',
  team: ' NULL',
};

export const convertToStringArrayOutput2 = [
  'Pregnancy Registration',
  '2019-10-02',
  'Husna Hariz',
  'EDD = 07-12-2019\nGravidity = 4\nParity = 3\nWeight = 78 \nHeight = 165\nBMI = 28\nPrevious Gynaecology History = Previous C-section/forcep/?, Previous convulsion\nCurrent Symptoms = Coughing',
];

export const getEventsPregnancyArrayInput1 = [
  {
    EventDate: '2019-09-25',
    sms_type: 'Pregnancy Detection',
    anc_id: '100NG6',
    age: '33',
    health_worker_location_name: 'Saigon',
    health_worker_name: 'Husna Hariz',
    height: 0,
    weight: 0,
    previous_risks: ' NULL',
    lmp_edd: 0,
    parity: 0,
    gravidity: 0,
    message: 'Name = habiba farsy  \nPhone Number = +84984664991 \nHealth Insurance = ',
    event_date: '2019-09-25T14:34:47.592000',
    intervention: ' NULL',
    breastfeeding: ' NULL',
    client_type: 'ec_woman',
    gender: 'F',
    child_no: ' NULL',
    first_name: 'habiba',
    second_name: 'farsy',
    third_name: ' NULL',
    last_name: ' NULL',
    date_of_birth: 0,
    year_of_birth: 1986,
    patient_contact: '+84984664991',
    location_id: '1234567890987654321',
    contact: ' NULL',
    anc_visit_date: 0,
    next_anc_date: 0,
    event_id: '1569422087742',
    symptoms: ' NULL',
    status: ' NULL',
    location: ' NULL',
    supplements: ' NULL',
    micronutrients: ' NULL',
    health_insurance_id: ' NULL',
    appointment_status: 'On Time',
    muac_status: ' NULL',
    response_status: ' NULL',
    risk_level: ' NULL',
    bmi: 0,
    muac: 0,
    lmp: 0,
    bp: ' NULL',
    mother_symptoms: ' NULL',
    ethnicity: ' NULL',
    household: ' NULL',
    toilet: ' NULL',
    handwashing: ' NULL',
    planned_delivery_location: ' NULL',
    death_date: 0,
    location_of_death: ' NULL',
    death_code: ' NULL',
    logface_risk: 'Not Set',
    death_reason: ' NULL',
    child_symptoms: ' NULL',
    delivery_location: ' NULL',
    delivery_method: ' NULL',
    child_risk_level: ' NULL',
    health_worker_contact: 'telegram:782996367',
    team: ' NULL',
  },
  {
    EventDate: '2019-09-25',
    sms_type: 'Pregnancy Registration',
    anc_id: '100NG6',
    age: '33',
    health_worker_location_name: 'Saigon',
    health_worker_name: 'Husna Hariz',
    height: 160,
    weight: 54,
    previous_risks: 'Diabetes, High blood pressure',
    lmp_edd: '2019-04-01',
    parity: 2,
    gravidity: 3,
    message:
      'EDD = 2019-04-01\nGravidity = 3\nParity = 2\nWeight = 54 \nHeight = 160\nPrevious Gynaecology History = Diabetes, High blood pressure\nCurrent Symptoms = Flaccid Paralysis',
    event_date: '2019-09-25T18:35:13.412000',
    intervention: ' NULL',
    breastfeeding: ' NULL',
    client_type: 'ec_woman',
    gender: 'F',
    child_no: ' NULL',
    first_name: 'habiba',
    second_name: ' NULL',
    third_name: ' NULL',
    last_name: ' NULL',
    date_of_birth: 0,
    year_of_birth: 1986,
    patient_contact: ' NULL',
    location_id: '1234567890987654321',
    contact: '0',
    anc_visit_date: '2019-09-25',
    next_anc_date: '2019-10-22',
    event_id: '1569422113576',
    symptoms: 'LM',
    status: ' NULL',
    location: ' NULL',
    supplements: ' NULL',
    micronutrients: ' NULL',
    health_insurance_id: ' NULL',
    appointment_status: 'On Time',
    muac_status: ' NULL',
    response_status: ' NULL',
    risk_level: 'high',
    bmi: 21,
    muac: 0,
    lmp: '2018-06-25',
    bp: '123-78',
    mother_symptoms: 'Flaccid Paralysis',
    ethnicity: ' NULL',
    household: ' NULL',
    toilet: ' NULL',
    handwashing: ' NULL',
    planned_delivery_location: ' NULL',
    death_date: 0,
    location_of_death: ' NULL',
    death_code: ' NULL',
    logface_risk: 'high',
    death_reason: ' NULL',
    child_symptoms: ' NULL',
    delivery_location: ' NULL',
    delivery_method: ' NULL',
    child_risk_level: ' NULL',
    health_worker_contact: 'telegram:782996367',
    team: ' NULL',
  },
  {
    EventDate: '2019-09-25',
    sms_type: 'ANC Visit',
    anc_id: '100NG6',
    age: '33',
    health_worker_location_name: 'Saigon',
    health_worker_name: 'Husna Hariz',
    height: 0,
    weight: 67,
    previous_risks: ' NULL',
    lmp_edd: 0,
    parity: 0,
    gravidity: 0,
    message:
      'Blood Pressure = 119-68\nWeight = 67\nCurrent Symptoms = Coughing\nSupplements = Takes Supplements\nRisk = high\nContact = 1',
    event_date: '2019-09-25T18:37:45.264000',
    intervention: ' NULL',
    breastfeeding: ' NULL',
    client_type: 'ec_woman',
    gender: 'F',
    child_no: ' NULL',
    first_name: 'habiba',
    second_name: ' NULL',
    third_name: ' NULL',
    last_name: ' NULL',
    date_of_birth: 0,
    year_of_birth: 1986,
    patient_contact: ' NULL',
    location_id: '1234567890987654321',
    contact: '1',
    anc_visit_date: '2019-10-22',
    next_anc_date: '2019-12-12',
    event_id: '1569422265409',
    symptoms: 'HO',
    status: ' NULL',
    location: ' NULL',
    supplements: 'Takes Supplements',
    micronutrients: ' NULL',
    health_insurance_id: ' NULL',
    appointment_status: 'On Time',
    muac_status: ' NULL',
    response_status: ' NULL',
    risk_level: 'high',
    bmi: 0,
    muac: 0,
    lmp: 0,
    bp: '119-68',
    mother_symptoms: 'Coughing',
    ethnicity: ' NULL',
    household: ' NULL',
    toilet: ' NULL',
    handwashing: ' NULL',
    planned_delivery_location: ' NULL',
    death_date: 0,
    location_of_death: ' NULL',
    death_code: ' NULL',
    logface_risk: 'high',
    death_reason: ' NULL',
    child_symptoms: ' NULL',
    delivery_location: ' NULL',
    delivery_method: ' NULL',
    child_risk_level: ' NULL',
    health_worker_contact: 'telegram:782996367',
    team: ' NULL',
  },
  {
    EventDate: '2019-09-25',
    sms_type: 'ANC Visit',
    anc_id: '100NG6',
    age: '33',
    health_worker_location_name: 'Saigon',
    health_worker_name: 'Husna Hariz',
    height: 0,
    weight: 67,
    previous_risks: ' NULL',
    lmp_edd: 0,
    parity: 0,
    gravidity: 0,
    message:
      'Blood Pressure = 119-68\nWeight = 67\nCurrent Symptoms = Coughing\nSupplements = Takes Supplements\nRisk = high\nContact = 2',
    event_date: '2019-09-25T18:39:11.560000',
    intervention: ' NULL',
    breastfeeding: ' NULL',
    client_type: 'ec_woman',
    gender: 'F',
    child_no: ' NULL',
    first_name: 'habiba',
    second_name: ' NULL',
    third_name: ' NULL',
    last_name: ' NULL',
    date_of_birth: 0,
    year_of_birth: 1986,
    patient_contact: ' NULL',
    location_id: '1234567890987654321',
    contact: '2',
    anc_visit_date: '2019-11-22',
    next_anc_date: '2019-12-12',
    event_id: '1569422351719',
    symptoms: 'HO',
    status: ' NULL',
    location: ' NULL',
    supplements: 'Takes Supplements',
    micronutrients: ' NULL',
    health_insurance_id: ' NULL',
    appointment_status: 'On Time',
    muac_status: ' NULL',
    response_status: ' NULL',
    risk_level: 'high',
    bmi: 0,
    muac: 0,
    lmp: 0,
    bp: '119-68',
    mother_symptoms: 'Coughing',
    ethnicity: ' NULL',
    household: ' NULL',
    toilet: ' NULL',
    handwashing: ' NULL',
    planned_delivery_location: ' NULL',
    death_date: 0,
    location_of_death: ' NULL',
    death_code: ' NULL',
    logface_risk: 'high',
    death_reason: ' NULL',
    child_symptoms: ' NULL',
    delivery_location: ' NULL',
    delivery_method: ' NULL',
    child_risk_level: ' NULL',
    health_worker_contact: 'telegram:782996367',
    team: ' NULL',
  },
  {
    EventDate: '2019-09-25',
    sms_type: 'Delivery Planning',
    anc_id: '100NG6',
    age: '33',
    health_worker_location_name: 'Saigon',
    health_worker_name: 'Husna Hariz',
    height: 0,
    weight: 0,
    previous_risks: ' NULL',
    lmp_edd: 0,
    parity: 0,
    gravidity: 0,
    message: 'Planned Delivery Location = At home \nCurrent Symptoms = No symptoms',
    event_date: '2019-09-25T18:40:35.036000',
    intervention: ' NULL',
    breastfeeding: ' NULL',
    client_type: 'ec_woman',
    gender: 'F',
    child_no: ' NULL',
    first_name: 'habiba',
    second_name: ' NULL',
    third_name: ' NULL',
    last_name: ' NULL',
    date_of_birth: 0,
    year_of_birth: 1986,
    patient_contact: ' NULL',
    location_id: '1234567890987654321',
    contact: '2',
    anc_visit_date: 0,
    next_anc_date: '2019-12-12',
    event_id: '1569422435185',
    symptoms: 'BT',
    status: ' NULL',
    location: 'NHA',
    supplements: ' NULL',
    micronutrients: ' NULL',
    health_insurance_id: ' NULL',
    appointment_status: 'On Time',
    muac_status: ' NULL',
    response_status: ' NULL',
    risk_level: 'no_risk',
    bmi: 0,
    muac: 0,
    lmp: 0,
    bp: ' NULL',
    mother_symptoms: 'No symptoms',
    ethnicity: ' NULL',
    household: ' NULL',
    toilet: ' NULL',
    handwashing: ' NULL',
    planned_delivery_location: 'At home',
    death_date: 0,
    location_of_death: ' NULL',
    death_code: ' NULL',
    logface_risk: 'no risk',
    death_reason: ' NULL',
    child_symptoms: ' NULL',
    delivery_location: ' NULL',
    delivery_method: ' NULL',
    child_risk_level: ' NULL',
    health_worker_contact: 'telegram:782996367',
    team: ' NULL',
  },
  {
    EventDate: '2019-09-25',
    sms_type: 'Social Determinants',
    anc_id: '100NG6',
    age: '33',
    health_worker_location_name: 'Saigon',
    health_worker_name: 'Husna Hariz',
    height: 0,
    weight: 0,
    previous_risks: ' NULL',
    lmp_edd: 0,
    parity: 0,
    gravidity: 0,
    message:
      'Planned Delivery Location = At home\nHousehold = HNG\nEthnicity = TAY\nToilet = Has no toilet\nHandwashing = Has no handwashing',
    event_date: '2019-09-25T18:41:54.819000',
    intervention: ' NULL',
    breastfeeding: ' NULL',
    client_type: 'ec_woman',
    gender: 'F',
    child_no: ' NULL',
    first_name: 'habiba',
    second_name: ' NULL',
    third_name: ' NULL',
    last_name: ' NULL',
    date_of_birth: 0,
    year_of_birth: 1986,
    patient_contact: ' NULL',
    location_id: '1234567890987654321',
    contact: '2',
    anc_visit_date: 0,
    next_anc_date: 0,
    event_id: '1569422514986',
    symptoms: ' NULL',
    status: ' NULL',
    location: 'NHA',
    supplements: ' NULL',
    micronutrients: ' NULL',
    health_insurance_id: ' NULL',
    appointment_status: 'On Time',
    muac_status: ' NULL',
    response_status: ' NULL',
    risk_level: 'no_risk',
    bmi: 0,
    muac: 0,
    lmp: 0,
    bp: ' NULL',
    mother_symptoms: ' NULL',
    ethnicity: 'TAY',
    household: 'HNG',
    toilet: 'Has no toilet',
    handwashing: 'Has no handwashing',
    planned_delivery_location: 'At home',
    death_date: 0,
    location_of_death: ' NULL',
    death_code: ' NULL',
    logface_risk: 'no risk',
    death_reason: ' NULL',
    child_symptoms: ' NULL',
    delivery_location: ' NULL',
    delivery_method: ' NULL',
    child_risk_level: ' NULL',
    health_worker_contact: 'telegram:782996367',
    team: ' NULL',
  },
  {
    EventDate: '2019-09-25',
    sms_type: 'ANC Visit',
    anc_id: '100NG6',
    age: '33',
    health_worker_location_name: 'Saigon',
    health_worker_name: 'Husna Hariz',
    height: 0,
    weight: 68,
    previous_risks: ' NULL',
    lmp_edd: 0,
    parity: 0,
    gravidity: 0,
    message:
      'Blood Pressure = 130-78\nWeight = 68\nCurrent Symptoms = Coughing, Fever, Chronic Disease, Congenital malformation\nSupplements = Takes Supplements\nRisk = high\nContact = 3',
    event_date: '2019-09-25T18:58:28.478000',
    intervention: ' NULL',
    breastfeeding: ' NULL',
    client_type: 'ec_woman',
    gender: 'F',
    child_no: ' NULL',
    first_name: 'habiba',
    second_name: ' NULL',
    third_name: ' NULL',
    last_name: ' NULL',
    date_of_birth: 0,
    year_of_birth: 1986,
    patient_contact: ' NULL',
    location_id: '1234567890987654321',
    contact: '3',
    anc_visit_date: '2019-12-22',
    next_anc_date: '2020-02-12',
    event_id: '1569423508727',
    symptoms: 'HO SOT KN DG',
    status: ' NULL',
    location: 'NHA',
    supplements: 'Takes Supplements',
    micronutrients: ' NULL',
    health_insurance_id: ' NULL',
    appointment_status: 'On Time',
    muac_status: ' NULL',
    response_status: ' NULL',
    risk_level: 'high',
    bmi: 0,
    muac: 0,
    lmp: 0,
    bp: '130-78',
    mother_symptoms: 'Coughing, Fever, Chronic Disease, Congenital malformation',
    ethnicity: ' NULL',
    household: ' NULL',
    toilet: ' NULL',
    handwashing: ' NULL',
    planned_delivery_location: ' NULL',
    death_date: 0,
    location_of_death: ' NULL',
    death_code: ' NULL',
    logface_risk: 'high',
    death_reason: ' NULL',
    child_symptoms: ' NULL',
    delivery_location: ' NULL',
    delivery_method: ' NULL',
    child_risk_level: ' NULL',
    health_worker_contact: 'telegram:782996367',
    team: ' NULL',
  },
  {
    EventDate: '2019-09-25',
    sms_type: 'ANC Visit',
    anc_id: '100NG6',
    age: '33',
    health_worker_location_name: 'Saigon',
    health_worker_name: 'Husna Hariz',
    height: 0,
    weight: 68,
    previous_risks: ' NULL',
    lmp_edd: 0,
    parity: 0,
    gravidity: 0,
    message:
      'Blood Pressure = 130-78\nWeight = 68\nCurrent Symptoms = Coughing, Fever, Chronic Disease, Congenital malformation\nSupplements = Takes Supplements\nRisk = high\nContact = 4',
    event_date: '2019-09-25T19:00:56.009000',
    intervention: ' NULL',
    breastfeeding: ' NULL',
    client_type: 'ec_woman',
    gender: 'F',
    child_no: ' NULL',
    first_name: 'habiba',
    second_name: ' NULL',
    third_name: ' NULL',
    last_name: ' NULL',
    date_of_birth: 0,
    year_of_birth: 1986,
    patient_contact: ' NULL',
    location_id: '1234567890987654321',
    contact: '4',
    anc_visit_date: '2020-02-22',
    next_anc_date: '2020-03-12',
    event_id: '1569423656162',
    symptoms: 'HO SOT KN DG',
    status: ' NULL',
    location: 'NHA',
    supplements: 'Takes Supplements',
    micronutrients: ' NULL',
    health_insurance_id: ' NULL',
    appointment_status: 'On Time',
    muac_status: ' NULL',
    response_status: ' NULL',
    risk_level: 'high',
    bmi: 0,
    muac: 0,
    lmp: 0,
    bp: '130-78',
    mother_symptoms: 'Coughing, Fever, Chronic Disease, Congenital malformation',
    ethnicity: ' NULL',
    household: ' NULL',
    toilet: ' NULL',
    handwashing: ' NULL',
    planned_delivery_location: ' NULL',
    death_date: 0,
    location_of_death: ' NULL',
    death_code: ' NULL',
    logface_risk: 'high',
    death_reason: ' NULL',
    child_symptoms: ' NULL',
    delivery_location: ' NULL',
    delivery_method: ' NULL',
    child_risk_level: ' NULL',
    health_worker_contact: 'telegram:782996367',
    team: ' NULL',
  },
  {
    EventDate: '2019-09-25',
    sms_type: 'Birth Report',
    anc_id: '100NG6',
    age: '-1',
    health_worker_location_name: 'Saigon',
    health_worker_name: 'Husna Hariz',
    height: 31,
    weight: 25,
    previous_risks: ' NULL',
    lmp_edd: 0,
    parity: 0,
    gravidity: 0,
    message:
      'Child DOB = 2020-01-01 \nChild Gender = M \nDelivery Location = District hospitals/CDC \nNewborn Symptoms = Hypothermia, Fever \nChild Weight = 25 \nChild Length = 31 \nChild Risk = red_alert \nBreastfeeding = Breastfeeding during 1st hour',
    event_date: '2019-09-25T19:04:40.435000',
    intervention: ' NULL',
    breastfeeding: 'Breastfeeding during 1st hour',
    client_type: 'ec_woman',
    gender: 'M',
    child_no: '100NG6-20200101-1',
    first_name: 'habiba',
    second_name: ' NULL',
    third_name: ' NULL',
    last_name: ' NULL',
    date_of_birth: 0,
    year_of_birth: 2020,
    patient_contact: ' NULL',
    location_id: '1234567890987654321',
    contact: '4',
    anc_visit_date: 0,
    next_anc_date: 0,
    event_id: '1569423880614',
    symptoms: 'HNH SOT',
    status: ' NULL',
    location: 'BVH',
    supplements: ' NULL',
    micronutrients: ' NULL',
    health_insurance_id: ' NULL',
    appointment_status: 'On Time',
    muac_status: ' NULL',
    response_status: ' NULL',
    risk_level: 'red_alert',
    bmi: 0,
    muac: 0,
    lmp: 0,
    bp: ' NULL',
    mother_symptoms: 'Hypothermia, Fever',
    ethnicity: ' NULL',
    household: ' NULL',
    toilet: ' NULL',
    handwashing: ' NULL',
    planned_delivery_location: ' NULL',
    death_date: 0,
    location_of_death: ' NULL',
    death_code: ' NULL',
    logface_risk: 'red',
    death_reason: ' NULL',
    child_symptoms: 'Hypothermia, Fever',
    delivery_location: 'District hospitals/CDC',
    delivery_method: 'Some delivery method',
    child_risk_level: 'red_alert',
    health_worker_contact: 'telegram:782996367',
    team: ' NULL',
  },
  {
    EventDate: '2019-09-25',
    sms_type: 'Birth Report',
    anc_id: '100NG6',
    age: '-1',
    health_worker_location_name: 'Saigon',
    health_worker_name: 'Husna Hariz',
    height: 31,
    weight: 25,
    previous_risks: ' NULL',
    lmp_edd: 0,
    parity: 0,
    gravidity: 0,
    message:
      'Child DOB = 2020-04-01 \nChild Gender = M \nDelivery Location = District hospitals/CDC \nNewborn Symptoms = Hypothermia, Fever \nChild Weight = 25 \nChild Length = 31 \nChild Risk = red_alert \nBreastfeeding = Breastfeeding during 1st hour',
    event_date: '2019-09-25T19:09:11.619000',
    intervention: ' NULL',
    breastfeeding: 'Breastfeeding during 1st hour',
    client_type: 'ec_woman',
    gender: 'M',
    child_no: '100NG6-20200401-1',
    first_name: 'habiba',
    second_name: ' NULL',
    third_name: ' NULL',
    last_name: ' NULL',
    date_of_birth: 0,
    year_of_birth: 2020,
    patient_contact: ' NULL',
    location_id: '1234567890987654321',
    contact: '4',
    anc_visit_date: 0,
    next_anc_date: 0,
    event_id: '1569424151860',
    symptoms: 'HNH SOT',
    status: ' NULL',
    location: 'BVH',
    supplements: ' NULL',
    micronutrients: ' NULL',
    health_insurance_id: ' NULL',
    appointment_status: 'On Time',
    muac_status: ' NULL',
    response_status: ' NULL',
    risk_level: 'red_alert',
    bmi: 0,
    muac: 0,
    lmp: 0,
    bp: ' NULL',
    mother_symptoms: 'Hypothermia, Fever',
    ethnicity: ' NULL',
    household: ' NULL',
    toilet: ' NULL',
    handwashing: ' NULL',
    planned_delivery_location: ' NULL',
    death_date: 0,
    location_of_death: ' NULL',
    death_code: ' NULL',
    logface_risk: 'red',
    death_reason: ' NULL',
    child_symptoms: 'Hypothermia, Fever',
    delivery_location: 'District hospitals/CDC',
    delivery_method: 'Some delivery method',
    child_risk_level: 'red_alert',
    health_worker_contact: 'telegram:782996367',
    team: ' NULL',
  },
  {
    EventDate: '2019-09-26',
    sms_type: 'Red Alert Report',
    anc_id: '100NG6',
    age: '33',
    health_worker_location_name: 'Saigon',
    health_worker_name: 'Husna Hariz',
    height: 0,
    weight: 0,
    previous_risks: ' NULL',
    lmp_edd: 0,
    parity: 0,
    gravidity: 0,
    message: 'Symptoms = Dark vaginal blood \nLocation = At home \nInterventions = ',
    event_date: '2019-09-26T00:43:17.427000',
    intervention: ' NULL',
    breastfeeding: ' NULL',
    client_type: 'ec_woman',
    gender: 'F',
    child_no: ' NULL',
    first_name: 'habiba',
    second_name: ' NULL',
    third_name: ' NULL',
    last_name: ' NULL',
    date_of_birth: 0,
    year_of_birth: 1986,
    patient_contact: ' NULL',
    location_id: '1234567890987654321',
    contact: ' NULL',
    anc_visit_date: 0,
    next_anc_date: 0,
    event_id: '1569444197999',
    symptoms: 'MD',
    status: ' NULL',
    location: 'At home',
    supplements: ' NULL',
    micronutrients: ' NULL',
    health_insurance_id: ' NULL',
    appointment_status: 'On Time',
    muac_status: ' NULL',
    response_status: ' NULL',
    risk_level: 'red_alert',
    bmi: 0,
    muac: 0,
    lmp: 0,
    bp: ' NULL',
    mother_symptoms: 'Dark vaginal blood',
    ethnicity: ' NULL',
    household: ' NULL',
    toilet: ' NULL',
    handwashing: ' NULL',
    planned_delivery_location: ' NULL',
    death_date: 0,
    location_of_death: ' NULL',
    death_code: ' NULL',
    logface_risk: 'red',
    death_reason: ' NULL',
    child_symptoms: ' NULL',
    delivery_location: ' NULL',
    delivery_method: ' NULL',
    child_risk_level: ' NULL',
    health_worker_contact: 'telegram:782996367',
    team: ' NULL',
  },
  {
    EventDate: '2019-09-26',
    sms_type: 'Red Alert Report',
    anc_id: '100NG6',
    age: '33',
    health_worker_location_name: 'Saigon',
    health_worker_name: 'Husna Hariz',
    height: 0,
    weight: 0,
    previous_risks: ' NULL',
    lmp_edd: 0,
    parity: 0,
    gravidity: 0,
    message: 'Symptoms = Dark vaginal blood \nLocation = At home \nInterventions = ',
    event_date: '2019-09-26T00:48:55.842000',
    intervention: ' NULL',
    breastfeeding: ' NULL',
    client_type: 'ec_woman',
    gender: 'F',
    child_no: ' NULL',
    first_name: 'habiba',
    second_name: ' NULL',
    third_name: ' NULL',
    last_name: ' NULL',
    date_of_birth: 0,
    year_of_birth: 1986,
    patient_contact: ' NULL',
    location_id: '1234567890987654321',
    contact: ' NULL',
    anc_visit_date: 0,
    next_anc_date: 0,
    event_id: '1569444536025',
    symptoms: 'MD',
    status: ' NULL',
    location: 'At home',
    supplements: ' NULL',
    micronutrients: ' NULL',
    health_insurance_id: ' NULL',
    appointment_status: 'On Time',
    muac_status: ' NULL',
    response_status: ' NULL',
    risk_level: 'red_alert',
    bmi: 0,
    muac: 0,
    lmp: 0,
    bp: ' NULL',
    mother_symptoms: 'Dark vaginal blood',
    ethnicity: ' NULL',
    household: ' NULL',
    toilet: ' NULL',
    handwashing: ' NULL',
    planned_delivery_location: ' NULL',
    death_date: 0,
    location_of_death: ' NULL',
    death_code: ' NULL',
    logface_risk: 'red',
    death_reason: ' NULL',
    child_symptoms: ' NULL',
    delivery_location: ' NULL',
    delivery_method: ' NULL',
    child_risk_level: ' NULL',
    health_worker_contact: 'telegram:782996367',
    team: ' NULL',
  },
  {
    EventDate: '2019-09-26',
    sms_type: 'Red Alert Report',
    anc_id: '100NG6',
    age: '33',
    health_worker_location_name: 'Saigon',
    health_worker_name: 'Husna Hariz',
    height: 0,
    weight: 0,
    previous_risks: ' NULL',
    lmp_edd: 0,
    parity: 0,
    gravidity: 0,
    message: 'Symptoms = Dark vaginal blood \nLocation = At home \nInterventions = ',
    event_date: '2019-09-26T00:55:01.344000',
    intervention: ' NULL',
    breastfeeding: ' NULL',
    client_type: 'ec_woman',
    gender: 'F',
    child_no: ' NULL',
    first_name: 'habiba',
    second_name: ' NULL',
    third_name: ' NULL',
    last_name: ' NULL',
    date_of_birth: 0,
    year_of_birth: 1986,
    patient_contact: ' NULL',
    location_id: '1234567890987654321',
    contact: ' NULL',
    anc_visit_date: 0,
    next_anc_date: 0,
    event_id: '1569444901634',
    symptoms: 'MD',
    status: ' NULL',
    location: 'At home',
    supplements: ' NULL',
    micronutrients: ' NULL',
    health_insurance_id: ' NULL',
    appointment_status: 'On Time',
    muac_status: ' NULL',
    response_status: ' NULL',
    risk_level: 'red_alert',
    bmi: 0,
    muac: 0,
    lmp: 0,
    bp: ' NULL',
    mother_symptoms: 'Dark vaginal blood',
    ethnicity: ' NULL',
    household: ' NULL',
    toilet: ' NULL',
    handwashing: ' NULL',
    planned_delivery_location: ' NULL',
    death_date: 0,
    location_of_death: ' NULL',
    death_code: ' NULL',
    logface_risk: 'red',
    death_reason: ' NULL',
    child_symptoms: ' NULL',
    delivery_location: ' NULL',
    delivery_method: ' NULL',
    child_risk_level: ' NULL',
    health_worker_contact: 'telegram:782996367',
    team: ' NULL',
  },
  {
    EventDate: '2019-09-27',
    sms_type: 'Birth Report',
    anc_id: '100NG6',
    age: '-1',
    health_worker_location_name: 'Saigon',
    health_worker_name: 'Husna Hariz',
    height: 31,
    weight: 25,
    previous_risks: ' NULL',
    lmp_edd: 0,
    parity: 0,
    gravidity: 0,
    message:
      'Child DOB = 2020-04-01 \nChild Gender = M \nDelivery Location = District hospitals/CDC \nNewborn Symptoms = Hypothermia, Fever \nChild Weight = 25 \nChild Length = 31 \nChild Risk = red_alert \nBreastfeeding = Breastfeeding during 1st hour',
    event_date: '2019-09-27T11:26:49.742000',
    intervention: ' NULL',
    breastfeeding: 'Breastfeeding during 1st hour',
    client_type: 'ec_woman',
    gender: 'M',
    child_no: '100NG6-20200401-1',
    first_name: 'habiba',
    second_name: ' NULL',
    third_name: ' NULL',
    last_name: ' NULL',
    date_of_birth: 0,
    year_of_birth: 2020,
    patient_contact: ' NULL',
    location_id: '1234567890987654321',
    contact: '4',
    anc_visit_date: 0,
    next_anc_date: 0,
    event_id: '1569569210908',
    symptoms: 'HNH SOT',
    status: ' NULL',
    location: 'BVH',
    supplements: ' NULL',
    micronutrients: ' NULL',
    health_insurance_id: ' NULL',
    appointment_status: 'On Time',
    muac_status: ' NULL',
    response_status: ' NULL',
    risk_level: 'red_alert',
    bmi: 0,
    muac: 0,
    lmp: 0,
    bp: ' NULL',
    mother_symptoms: 'Hypothermia, Fever',
    ethnicity: ' NULL',
    household: ' NULL',
    toilet: ' NULL',
    handwashing: ' NULL',
    planned_delivery_location: ' NULL',
    death_date: 0,
    location_of_death: ' NULL',
    death_code: ' NULL',
    logface_risk: 'red',
    death_reason: ' NULL',
    child_symptoms: 'Hypothermia, Fever',
    delivery_location: 'District hospitals/CDC',
    delivery_method: 'Some delivery method',
    child_risk_level: 'red_alert',
    health_worker_contact: 'telegram:782996367',
    team: ' NULL',
  },
  {
    EventDate: '2019-09-27',
    sms_type: 'Birth Report',
    anc_id: '100NG6',
    age: '-1',
    health_worker_location_name: 'Saigon',
    health_worker_name: 'Husna Hariz',
    height: 31,
    weight: 25,
    previous_risks: ' NULL',
    lmp_edd: 0,
    parity: 0,
    gravidity: 0,
    message:
      'Child DOB = 2020-04-01 \nChild Gender = M \nDelivery Location = District hospitals/CDC \nNewborn Symptoms = Hypothermia, Fever \nChild Weight = 25 \nChild Length = 31 \nChild Risk = red_alert \nBreastfeeding = Breastfeeding during 1st hour',
    event_date: '2019-09-27T11:30:25.236000',
    intervention: ' NULL',
    breastfeeding: 'Breastfeeding during 1st hour',
    client_type: 'ec_woman',
    gender: 'M',
    child_no: '100NG6-20200401-1',
    first_name: 'habiba',
    second_name: ' NULL',
    third_name: ' NULL',
    last_name: ' NULL',
    date_of_birth: 0,
    year_of_birth: 2020,
    patient_contact: ' NULL',
    location_id: '1234567890987654321',
    contact: '4',
    anc_visit_date: 0,
    next_anc_date: 0,
    event_id: '1569569425411',
    symptoms: 'HNH SOT',
    status: ' NULL',
    location: 'BVH',
    supplements: ' NULL',
    micronutrients: ' NULL',
    health_insurance_id: ' NULL',
    appointment_status: 'On Time',
    muac_status: ' NULL',
    response_status: ' NULL',
    risk_level: 'red_alert',
    bmi: 0,
    muac: 0,
    lmp: 0,
    bp: ' NULL',
    mother_symptoms: 'Hypothermia, Fever',
    ethnicity: ' NULL',
    household: ' NULL',
    toilet: ' NULL',
    handwashing: ' NULL',
    planned_delivery_location: ' NULL',
    death_date: 0,
    location_of_death: ' NULL',
    death_code: ' NULL',
    logface_risk: 'red',
    death_reason: ' NULL',
    child_symptoms: 'Hypothermia, Fever',
    delivery_location: 'District hospitals/CDC',
    delivery_method: 'Some delivery method',
    child_risk_level: 'red_alert',
    health_worker_contact: 'telegram:782996367',
    team: ' NULL',
  },
  {
    EventDate: '2019-09-27',
    sms_type: 'Birth Report',
    anc_id: '100NG6',
    age: '-1',
    health_worker_location_name: 'Saigon',
    health_worker_name: 'Husna Hariz',
    height: 31,
    weight: 25,
    previous_risks: ' NULL',
    lmp_edd: 0,
    parity: 0,
    gravidity: 0,
    message:
      'Child DOB = 2020-04-01 \nChild Gender = M \nDelivery Location = District hospitals/CDC \nNewborn Symptoms = Hypothermia, Fever \nChild Weight = 25 \nChild Length = 31 \nChild Risk = red_alert \nBreastfeeding = Breastfeeding during 1st hour',
    event_date: '2019-09-27T11:45:02.606000',
    intervention: ' NULL',
    breastfeeding: 'Breastfeeding during 1st hour',
    client_type: 'ec_woman',
    gender: 'M',
    child_no: '100NG6-20200401-1',
    first_name: 'habiba',
    second_name: ' NULL',
    third_name: ' NULL',
    last_name: ' NULL',
    date_of_birth: 0,
    year_of_birth: 2020,
    patient_contact: ' NULL',
    location_id: '1234567890987654321',
    contact: '4',
    anc_visit_date: 0,
    next_anc_date: 0,
    event_id: '1569570302932',
    symptoms: 'HNH SOT',
    status: ' NULL',
    location: 'BVH',
    supplements: ' NULL',
    micronutrients: ' NULL',
    health_insurance_id: ' NULL',
    appointment_status: 'On Time',
    muac_status: ' NULL',
    response_status: ' NULL',
    risk_level: 'red_alert',
    bmi: 0,
    muac: 0,
    lmp: 0,
    bp: ' NULL',
    mother_symptoms: 'Hypothermia, Fever',
    ethnicity: ' NULL',
    household: ' NULL',
    toilet: ' NULL',
    handwashing: ' NULL',
    planned_delivery_location: ' NULL',
    death_date: 0,
    location_of_death: ' NULL',
    death_code: ' NULL',
    logface_risk: 'red',
    death_reason: ' NULL',
    child_symptoms: 'Hypothermia, Fever',
    delivery_location: 'District hospitals/CDC',
    delivery_method: 'Some delivery method',
    child_risk_level: 'red_alert',
    health_worker_contact: 'telegram:782996367',
    team: ' NULL',
  },
];

export const getEventsPregnancyArrayOutput1 = [
  [
    {
      EventDate: '2019-09-25',
      sms_type: 'Pregnancy Registration',
      anc_id: '100NG6',
      age: '33',
      health_worker_location_name: 'Saigon',
      health_worker_name: 'Husna Hariz',
      height: 160,
      weight: 54,
      previous_risks: 'Diabetes, High blood pressure',
      lmp_edd: '2019-04-01',
      parity: 2,
      gravidity: 3,
      message:
        'EDD = 2019-04-01\nGravidity = 3\nParity = 2\nWeight = 54 \nHeight = 160\nPrevious Gynaecology History = Diabetes, High blood pressure\nCurrent Symptoms = Flaccid Paralysis',
      event_date: '2019-09-25T18:35:13.412000',
      intervention: ' NULL',
      breastfeeding: ' NULL',
      client_type: 'ec_woman',
      gender: 'F',
      child_no: ' NULL',
      first_name: 'habiba',
      second_name: ' NULL',
      third_name: ' NULL',
      last_name: ' NULL',
      date_of_birth: 0,
      year_of_birth: 1986,
      patient_contact: ' NULL',
      location_id: '1234567890987654321',
      contact: '0',
      anc_visit_date: '2019-09-25',
      next_anc_date: '2019-10-22',
      event_id: '1569422113576',
      symptoms: 'LM',
      status: ' NULL',
      location: ' NULL',
      supplements: ' NULL',
      micronutrients: ' NULL',
      health_insurance_id: ' NULL',
      appointment_status: 'On Time',
      muac_status: ' NULL',
      response_status: ' NULL',
      risk_level: 'high',
      bmi: 21,
      muac: 0,
      lmp: '2018-06-25',
      bp: '123-78',
      mother_symptoms: 'Flaccid Paralysis',
      ethnicity: ' NULL',
      household: ' NULL',
      toilet: ' NULL',
      handwashing: ' NULL',
      planned_delivery_location: ' NULL',
      death_date: 0,
      location_of_death: ' NULL',
      death_code: ' NULL',
      logface_risk: 'high',
      death_reason: ' NULL',
      child_symptoms: ' NULL',
      delivery_location: ' NULL',
      delivery_method: ' NULL',
      child_risk_level: ' NULL',
      health_worker_contact: 'telegram:782996367',
      team: ' NULL',
    },
    {
      EventDate: '2019-09-25',
      sms_type: 'Birth Report',
      anc_id: '100NG6',
      age: '-1',
      health_worker_location_name: 'Saigon',
      health_worker_name: 'Husna Hariz',
      height: 31,
      weight: 25,
      previous_risks: ' NULL',
      lmp_edd: 0,
      parity: 0,
      gravidity: 0,
      message:
        'Child DOB = 2020-01-01 \nChild Gender = M \nDelivery Location = District hospitals/CDC \nNewborn Symptoms = Hypothermia, Fever \nChild Weight = 25 \nChild Length = 31 \nChild Risk = red_alert \nBreastfeeding = Breastfeeding during 1st hour',
      event_date: '2019-09-25T19:04:40.435000',
      intervention: ' NULL',
      breastfeeding: 'Breastfeeding during 1st hour',
      client_type: 'ec_woman',
      gender: 'M',
      child_no: '100NG6-20200101-1',
      first_name: 'habiba',
      second_name: ' NULL',
      third_name: ' NULL',
      last_name: ' NULL',
      date_of_birth: 0,
      year_of_birth: 2020,
      patient_contact: ' NULL',
      location_id: '1234567890987654321',
      contact: '4',
      anc_visit_date: 0,
      next_anc_date: 0,
      event_id: '1569423880614',
      symptoms: 'HNH SOT',
      status: ' NULL',
      location: 'BVH',
      supplements: ' NULL',
      micronutrients: ' NULL',
      health_insurance_id: ' NULL',
      appointment_status: 'On Time',
      muac_status: ' NULL',
      response_status: ' NULL',
      risk_level: 'red_alert',
      bmi: 0,
      muac: 0,
      lmp: 0,
      bp: ' NULL',
      mother_symptoms: 'Hypothermia, Fever',
      ethnicity: ' NULL',
      household: ' NULL',
      toilet: ' NULL',
      handwashing: ' NULL',
      planned_delivery_location: ' NULL',
      death_date: 0,
      location_of_death: ' NULL',
      death_code: ' NULL',
      logface_risk: 'red',
      death_reason: ' NULL',
      child_symptoms: 'Hypothermia, Fever',
      delivery_location: 'District hospitals/CDC',
      delivery_method: 'Some delivery method',
      child_risk_level: 'red_alert',
      health_worker_contact: 'telegram:782996367',
      team: ' NULL',
    },
    {
      EventDate: '2019-09-25',
      sms_type: 'Birth Report',
      anc_id: '100NG6',
      age: '-1',
      health_worker_location_name: 'Saigon',
      health_worker_name: 'Husna Hariz',
      height: 31,
      weight: 25,
      previous_risks: ' NULL',
      lmp_edd: 0,
      parity: 0,
      gravidity: 0,
      message:
        'Child DOB = 2020-04-01 \nChild Gender = M \nDelivery Location = District hospitals/CDC \nNewborn Symptoms = Hypothermia, Fever \nChild Weight = 25 \nChild Length = 31 \nChild Risk = red_alert \nBreastfeeding = Breastfeeding during 1st hour',
      event_date: '2019-09-25T19:09:11.619000',
      intervention: ' NULL',
      breastfeeding: 'Breastfeeding during 1st hour',
      client_type: 'ec_woman',
      gender: 'M',
      child_no: '100NG6-20200401-1',
      first_name: 'habiba',
      second_name: ' NULL',
      third_name: ' NULL',
      last_name: ' NULL',
      date_of_birth: 0,
      year_of_birth: 2020,
      patient_contact: ' NULL',
      location_id: '1234567890987654321',
      contact: '4',
      anc_visit_date: 0,
      next_anc_date: 0,
      event_id: '1569424151860',
      symptoms: 'HNH SOT',
      status: ' NULL',
      location: 'BVH',
      supplements: ' NULL',
      micronutrients: ' NULL',
      health_insurance_id: ' NULL',
      appointment_status: 'On Time',
      muac_status: ' NULL',
      response_status: ' NULL',
      risk_level: 'red_alert',
      bmi: 0,
      muac: 0,
      lmp: 0,
      bp: ' NULL',
      mother_symptoms: 'Hypothermia, Fever',
      ethnicity: ' NULL',
      household: ' NULL',
      toilet: ' NULL',
      handwashing: ' NULL',
      planned_delivery_location: ' NULL',
      death_date: 0,
      location_of_death: ' NULL',
      death_code: ' NULL',
      logface_risk: 'red',
      death_reason: ' NULL',
      child_symptoms: 'Hypothermia, Fever',
      delivery_location: 'District hospitals/CDC',
      delivery_method: 'Some delivery method',
      child_risk_level: 'red_alert',
      health_worker_contact: 'telegram:782996367',
      team: ' NULL',
    },
    {
      EventDate: '2019-09-27',
      sms_type: 'Birth Report',
      anc_id: '100NG6',
      age: '-1',
      health_worker_location_name: 'Saigon',
      health_worker_name: 'Husna Hariz',
      height: 31,
      weight: 25,
      previous_risks: ' NULL',
      lmp_edd: 0,
      parity: 0,
      gravidity: 0,
      message:
        'Child DOB = 2020-04-01 \nChild Gender = M \nDelivery Location = District hospitals/CDC \nNewborn Symptoms = Hypothermia, Fever \nChild Weight = 25 \nChild Length = 31 \nChild Risk = red_alert \nBreastfeeding = Breastfeeding during 1st hour',
      event_date: '2019-09-27T11:26:49.742000',
      intervention: ' NULL',
      breastfeeding: 'Breastfeeding during 1st hour',
      client_type: 'ec_woman',
      gender: 'M',
      child_no: '100NG6-20200401-1',
      first_name: 'habiba',
      second_name: ' NULL',
      third_name: ' NULL',
      last_name: ' NULL',
      date_of_birth: 0,
      year_of_birth: 2020,
      patient_contact: ' NULL',
      location_id: '1234567890987654321',
      contact: '4',
      anc_visit_date: 0,
      next_anc_date: 0,
      event_id: '1569569210908',
      symptoms: 'HNH SOT',
      status: ' NULL',
      location: 'BVH',
      supplements: ' NULL',
      micronutrients: ' NULL',
      health_insurance_id: ' NULL',
      appointment_status: 'On Time',
      muac_status: ' NULL',
      response_status: ' NULL',
      risk_level: 'red_alert',
      bmi: 0,
      muac: 0,
      lmp: 0,
      bp: ' NULL',
      mother_symptoms: 'Hypothermia, Fever',
      ethnicity: ' NULL',
      household: ' NULL',
      toilet: ' NULL',
      handwashing: ' NULL',
      planned_delivery_location: ' NULL',
      death_date: 0,
      location_of_death: ' NULL',
      death_code: ' NULL',
      logface_risk: 'red',
      death_reason: ' NULL',
      child_symptoms: 'Hypothermia, Fever',
      delivery_location: 'District hospitals/CDC',
      delivery_method: 'Some delivery method',
      child_risk_level: 'red_alert',
      health_worker_contact: 'telegram:782996367',
      team: ' NULL',
    },
    {
      EventDate: '2019-09-27',
      sms_type: 'Birth Report',
      anc_id: '100NG6',
      age: '-1',
      health_worker_location_name: 'Saigon',
      health_worker_name: 'Husna Hariz',
      height: 31,
      weight: 25,
      previous_risks: ' NULL',
      lmp_edd: 0,
      parity: 0,
      gravidity: 0,
      message:
        'Child DOB = 2020-04-01 \nChild Gender = M \nDelivery Location = District hospitals/CDC \nNewborn Symptoms = Hypothermia, Fever \nChild Weight = 25 \nChild Length = 31 \nChild Risk = red_alert \nBreastfeeding = Breastfeeding during 1st hour',
      event_date: '2019-09-27T11:30:25.236000',
      intervention: ' NULL',
      breastfeeding: 'Breastfeeding during 1st hour',
      client_type: 'ec_woman',
      gender: 'M',
      child_no: '100NG6-20200401-1',
      first_name: 'habiba',
      second_name: ' NULL',
      third_name: ' NULL',
      last_name: ' NULL',
      date_of_birth: 0,
      year_of_birth: 2020,
      patient_contact: ' NULL',
      location_id: '1234567890987654321',
      contact: '4',
      anc_visit_date: 0,
      next_anc_date: 0,
      event_id: '1569569425411',
      symptoms: 'HNH SOT',
      status: ' NULL',
      location: 'BVH',
      supplements: ' NULL',
      micronutrients: ' NULL',
      health_insurance_id: ' NULL',
      appointment_status: 'On Time',
      muac_status: ' NULL',
      response_status: ' NULL',
      risk_level: 'red_alert',
      bmi: 0,
      muac: 0,
      lmp: 0,
      bp: ' NULL',
      mother_symptoms: 'Hypothermia, Fever',
      ethnicity: ' NULL',
      household: ' NULL',
      toilet: ' NULL',
      handwashing: ' NULL',
      planned_delivery_location: ' NULL',
      death_date: 0,
      location_of_death: ' NULL',
      death_code: ' NULL',
      logface_risk: 'red',
      death_reason: ' NULL',
      child_symptoms: 'Hypothermia, Fever',
      delivery_location: 'District hospitals/CDC',
      delivery_method: 'Some delivery method',
      child_risk_level: 'red_alert',
      health_worker_contact: 'telegram:782996367',
      team: ' NULL',
    },
    {
      EventDate: '2019-09-27',
      sms_type: 'Birth Report',
      anc_id: '100NG6',
      age: '-1',
      health_worker_location_name: 'Saigon',
      health_worker_name: 'Husna Hariz',
      height: 31,
      weight: 25,
      previous_risks: ' NULL',
      lmp_edd: 0,
      parity: 0,
      gravidity: 0,
      message:
        'Child DOB = 2020-04-01 \nChild Gender = M \nDelivery Location = District hospitals/CDC \nNewborn Symptoms = Hypothermia, Fever \nChild Weight = 25 \nChild Length = 31 \nChild Risk = red_alert \nBreastfeeding = Breastfeeding during 1st hour',
      event_date: '2019-09-27T11:45:02.606000',
      intervention: ' NULL',
      breastfeeding: 'Breastfeeding during 1st hour',
      client_type: 'ec_woman',
      gender: 'M',
      child_no: '100NG6-20200401-1',
      first_name: 'habiba',
      second_name: ' NULL',
      third_name: ' NULL',
      last_name: ' NULL',
      date_of_birth: 0,
      year_of_birth: 2020,
      patient_contact: ' NULL',
      location_id: '1234567890987654321',
      contact: '4',
      anc_visit_date: 0,
      next_anc_date: 0,
      event_id: '1569570302932',
      symptoms: 'HNH SOT',
      status: ' NULL',
      location: 'BVH',
      supplements: ' NULL',
      micronutrients: ' NULL',
      health_insurance_id: ' NULL',
      appointment_status: 'On Time',
      muac_status: ' NULL',
      response_status: ' NULL',
      risk_level: 'red_alert',
      bmi: 0,
      muac: 0,
      lmp: 0,
      bp: ' NULL',
      mother_symptoms: 'Hypothermia, Fever',
      ethnicity: ' NULL',
      household: ' NULL',
      toilet: ' NULL',
      handwashing: ' NULL',
      planned_delivery_location: ' NULL',
      death_date: 0,
      location_of_death: ' NULL',
      death_code: ' NULL',
      logface_risk: 'red',
      death_reason: ' NULL',
      child_symptoms: 'Hypothermia, Fever',
      delivery_location: 'District hospitals/CDC',
      delivery_method: 'Some delivery method',
      child_risk_level: 'red_alert',
      health_worker_contact: 'telegram:782996367',
      team: ' NULL',
    },
  ],
];

export const getEventsPregnancyArrayInput2 = [
  {
    EventDate: '2019-09-27',
    sms_type: 'Pregnancy Detection',
    anc_id: '100NH4',
    age: '34',
    health_worker_location_name: 'Saigon',
    health_worker_name: 'Husna Hariz',
    height: 0,
    weight: 0,
    previous_risks: ' NULL',
    lmp_edd: 0,
    parity: 0,
    gravidity: 0,
    message: 'Name = Diana Amber Decker \nPhone Number = +84995678456 \nHealth Insurance = ',
    event_date: '2019-09-27T08:43:02.476000',
    intervention: ' NULL',
    breastfeeding: ' NULL',
    client_type: 'ec_woman',
    gender: 'F',
    child_no: ' NULL',
    first_name: 'Diana',
    second_name: 'Amber',
    third_name: 'Decker',
    last_name: ' NULL',
    date_of_birth: 0,
    year_of_birth: 1985,
    patient_contact: '+84995678456',
    location_id: '1234567890987654321',
    contact: ' NULL',
    anc_visit_date: 0,
    next_anc_date: 0,
    event_id: '1569573782617',
    symptoms: ' NULL',
    status: ' NULL',
    location: ' NULL',
    supplements: ' NULL',
    micronutrients: ' NULL',
    health_insurance_id: ' NULL',
    appointment_status: 'On Time',
    muac_status: ' NULL',
    response_status: ' NULL',
    risk_level: ' NULL',
    bmi: 0,
    muac: 0,
    lmp: 0,
    bp: ' NULL',
    mother_symptoms: ' NULL',
    ethnicity: ' NULL',
    household: ' NULL',
    toilet: ' NULL',
    handwashing: ' NULL',
    planned_delivery_location: ' NULL',
    death_date: 0,
    location_of_death: ' NULL',
    death_code: ' NULL',
    logface_risk: 'Not Set',
    death_reason: ' NULL',
    child_symptoms: ' NULL',
    delivery_location: ' NULL',
    delivery_method: ' NULL',
    child_risk_level: ' NULL',
    health_worker_contact: 'telegram:782996367',
    team: ' NULL',
  },
];
export const getEventsPregnancyArrayOutput2 = [];

export const reportTableProps = [
  {
    EventDate: '2019-09-25',
    sms_type: 'Pregnancy Detection',
    anc_id: '100NG6',
    age: '33',
    health_worker_location_name: 'Saigon',
    health_worker_name: 'Husna Hariz',
    height: 0,
    weight: 0,
    previous_risks: ' NULL',
    lmp_edd: 0,
    parity: 0,
    gravidity: 0,
    message: 'Name = habiba farsy  \nPhone Number = +84984664991 \nHealth Insurance = ',
    event_date: '2019-09-25T14:34:47.592000',
    intervention: ' NULL',
    breastfeeding: ' NULL',
    client_type: 'ec_woman',
    gender: 'F',
    child_no: ' NULL',
    first_name: 'habiba',
    second_name: 'farsy',
    third_name: ' NULL',
    last_name: ' NULL',
    date_of_birth: 0,
    year_of_birth: 1986,
    patient_contact: '+84984664991',
    location_id: '1234567890987654321',
    contact: ' NULL',
    anc_visit_date: 0,
    next_anc_date: 0,
    event_id: '1569422087742',
    symptoms: ' NULL',
    status: ' NULL',
    location: ' NULL',
    supplements: ' NULL',
    micronutrients: ' NULL',
    health_insurance_id: ' NULL',
    appointment_status: 'On Time',
    muac_status: ' NULL',
    response_status: ' NULL',
    risk_level: ' NULL',
    bmi: 0,
    muac: 0,
    lmp: 0,
    bp: ' NULL',
    mother_symptoms: ' NULL',
    ethnicity: ' NULL',
    household: ' NULL',
    toilet: ' NULL',
    handwashing: ' NULL',
    planned_delivery_location: ' NULL',
    death_date: 0,
    location_of_death: ' NULL',
    death_code: ' NULL',
    logface_risk: 'Not Set',
    death_reason: ' NULL',
    child_symptoms: ' NULL',
    delivery_location: ' NULL',
    delivery_method: ' NULL',
    child_risk_level: ' NULL',
    health_worker_contact: 'telegram:782996367',
    team: ' NULL',
  },
  {
    EventDate: '2019-09-25',
    sms_type: 'Pregnancy Registration',
    anc_id: '100NG6',
    age: '33',
    health_worker_location_name: 'Saigon',
    health_worker_name: 'Husna Hariz',
    height: 160,
    weight: 54,
    previous_risks: 'Diabetes, High blood pressure',
    lmp_edd: '2019-04-01',
    parity: 2,
    gravidity: 3,
    message:
      'EDD = 2019-04-01\nGravidity = 3\nParity = 2\nWeight = 54 \nHeight = 160\nPrevious Gynaecology History = Diabetes, High blood pressure\nCurrent Symptoms = Flaccid Paralysis',
    event_date: '2019-09-25T18:35:13.412000',
    intervention: ' NULL',
    breastfeeding: ' NULL',
    client_type: 'ec_woman',
    gender: 'F',
    child_no: ' NULL',
    first_name: 'habiba',
    second_name: ' NULL',
    third_name: ' NULL',
    last_name: ' NULL',
    date_of_birth: 0,
    year_of_birth: 1986,
    patient_contact: ' NULL',
    location_id: '1234567890987654321',
    contact: '0',
    anc_visit_date: '2019-09-25',
    next_anc_date: '2019-10-22',
    event_id: '1569422113576',
    symptoms: 'LM',
    status: ' NULL',
    location: ' NULL',
    supplements: ' NULL',
    micronutrients: ' NULL',
    health_insurance_id: ' NULL',
    appointment_status: 'On Time',
    muac_status: ' NULL',
    response_status: ' NULL',
    risk_level: 'high',
    bmi: 21,
    muac: 0,
    lmp: '2018-06-25',
    bp: '123-78',
    mother_symptoms: 'Flaccid Paralysis',
    ethnicity: ' NULL',
    household: ' NULL',
    toilet: ' NULL',
    handwashing: ' NULL',
    planned_delivery_location: ' NULL',
    death_date: 0,
    location_of_death: ' NULL',
    death_code: ' NULL',
    logface_risk: 'high',
    death_reason: ' NULL',
    child_symptoms: ' NULL',
    delivery_location: ' NULL',
    delivery_method: ' NULL',
    child_risk_level: ' NULL',
    health_worker_contact: 'telegram:782996367',
    team: ' NULL',
  },
  {
    EventDate: '2019-09-25',
    sms_type: 'ANC Visit',
    anc_id: '100NG6',
    age: '33',
    health_worker_location_name: 'Saigon',
    health_worker_name: 'Husna Hariz',
    height: 0,
    weight: 67,
    previous_risks: ' NULL',
    lmp_edd: 0,
    parity: 0,
    gravidity: 0,
    message:
      'Blood Pressure = 119-68\nWeight = 67\nCurrent Symptoms = Coughing\nSupplements = Takes Supplements\nRisk = high\nContact = 1',
    event_date: '2019-09-25T18:37:45.264000',
    intervention: ' NULL',
    breastfeeding: ' NULL',
    client_type: 'ec_woman',
    gender: 'F',
    child_no: ' NULL',
    first_name: 'habiba',
    second_name: ' NULL',
    third_name: ' NULL',
    last_name: ' NULL',
    date_of_birth: 0,
    year_of_birth: 1986,
    patient_contact: ' NULL',
    location_id: '1234567890987654321',
    contact: '1',
    anc_visit_date: '2019-10-22',
    next_anc_date: '2019-12-12',
    event_id: '1569422265409',
    symptoms: 'HO',
    status: ' NULL',
    location: ' NULL',
    supplements: 'Takes Supplements',
    micronutrients: ' NULL',
    health_insurance_id: ' NULL',
    appointment_status: 'On Time',
    muac_status: ' NULL',
    response_status: ' NULL',
    risk_level: 'high',
    bmi: 0,
    muac: 0,
    lmp: 0,
    bp: '119-68',
    mother_symptoms: 'Coughing',
    ethnicity: ' NULL',
    household: ' NULL',
    toilet: ' NULL',
    handwashing: ' NULL',
    planned_delivery_location: ' NULL',
    death_date: 0,
    location_of_death: ' NULL',
    death_code: ' NULL',
    logface_risk: 'high',
    death_reason: ' NULL',
    child_symptoms: ' NULL',
    delivery_location: ' NULL',
    delivery_method: ' NULL',
    child_risk_level: ' NULL',
    health_worker_contact: 'telegram:782996367',
    team: ' NULL',
  },
  {
    EventDate: '2019-09-25',
    sms_type: 'ANC Visit',
    anc_id: '100NG6',
    age: '33',
    health_worker_location_name: 'Saigon',
    health_worker_name: 'Husna Hariz',
    height: 0,
    weight: 67,
    previous_risks: ' NULL',
    lmp_edd: 0,
    parity: 0,
    gravidity: 0,
    message:
      'Blood Pressure = 119-68\nWeight = 67\nCurrent Symptoms = Coughing\nSupplements = Takes Supplements\nRisk = high\nContact = 2',
    event_date: '2019-09-25T18:39:11.560000',
    intervention: ' NULL',
    breastfeeding: ' NULL',
    client_type: 'ec_woman',
    gender: 'F',
    child_no: ' NULL',
    first_name: 'habiba',
    second_name: ' NULL',
    third_name: ' NULL',
    last_name: ' NULL',
    date_of_birth: 0,
    year_of_birth: 1986,
    patient_contact: ' NULL',
    location_id: '1234567890987654321',
    contact: '2',
    anc_visit_date: '2019-11-22',
    next_anc_date: '2019-12-12',
    event_id: '1569422351719',
    symptoms: 'HO',
    status: ' NULL',
    location: ' NULL',
    supplements: 'Takes Supplements',
    micronutrients: ' NULL',
    health_insurance_id: ' NULL',
    appointment_status: 'On Time',
    muac_status: ' NULL',
    response_status: ' NULL',
    risk_level: 'high',
    bmi: 0,
    muac: 0,
    lmp: 0,
    bp: '119-68',
    mother_symptoms: 'Coughing',
    ethnicity: ' NULL',
    household: ' NULL',
    toilet: ' NULL',
    handwashing: ' NULL',
    planned_delivery_location: ' NULL',
    death_date: 0,
    location_of_death: ' NULL',
    death_code: ' NULL',
    logface_risk: 'high',
    death_reason: ' NULL',
    child_symptoms: ' NULL',
    delivery_location: ' NULL',
    delivery_method: ' NULL',
    child_risk_level: ' NULL',
    health_worker_contact: 'telegram:782996367',
    team: ' NULL',
  },
  {
    EventDate: '2019-09-25',
    sms_type: 'Delivery Planning',
    anc_id: '100NG6',
    age: '33',
    health_worker_location_name: 'Saigon',
    health_worker_name: 'Husna Hariz',
    height: 0,
    weight: 0,
    previous_risks: ' NULL',
    lmp_edd: 0,
    parity: 0,
    gravidity: 0,
    message: 'Planned Delivery Location = At home \nCurrent Symptoms = No symptoms',
    event_date: '2019-09-25T18:40:35.036000',
    intervention: ' NULL',
    breastfeeding: ' NULL',
    client_type: 'ec_woman',
    gender: 'F',
    child_no: ' NULL',
    first_name: 'habiba',
    second_name: ' NULL',
    third_name: ' NULL',
    last_name: ' NULL',
    date_of_birth: 0,
    year_of_birth: 1986,
    patient_contact: ' NULL',
    location_id: '1234567890987654321',
    contact: '2',
    anc_visit_date: 0,
    next_anc_date: '2019-12-12',
    event_id: '1569422435185',
    symptoms: 'BT',
    status: ' NULL',
    location: 'NHA',
    supplements: ' NULL',
    micronutrients: ' NULL',
    health_insurance_id: ' NULL',
    appointment_status: 'On Time',
    muac_status: ' NULL',
    response_status: ' NULL',
    risk_level: 'no_risk',
    bmi: 0,
    muac: 0,
    lmp: 0,
    bp: ' NULL',
    mother_symptoms: 'No symptoms',
    ethnicity: ' NULL',
    household: ' NULL',
    toilet: ' NULL',
    handwashing: ' NULL',
    planned_delivery_location: 'At home',
    death_date: 0,
    location_of_death: ' NULL',
    death_code: ' NULL',
    logface_risk: 'no risk',
    death_reason: ' NULL',
    child_symptoms: ' NULL',
    delivery_location: ' NULL',
    delivery_method: ' NULL',
    child_risk_level: ' NULL',
    health_worker_contact: 'telegram:782996367',
    team: ' NULL',
  },
  {
    EventDate: '2019-09-25',
    sms_type: 'Social Determinants',
    anc_id: '100NG6',
    age: '33',
    health_worker_location_name: 'Saigon',
    health_worker_name: 'Husna Hariz',
    height: 0,
    weight: 0,
    previous_risks: ' NULL',
    lmp_edd: 0,
    parity: 0,
    gravidity: 0,
    message:
      'Planned Delivery Location = At home\nHousehold = HNG\nEthnicity = TAY\nToilet = Has no toilet\nHandwashing = Has no handwashing',
    event_date: '2019-09-25T18:41:54.819000',
    intervention: ' NULL',
    breastfeeding: ' NULL',
    client_type: 'ec_woman',
    gender: 'F',
    child_no: ' NULL',
    first_name: 'habiba',
    second_name: ' NULL',
    third_name: ' NULL',
    last_name: ' NULL',
    date_of_birth: 0,
    year_of_birth: 1986,
    patient_contact: ' NULL',
    location_id: '1234567890987654321',
    contact: '2',
    anc_visit_date: 0,
    next_anc_date: 0,
    event_id: '1569422514986',
    symptoms: ' NULL',
    status: ' NULL',
    location: 'NHA',
    supplements: ' NULL',
    micronutrients: ' NULL',
    health_insurance_id: ' NULL',
    appointment_status: 'On Time',
    muac_status: ' NULL',
    response_status: ' NULL',
    risk_level: 'no_risk',
    bmi: 0,
    muac: 0,
    lmp: 0,
    bp: ' NULL',
    mother_symptoms: ' NULL',
    ethnicity: 'TAY',
    household: 'HNG',
    toilet: 'Has no toilet',
    handwashing: 'Has no handwashing',
    planned_delivery_location: 'At home',
    death_date: 0,
    location_of_death: ' NULL',
    death_code: ' NULL',
    logface_risk: 'no risk',
    death_reason: ' NULL',
    child_symptoms: ' NULL',
    delivery_location: ' NULL',
    delivery_method: ' NULL',
    child_risk_level: ' NULL',
    health_worker_contact: 'telegram:782996367',
    team: ' NULL',
  },
  {
    EventDate: '2019-09-25',
    sms_type: 'ANC Visit',
    anc_id: '100NG6',
    age: '33',
    health_worker_location_name: 'Saigon',
    health_worker_name: 'Husna Hariz',
    height: 0,
    weight: 68,
    previous_risks: ' NULL',
    lmp_edd: 0,
    parity: 0,
    gravidity: 0,
    message:
      'Blood Pressure = 130-78\nWeight = 68\nCurrent Symptoms = Coughing, Fever, Chronic Disease, Congenital malformation\nSupplements = Takes Supplements\nRisk = high\nContact = 3',
    event_date: '2019-09-25T18:58:28.478000',
    intervention: ' NULL',
    breastfeeding: ' NULL',
    client_type: 'ec_woman',
    gender: 'F',
    child_no: ' NULL',
    first_name: 'habiba',
    second_name: ' NULL',
    third_name: ' NULL',
    last_name: ' NULL',
    date_of_birth: 0,
    year_of_birth: 1986,
    patient_contact: ' NULL',
    location_id: '1234567890987654321',
    contact: '3',
    anc_visit_date: '2019-12-22',
    next_anc_date: '2020-02-12',
    event_id: '1569423508727',
    symptoms: 'HO SOT KN DG',
    status: ' NULL',
    location: 'NHA',
    supplements: 'Takes Supplements',
    micronutrients: ' NULL',
    health_insurance_id: ' NULL',
    appointment_status: 'On Time',
    muac_status: ' NULL',
    response_status: ' NULL',
    risk_level: 'high',
    bmi: 0,
    muac: 0,
    lmp: 0,
    bp: '130-78',
    mother_symptoms: 'Coughing, Fever, Chronic Disease, Congenital malformation',
    ethnicity: ' NULL',
    household: ' NULL',
    toilet: ' NULL',
    handwashing: ' NULL',
    planned_delivery_location: ' NULL',
    death_date: 0,
    location_of_death: ' NULL',
    death_code: ' NULL',
    logface_risk: 'high',
    death_reason: ' NULL',
    child_symptoms: ' NULL',
    delivery_location: ' NULL',
    delivery_method: ' NULL',
    child_risk_level: ' NULL',
    health_worker_contact: 'telegram:782996367',
    team: ' NULL',
  },
  {
    EventDate: '2019-09-25',
    sms_type: 'ANC Visit',
    anc_id: '100NG6',
    age: '33',
    health_worker_location_name: 'Saigon',
    health_worker_name: 'Husna Hariz',
    height: 0,
    weight: 68,
    previous_risks: ' NULL',
    lmp_edd: 0,
    parity: 0,
    gravidity: 0,
    message:
      'Blood Pressure = 130-78\nWeight = 68\nCurrent Symptoms = Coughing, Fever, Chronic Disease, Congenital malformation\nSupplements = Takes Supplements\nRisk = high\nContact = 4',
    event_date: '2019-09-25T19:00:56.009000',
    intervention: ' NULL',
    breastfeeding: ' NULL',
    client_type: 'ec_woman',
    gender: 'F',
    child_no: ' NULL',
    first_name: 'habiba',
    second_name: ' NULL',
    third_name: ' NULL',
    last_name: ' NULL',
    date_of_birth: 0,
    year_of_birth: 1986,
    patient_contact: ' NULL',
    location_id: '1234567890987654321',
    contact: '4',
    anc_visit_date: '2020-02-22',
    next_anc_date: '2020-03-12',
    event_id: '1569423656162',
    symptoms: 'HO SOT KN DG',
    status: ' NULL',
    location: 'NHA',
    supplements: 'Takes Supplements',
    micronutrients: ' NULL',
    health_insurance_id: ' NULL',
    appointment_status: 'On Time',
    muac_status: ' NULL',
    response_status: ' NULL',
    risk_level: 'high',
    bmi: 0,
    muac: 0,
    lmp: 0,
    bp: '130-78',
    mother_symptoms: 'Coughing, Fever, Chronic Disease, Congenital malformation',
    ethnicity: ' NULL',
    household: ' NULL',
    toilet: ' NULL',
    handwashing: ' NULL',
    planned_delivery_location: ' NULL',
    death_date: 0,
    location_of_death: ' NULL',
    death_code: ' NULL',
    logface_risk: 'high',
    death_reason: ' NULL',
    child_symptoms: ' NULL',
    delivery_location: ' NULL',
    delivery_method: ' NULL',
    child_risk_level: ' NULL',
    health_worker_contact: 'telegram:782996367',
    team: ' NULL',
  },
  {
    EventDate: '2019-09-25',
    sms_type: 'Birth Report',
    anc_id: '100NG6',
    age: '-1',
    health_worker_location_name: 'Saigon',
    health_worker_name: 'Husna Hariz',
    height: 31,
    weight: 25,
    previous_risks: ' NULL',
    lmp_edd: 0,
    parity: 0,
    gravidity: 0,
    message:
      'Child DOB = 2020-01-01 \nChild Gender = M \nDelivery Location = District hospitals/CDC \nNewborn Symptoms = Hypothermia, Fever \nChild Weight = 25 \nChild Length = 31 \nChild Risk = red_alert \nBreastfeeding = Breastfeeding during 1st hour',
    event_date: '2019-09-25T19:04:40.435000',
    intervention: ' NULL',
    breastfeeding: 'Breastfeeding during 1st hour',
    client_type: 'ec_woman',
    gender: 'M',
    child_no: '100NG6-20200101-1',
    first_name: 'habiba',
    second_name: ' NULL',
    third_name: ' NULL',
    last_name: ' NULL',
    date_of_birth: 0,
    year_of_birth: 2020,
    patient_contact: ' NULL',
    location_id: '1234567890987654321',
    contact: '4',
    anc_visit_date: 0,
    next_anc_date: 0,
    event_id: '1569423880614',
    symptoms: 'HNH SOT',
    status: ' NULL',
    location: 'BVH',
    supplements: ' NULL',
    micronutrients: ' NULL',
    health_insurance_id: ' NULL',
    appointment_status: 'On Time',
    muac_status: ' NULL',
    response_status: ' NULL',
    risk_level: 'red_alert',
    bmi: 0,
    muac: 0,
    lmp: 0,
    bp: ' NULL',
    mother_symptoms: 'Hypothermia, Fever',
    ethnicity: ' NULL',
    household: ' NULL',
    toilet: ' NULL',
    handwashing: ' NULL',
    planned_delivery_location: ' NULL',
    death_date: 0,
    location_of_death: ' NULL',
    death_code: ' NULL',
    logface_risk: 'red',
    death_reason: ' NULL',
    child_symptoms: 'Hypothermia, Fever',
    delivery_location: 'District hospitals/CDC',
    delivery_method: 'Some delivery method',
    child_risk_level: 'red_alert',
    health_worker_contact: 'telegram:782996367',
    team: ' NULL',
  },
  {
    EventDate: '2019-09-25',
    sms_type: 'Birth Report',
    anc_id: '100NG6',
    age: '-1',
    health_worker_location_name: 'Saigon',
    health_worker_name: 'Husna Hariz',
    height: 31,
    weight: 25,
    previous_risks: ' NULL',
    lmp_edd: 0,
    parity: 0,
    gravidity: 0,
    message:
      'Child DOB = 2020-04-01 \nChild Gender = M \nDelivery Location = District hospitals/CDC \nNewborn Symptoms = Hypothermia, Fever \nChild Weight = 25 \nChild Length = 31 \nChild Risk = red_alert \nBreastfeeding = Breastfeeding during 1st hour',
    event_date: '2019-09-25T19:09:11.619000',
    intervention: ' NULL',
    breastfeeding: 'Breastfeeding during 1st hour',
    client_type: 'ec_woman',
    gender: 'M',
    child_no: '100NG6-20200401-1',
    first_name: 'habiba',
    second_name: ' NULL',
    third_name: ' NULL',
    last_name: ' NULL',
    date_of_birth: 0,
    year_of_birth: 2020,
    patient_contact: ' NULL',
    location_id: '1234567890987654321',
    contact: '4',
    anc_visit_date: 0,
    next_anc_date: 0,
    event_id: '1569424151860',
    symptoms: 'HNH SOT',
    status: ' NULL',
    location: 'BVH',
    supplements: ' NULL',
    micronutrients: ' NULL',
    health_insurance_id: ' NULL',
    appointment_status: 'On Time',
    muac_status: ' NULL',
    response_status: ' NULL',
    risk_level: 'red_alert',
    bmi: 0,
    muac: 0,
    lmp: 0,
    bp: ' NULL',
    mother_symptoms: 'Hypothermia, Fever',
    ethnicity: ' NULL',
    household: ' NULL',
    toilet: ' NULL',
    handwashing: ' NULL',
    planned_delivery_location: ' NULL',
    death_date: 0,
    location_of_death: ' NULL',
    death_code: ' NULL',
    logface_risk: 'red',
    death_reason: ' NULL',
    child_symptoms: 'Hypothermia, Fever',
    delivery_location: 'District hospitals/CDC',
    delivery_method: 'Some delivery method',
    child_risk_level: 'red_alert',
    health_worker_contact: 'telegram:782996367',
    team: ' NULL',
  },
  {
    EventDate: '2019-09-26',
    sms_type: 'Red Alert Report',
    anc_id: '100NG6',
    age: '33',
    health_worker_location_name: 'Saigon',
    health_worker_name: 'Husna Hariz',
    height: 0,
    weight: 0,
    previous_risks: ' NULL',
    lmp_edd: 0,
    parity: 0,
    gravidity: 0,
    message: 'Symptoms = Dark vaginal blood \nLocation = At home \nInterventions = ',
    event_date: '2019-09-26T00:43:17.427000',
    intervention: ' NULL',
    breastfeeding: ' NULL',
    client_type: 'ec_woman',
    gender: 'F',
    child_no: ' NULL',
    first_name: 'habiba',
    second_name: ' NULL',
    third_name: ' NULL',
    last_name: ' NULL',
    date_of_birth: 0,
    year_of_birth: 1986,
    patient_contact: ' NULL',
    location_id: '1234567890987654321',
    contact: ' NULL',
    anc_visit_date: 0,
    next_anc_date: 0,
    event_id: '1569444197999',
    symptoms: 'MD',
    status: ' NULL',
    location: 'At home',
    supplements: ' NULL',
    micronutrients: ' NULL',
    health_insurance_id: ' NULL',
    appointment_status: 'On Time',
    muac_status: ' NULL',
    response_status: ' NULL',
    risk_level: 'red_alert',
    bmi: 0,
    muac: 0,
    lmp: 0,
    bp: ' NULL',
    mother_symptoms: 'Dark vaginal blood',
    ethnicity: ' NULL',
    household: ' NULL',
    toilet: ' NULL',
    handwashing: ' NULL',
    planned_delivery_location: ' NULL',
    death_date: 0,
    location_of_death: ' NULL',
    death_code: ' NULL',
    logface_risk: 'red',
    death_reason: ' NULL',
    child_symptoms: ' NULL',
    delivery_location: ' NULL',
    delivery_method: ' NULL',
    child_risk_level: ' NULL',
    health_worker_contact: 'telegram:782996367',
    team: ' NULL',
  },
  {
    EventDate: '2019-09-26',
    sms_type: 'Red Alert Report',
    anc_id: '100NG6',
    age: '33',
    health_worker_location_name: 'Saigon',
    health_worker_name: 'Husna Hariz',
    height: 0,
    weight: 0,
    previous_risks: ' NULL',
    lmp_edd: 0,
    parity: 0,
    gravidity: 0,
    message: 'Symptoms = Dark vaginal blood \nLocation = At home \nInterventions = ',
    event_date: '2019-09-26T00:48:55.842000',
    intervention: ' NULL',
    breastfeeding: ' NULL',
    client_type: 'ec_woman',
    gender: 'F',
    child_no: ' NULL',
    first_name: 'habiba',
    second_name: ' NULL',
    third_name: ' NULL',
    last_name: ' NULL',
    date_of_birth: 0,
    year_of_birth: 1986,
    patient_contact: ' NULL',
    location_id: '1234567890987654321',
    contact: ' NULL',
    anc_visit_date: 0,
    next_anc_date: 0,
    event_id: '1569444536025',
    symptoms: 'MD',
    status: ' NULL',
    location: 'At home',
    supplements: ' NULL',
    micronutrients: ' NULL',
    health_insurance_id: ' NULL',
    appointment_status: 'On Time',
    muac_status: ' NULL',
    response_status: ' NULL',
    risk_level: 'red_alert',
    bmi: 0,
    muac: 0,
    lmp: 0,
    bp: ' NULL',
    mother_symptoms: 'Dark vaginal blood',
    ethnicity: ' NULL',
    household: ' NULL',
    toilet: ' NULL',
    handwashing: ' NULL',
    planned_delivery_location: ' NULL',
    death_date: 0,
    location_of_death: ' NULL',
    death_code: ' NULL',
    logface_risk: 'red',
    death_reason: ' NULL',
    child_symptoms: ' NULL',
    delivery_location: ' NULL',
    delivery_method: ' NULL',
    child_risk_level: ' NULL',
    health_worker_contact: 'telegram:782996367',
    team: ' NULL',
  },
  {
    EventDate: '2019-09-26',
    sms_type: 'Red Alert Report',
    anc_id: '100NG6',
    age: '33',
    health_worker_location_name: 'Saigon',
    health_worker_name: 'Husna Hariz',
    height: 0,
    weight: 0,
    previous_risks: ' NULL',
    lmp_edd: 0,
    parity: 0,
    gravidity: 0,
    message: 'Symptoms = Dark vaginal blood \nLocation = At home \nInterventions = ',
    event_date: '2019-09-26T00:55:01.344000',
    intervention: ' NULL',
    breastfeeding: ' NULL',
    client_type: 'ec_woman',
    gender: 'F',
    child_no: ' NULL',
    first_name: 'habiba',
    second_name: ' NULL',
    third_name: ' NULL',
    last_name: ' NULL',
    date_of_birth: 0,
    year_of_birth: 1986,
    patient_contact: ' NULL',
    location_id: '1234567890987654321',
    contact: ' NULL',
    anc_visit_date: 0,
    next_anc_date: 0,
    event_id: '1569444901634',
    symptoms: 'MD',
    status: ' NULL',
    location: 'At home',
    supplements: ' NULL',
    micronutrients: ' NULL',
    health_insurance_id: ' NULL',
    appointment_status: 'On Time',
    muac_status: ' NULL',
    response_status: ' NULL',
    risk_level: 'red_alert',
    bmi: 0,
    muac: 0,
    lmp: 0,
    bp: ' NULL',
    mother_symptoms: 'Dark vaginal blood',
    ethnicity: ' NULL',
    household: ' NULL',
    toilet: ' NULL',
    handwashing: ' NULL',
    planned_delivery_location: ' NULL',
    death_date: 0,
    location_of_death: ' NULL',
    death_code: ' NULL',
    logface_risk: 'red',
    death_reason: ' NULL',
    child_symptoms: ' NULL',
    delivery_location: ' NULL',
    delivery_method: ' NULL',
    child_risk_level: ' NULL',
    health_worker_contact: 'telegram:782996367',
    team: ' NULL',
  },
  {
    EventDate: '2019-09-27',
    sms_type: 'Birth Report',
    anc_id: '100NG6',
    age: '-1',
    health_worker_location_name: 'Saigon',
    health_worker_name: 'Husna Hariz',
    height: 31,
    weight: 25,
    previous_risks: ' NULL',
    lmp_edd: 0,
    parity: 0,
    gravidity: 0,
    message:
      'Child DOB = 2020-04-01 \nChild Gender = M \nDelivery Location = District hospitals/CDC \nNewborn Symptoms = Hypothermia, Fever \nChild Weight = 25 \nChild Length = 31 \nChild Risk = red_alert \nBreastfeeding = Breastfeeding during 1st hour',
    event_date: '2019-09-27T11:26:49.742000',
    intervention: ' NULL',
    breastfeeding: 'Breastfeeding during 1st hour',
    client_type: 'ec_woman',
    gender: 'M',
    child_no: '100NG6-20200401-1',
    first_name: 'habiba',
    second_name: ' NULL',
    third_name: ' NULL',
    last_name: ' NULL',
    date_of_birth: 0,
    year_of_birth: 2020,
    patient_contact: ' NULL',
    location_id: '1234567890987654321',
    contact: '4',
    anc_visit_date: 0,
    next_anc_date: 0,
    event_id: '1569569210908',
    symptoms: 'HNH SOT',
    status: ' NULL',
    location: 'BVH',
    supplements: ' NULL',
    micronutrients: ' NULL',
    health_insurance_id: ' NULL',
    appointment_status: 'On Time',
    muac_status: ' NULL',
    response_status: ' NULL',
    risk_level: 'red_alert',
    bmi: 0,
    muac: 0,
    lmp: 0,
    bp: ' NULL',
    mother_symptoms: 'Hypothermia, Fever',
    ethnicity: ' NULL',
    household: ' NULL',
    toilet: ' NULL',
    handwashing: ' NULL',
    planned_delivery_location: ' NULL',
    death_date: 0,
    location_of_death: ' NULL',
    death_code: ' NULL',
    logface_risk: 'red',
    death_reason: ' NULL',
    child_symptoms: 'Hypothermia, Fever',
    delivery_location: 'District hospitals/CDC',
    delivery_method: 'Some delivery method',
    child_risk_level: 'red_alert',
    health_worker_contact: 'telegram:782996367',
    team: ' NULL',
  },
  {
    EventDate: '2019-09-27',
    sms_type: 'Birth Report',
    anc_id: '100NG6',
    age: '-1',
    health_worker_location_name: 'Saigon',
    health_worker_name: 'Husna Hariz',
    height: 31,
    weight: 25,
    previous_risks: ' NULL',
    lmp_edd: 0,
    parity: 0,
    gravidity: 0,
    message:
      'Child DOB = 2020-04-01 \nChild Gender = M \nDelivery Location = District hospitals/CDC \nNewborn Symptoms = Hypothermia, Fever \nChild Weight = 25 \nChild Length = 31 \nChild Risk = red_alert \nBreastfeeding = Breastfeeding during 1st hour',
    event_date: '2019-09-27T11:30:25.236000',
    intervention: ' NULL',
    breastfeeding: 'Breastfeeding during 1st hour',
    client_type: 'ec_woman',
    gender: 'M',
    child_no: '100NG6-20200401-1',
    first_name: 'habiba',
    second_name: ' NULL',
    third_name: ' NULL',
    last_name: ' NULL',
    date_of_birth: 0,
    year_of_birth: 2020,
    patient_contact: ' NULL',
    location_id: '1234567890987654321',
    contact: '4',
    anc_visit_date: 0,
    next_anc_date: 0,
    event_id: '1569569425411',
    symptoms: 'HNH SOT',
    status: ' NULL',
    location: 'BVH',
    supplements: ' NULL',
    micronutrients: ' NULL',
    health_insurance_id: ' NULL',
    appointment_status: 'On Time',
    muac_status: ' NULL',
    response_status: ' NULL',
    risk_level: 'red_alert',
    bmi: 0,
    muac: 0,
    lmp: 0,
    bp: ' NULL',
    mother_symptoms: 'Hypothermia, Fever',
    ethnicity: ' NULL',
    household: ' NULL',
    toilet: ' NULL',
    handwashing: ' NULL',
    planned_delivery_location: ' NULL',
    death_date: 0,
    location_of_death: ' NULL',
    death_code: ' NULL',
    logface_risk: 'red',
    death_reason: ' NULL',
    child_symptoms: 'Hypothermia, Fever',
    delivery_location: 'District hospitals/CDC',
    delivery_method: 'Some delivery method',
    child_risk_level: 'red_alert',
    health_worker_contact: 'telegram:782996367',
    team: ' NULL',
  },
  {
    EventDate: '2019-09-27',
    sms_type: 'Birth Report',
    anc_id: '100NG6',
    age: '-1',
    health_worker_location_name: 'Saigon',
    health_worker_name: 'Husna Hariz',
    height: 31,
    weight: 25,
    previous_risks: ' NULL',
    lmp_edd: 0,
    parity: 0,
    gravidity: 0,
    message:
      'Child DOB = 2020-04-01 \nChild Gender = M \nDelivery Location = District hospitals/CDC \nNewborn Symptoms = Hypothermia, Fever \nChild Weight = 25 \nChild Length = 31 \nChild Risk = red_alert \nBreastfeeding = Breastfeeding during 1st hour',
    event_date: '2019-09-27T11:45:02.606000',
    intervention: ' NULL',
    breastfeeding: 'Breastfeeding during 1st hour',
    client_type: 'ec_woman',
    gender: 'M',
    child_no: '100NG6-20200401-1',
    first_name: 'habiba',
    second_name: ' NULL',
    third_name: ' NULL',
    last_name: ' NULL',
    date_of_birth: 0,
    year_of_birth: 2020,
    patient_contact: ' NULL',
    location_id: '1234567890987654321',
    contact: '4',
    anc_visit_date: 0,
    next_anc_date: 0,
    event_id: '1569570302932',
    symptoms: 'HNH SOT',
    status: ' NULL',
    location: 'BVH',
    supplements: ' NULL',
    micronutrients: ' NULL',
    health_insurance_id: ' NULL',
    appointment_status: 'On Time',
    muac_status: ' NULL',
    response_status: ' NULL',
    risk_level: 'red_alert',
    bmi: 0,
    muac: 0,
    lmp: 0,
    bp: ' NULL',
    mother_symptoms: 'Hypothermia, Fever',
    ethnicity: ' NULL',
    household: ' NULL',
    toilet: ' NULL',
    handwashing: ' NULL',
    planned_delivery_location: ' NULL',
    death_date: 0,
    location_of_death: ' NULL',
    death_code: ' NULL',
    logface_risk: 'red',
    death_reason: ' NULL',
    child_symptoms: 'Hypothermia, Fever',
    delivery_location: 'District hospitals/CDC',
    delivery_method: 'Some delivery method',
    child_risk_level: 'red_alert',
    health_worker_contact: 'telegram:782996367',
    team: ' NULL',
  },
];
export const removeDuplicateWeightsInput1 = [
  {
    weight: 78,
    month: 8,
  },
  {
    weight: 2,
    month: 8,
  },
];

export const removeDuplicateWeightsOutput1 = [
  {
    month: 8,
    weight: 40,
  },
];

export const removeDuplicateWeightsInput2 = [
  {
    weight: 78,
    month: 8,
  },
];

export const emoveDuplicateWeightsOutput2 = [
  {
    month: 8,
    weight: 78,
  },
];
